-- =============================================================================
-- Migration: 20260401_AddEnvironmentAccessControl
-- Description: Add Environments table, UserEnvironments table, and
--              HasWebAccess column to AppUsers for environment-based
--              access control.
-- =============================================================================

-- ─── 1. Environments table ───────────────────────────────────────────────────
-- Already created in the first run — skip if it exists.
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Environments')
BEGIN
    CREATE TABLE [dbo].[Environments] (
        [Id]        UNIQUEIDENTIFIER NOT NULL
                        CONSTRAINT [DF_Environments_Id]        DEFAULT (NEWSEQUENTIALID()),
        [Name]      NVARCHAR(100)    NOT NULL,
        [Code]      NVARCHAR(20)     NOT NULL,
        [IsActive]  BIT              NOT NULL
                        CONSTRAINT [DF_Environments_IsActive]  DEFAULT (1),
        [CreatedAt] DATETIME2(7)     NOT NULL
                        CONSTRAINT [DF_Environments_CreatedAt] DEFAULT (SYSUTCDATETIME()),
        [UpdatedAt] DATETIME2(7)     NOT NULL
                        CONSTRAINT [DF_Environments_UpdatedAt] DEFAULT (SYSUTCDATETIME()),
                        CONSTRAINT [
        CONSTRAINT [PK_Environments]      PRIMARY KEY CLUSTERED ([Id]),
        CONSTRAINT [UQ_Environments_Code] UNIQUE ([Code])
    );

    INSERT INTO [dbo].[Environments] ([Id], [Name], [Code]) VALUES
        (N'A1B2C3D4-0001-4000-8000-000000000D01', N'Development',             N'DEV'),
        (N'A1B2C3D4-0002-4000-8000-000000000D02', N'Quality Assurance',       N'QA'),
        (N'A1B2C3D4-0003-4000-8000-000000000D03', N'User Acceptance Testing', N'UAT'),
        (N'A1B2C3D4-0004-4000-8000-000000000D04', N'Production',              N'PROD');

    PRINT 'Created Environments table and seeded 4 standard rows.';
END
ELSE
BEGIN
    -- For existing databases: update GUIDs to hardcoded values.
    -- Must update FK references in UserEnvironments first, then the PK.
    DECLARE @oldId UNIQUEIDENTIFIER, @newId UNIQUEIDENTIFIER;

    -- DEV
    SELECT @oldId = [Id] FROM [dbo].[Environments] WHERE [Code] = N'DEV';
    SET @newId = N'A1B2C3D4-0001-4000-8000-000000000D01';
    IF @oldId IS NOT NULL AND @oldId <> @newId
    BEGIN
        UPDATE [dbo].[UserEnvironments] SET [EnvironmentId] = @newId WHERE [EnvironmentId] = @oldId;
        UPDATE [dbo].[Environments] SET [Id] = @newId WHERE [Id] = @oldId;
    END

    -- QA
    SELECT @oldId = [Id] FROM [dbo].[Environments] WHERE [Code] = N'QA';
    SET @newId = N'A1B2C3D4-0002-4000-8000-000000000D02';
    IF @oldId IS NOT NULL AND @oldId <> @newId
    BEGIN
        UPDATE [dbo].[UserEnvironments] SET [EnvironmentId] = @newId WHERE [EnvironmentId] = @oldId;
        UPDATE [dbo].[Environments] SET [Id] = @newId WHERE [Id] = @oldId;
    END

    -- UAT
    SELECT @oldId = [Id] FROM [dbo].[Environments] WHERE [Code] = N'UAT';
    SET @newId = N'A1B2C3D4-0003-4000-8000-000000000D03';
    IF @oldId IS NOT NULL AND @oldId <> @newId
    BEGIN
        UPDATE [dbo].[UserEnvironments] SET [EnvironmentId] = @newId WHERE [EnvironmentId] = @oldId;
        UPDATE [dbo].[Environments] SET [Id] = @newId WHERE [Id] = @oldId;
    END

    -- PROD
    SELECT @oldId = [Id] FROM [dbo].[Environments] WHERE [Code] = N'PROD';
    SET @newId = N'A1B2C3D4-0004-4000-8000-000000000D04';
    IF @oldId IS NOT NULL AND @oldId <> @newId
    BEGIN
        UPDATE [dbo].[UserEnvironments] SET [EnvironmentId] = @newId WHERE [EnvironmentId] = @oldId;
        UPDATE [dbo].[Environments] SET [Id] = @newId WHERE [Id] = @oldId;
    END

    PRINT 'Environments table already exists — updated GUIDs to hardcoded values.';
END

-- ─── 2. UserEnvironments table ───────────────────────────────────────────────
-- NOTE: FK references [dbo].[AppUsers] (plural) — the actual SQL table name
--       as generated by EF Core from DbSet<AppUser> AppUsers.
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'UserEnvironments')
BEGIN
    CREATE TABLE [dbo].[UserEnvironments] (
        [Id]            UNIQUEIDENTIFIER NOT NULL
                            CONSTRAINT [DF_UserEnvironments_Id]        DEFAULT (NEWSEQUENTIALID()),
        [UserId]        INT              NOT NULL,
        [CustomerId]    INT              NOT NULL,
        [EnvironmentId] UNIQUEIDENTIFIER NOT NULL,
        [CreatedAt]     DATETIME2(7)     NOT NULL
                            CONSTRAINT [DF_UserEnvironments_CreatedAt] DEFAULT (SYSUTCDATETIME()),

        CONSTRAINT [PK_UserEnvironments] PRIMARY KEY CLUSTERED ([Id]),

        CONSTRAINT [FK_UserEnvironments_AppUsers]
            FOREIGN KEY ([UserId]) REFERENCES [dbo].[AppUsers] ([UserId])
            ON DELETE CASCADE,

        CONSTRAINT [FK_UserEnvironments_Environments]
            FOREIGN KEY ([EnvironmentId]) REFERENCES [dbo].[Environments] ([Id]),

        -- Prevent duplicate mappings for the same user / customer / environment
        CONSTRAINT [UQ_UserEnvironments_User_Env_Customer]
            UNIQUE ([UserId], [EnvironmentId], [CustomerId])
    );

    CREATE NONCLUSTERED INDEX [IX_UserEnvironments_UserId]
        ON [dbo].[UserEnvironments] ([UserId]);

    CREATE NONCLUSTERED INDEX [IX_UserEnvironments_EnvironmentId]
        ON [dbo].[UserEnvironments] ([EnvironmentId]);

    PRINT 'Created UserEnvironments table.';
END
ELSE
BEGIN
    PRINT 'UserEnvironments table already exists — skipped.';
END

-- ─── 3. HasWebAccess column on AppUsers ──────────────────────────────────────
-- Table is [dbo].[AppUsers] (EF Core plural convention).
-- Default = 1 so all existing users retain web access automatically.
IF NOT EXISTS (
    SELECT * FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.AppUsers') AND name = N'HasWebAccess'
)
BEGIN
    ALTER TABLE [dbo].[AppUsers]
        ADD [HasWebAccess] BIT NOT NULL
            CONSTRAINT [DF_AppUsers_HasWebAccess] DEFAULT (1);

    PRINT 'Added HasWebAccess column to AppUsers (default 1 — all existing users retain access).';
END
ELSE
BEGIN
    PRINT 'HasWebAccess column already exists on AppUsers — skipped.';
END
