// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Main;

public partial class App
{
    public int Id { get; set; }

    public int AppId { get; set; }

    public string AppName { get; set; } = null!;

    public string? Comment { get; set; }
}