// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Main;

public partial class ComputerID
{
    public string? ComputerId1 { get; set; }

    public int CustomerId { get; set; }

    public int DeviceId { get; set; }
}