// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Main;

public partial class CustomerDevice
{
    public int DeviceId { get; set; }

    public int CustomerId { get; set; }

    public int? AppId { get; set; }

    public string? DeviceName { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public int? SystemUserCreated { get; set; }

    public int? CurrentAppFilesVersionId { get; set; }

    public string? Description { get; set; }

    public string AdvancedUId { get; set; } = null!;

    public string? ConnectLink { get; set; }

    public int? LicenseId { get; set; }

    public virtual CustomerAppLicense? License { get; set; }
}