// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Main;

public partial class DbVersion
{
    public int Id { get; set; }

    public string DBVersion1 { get; set; } = null!;

    public string? Description { get; set; }

    public string S3Key { get; set; } = null!;

    public DateTime DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public int? SystemUserCreated { get; set; }
}