// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Main;

public partial class Module
{
    public int ModuleId { get; set; }

    public string ModuleName { get; set; } = null!;

    public bool IsDefault { get; set; }

    public string PageURL { get; set; } = null!;

    // --- New RBAC fields ---

    /// <summary>
    /// Unique code for dot-notation, e.g. "sales", "hr", "inventory"
    /// </summary>
    public string? Code { get; set; }

    /// <summary>
    /// Self-referencing FK for sub-modules
    /// </summary>
    public int? ParentModuleId { get; set; }

    public string? Icon { get; set; }

    public int SortOrder { get; set; }

    public bool IsActive { get; set; }

    // --- Navigation properties ---

    public virtual Module? ParentModule { get; set; }

    public virtual ICollection<Module> ChildModules { get; set; } = new List<Module>();

    public virtual ICollection<Screen> Screens { get; set; } = new List<Screen>();

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();

    public virtual ICollection<PlanModule> PlanModules { get; set; } = new List<PlanModule>();

    public virtual ICollection<TenantAllowedModule> TenantAllowedModules { get; set; } = new List<TenantAllowedModule>();
}