// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Main;

public partial class SystemUser
{
    public int UserId { get; set; }

    public string UserName { get; set; } = null!;

    public string Password { get; set; } = null!;

    public bool IsAdmin { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public int? SystemUserCreated { get; set; }

    // --- New RBAC fields ---

    /// <summary>
    /// Can manage other super admins
    /// </summary>
    public bool IsMasterAdmin { get; set; }

    public string? FullName { get; set; }

    public DateTime? LastLoginAt { get; set; }
}