// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class AccountsViewCombo
{
    public string? AccountName { get; set; }

    public Guid AccountID { get; set; }
}