// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class AccountView
{
    public Guid AccountID { get; set; }

    public string? AccountName { get; set; }

    public string? AccountDescription { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }
}