// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Action
{
    public Guid ActionID { get; set; }

    public Guid? BatchID { get; set; }

    public int? ActionType { get; set; }

    public DateTime? ActionDate { get; set; }

    public Guid? UserID { get; set; }

    public Guid? TransactionID { get; set; }

    public Guid? RegisterID { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public decimal? ActionSum { get; set; }

    public string? Description { get; set; }

    public string? Info { get; set; }
}