// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ActivityView
{
    public Guid? ActivityID { get; set; }

    public string? TableNameDesc { get; set; }

    public string? Username { get; set; }

    public string? Status { get; set; }

    public string? Description { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? RowID { get; set; }
}