// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class AllTransactionForSupplier
{
    public Guid IDc { get; set; }

    public Guid? SupplierNo { get; set; }

    public int Type { get; set; }

    public DateTime? Datet { get; set; }

    public string? Num { get; set; }

    public decimal? Amount { get; set; }

    public Guid? StoreNo { get; set; }

    public short? Status { get; set; }
}