// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Alteration
{
    public int AlterationID { get; set; }

    public string? AlterationNo { get; set; }

    public Guid? TransactionID { get; set; }

    public Guid? TransactionEntryID { get; set; }

    /// <summary>
    /// 1=Open
    /// 2= Working Now
    /// 3= Ready 
    /// 4 =Done
    /// 
    /// </summary>
    public short? AlterationStatus { get; set; }

    public int? AlterationType { get; set; }

    public string? Note { get; set; }

    public DateTime? ExpectedDate { get; set; }

    public int? ConveyorID { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}