// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ApexSQL_SC_PoliciesTable
{
    public bool? CheckOutBeforeEdit { get; set; }

    public int? DatabaseID { get; set; }

    public int ID { get; set; }

    public bool? LockBeforeEdit { get; set; }

    public bool? LogChanges { get; set; }
}