// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class BatchView
{
    public Guid BatchID { get; set; }

    public string? BatchNumber { get; set; }

    public Guid? CashierID { get; set; }

    public Guid? StoreID { get; set; }

    public int? BatchStatus { get; set; }

    public Guid? RegisterID { get; set; }

    public DateTime? OpeningDateTime { get; set; }

    public DateTime? ClosingDateTime { get; set; }

    public decimal? OpeningAmount { get; set; }

    public decimal? ClosingAmount { get; set; }

    public int? OpenHunderdBills { get; set; }

    public int? OpenFiftyBills { get; set; }

    public int? OpenTwentyBills { get; set; }

    public int? OpenTenBills { get; set; }

    public int? OpenFiveBills { get; set; }

    public int? OpenSingels { get; set; }

    public int? OpenQuarter { get; set; }

    public int? OpenDimes { get; set; }

    public int? OpenNickels { get; set; }

    public int? OpenPennies { get; set; }

    public decimal? OpenOther { get; set; }

    public int? CloseHunderdBills { get; set; }

    public int? CloseFiftyBills { get; set; }

    public int? CloseTwentyBills { get; set; }

    public int? CloseTenBills { get; set; }

    public int? CloseFiveBills { get; set; }

    public int? CloseSingels { get; set; }

    public int? CloseQuarter { get; set; }

    public int? CloseDimes { get; set; }

    public int? CloseNickels { get; set; }

    public int? ClosePennies { get; set; }

    public decimal? CloseOther { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public string? BatchText { get; set; }
}