// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class BillWithStoreID
{
    public Guid BillID { get; set; }

    public string? BillNo { get; set; }

    public Guid? SupplierID { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Amount { get; set; }

    public decimal? AmountPay { get; set; }

    public DateTime? BillDate { get; set; }

    public DateTime? BillDue { get; set; }

    public Guid? PersonGet { get; set; }

    public string? Note { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public Guid? StoreID { get; set; }

    public short? ReceiveStatus { get; set; }

    public Guid? TermsID { get; set; }

    public decimal? EntrySum { get; set; }
}