// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ButtonSheetsView
{
    public Guid SheetID { get; set; }

    public string? SheetName { get; set; }

    public int Status { get; set; }

    public DateTime? DateModified { get; set; }

    public int Sort { get; set; }
}