// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CODView
{
    public string? CustomerNo { get; set; }

    public string Name { get; set; } = null!;

    public string? Address { get; set; }

    public string CityStateAndZip { get; set; } = null!;

    public string? Phone { get; set; }

    public DateTime? DateOfSale { get; set; }

    public decimal? CODAmount { get; set; }

    public decimal? AmountPaid { get; set; }
}