// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CompSetting
{
    public long CompSettingID { get; set; }

    public string CompName { get; set; } = null!;

    public Guid? CompStoreID { get; set; }

    public Guid? CompUserLogedID { get; set; }

    public DateTime? mpUserLogOnTime { get; set; }

    public DateTime? mpUserLogOffTime { get; set; }

    public string? CompPrinterPath { get; set; }

    public string? CompDBUpdatePath { get; set; }
}