// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CONSTRAINT_UNIQUE_script_view
{
    public string? indexName { get; set; }

    public string TableName { get; set; } = null!;

    public string? SCHEMA_NAME { get; set; }

    public string? CreateIndexScript { get; set; }
}