// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Conveyor
{
    public int ConveyorID { get; set; }

    public string Rack { get; set; } = null!;

    public int RowNo { get; set; }

    public short? Reserved { get; set; }

    public int? RackNo { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? WorkOrderID { get; set; }
}