// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CostByTransactionAndSupplier
{
    public Guid? TransactionID { get; set; }

    public decimal? SumCost { get; set; }

    public Guid? SupplierNo { get; set; }

    public decimal? Debit { get; set; }
}