// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Coupon1
{
    public Guid CouponID { get; set; }

    public decimal? DiscPrec { get; set; }

    public decimal? MinTotalSale { get; set; }

    public int? CouponType { get; set; }

    public bool? ExcludePhoneOrder { get; set; }

    public bool? IncludeDiscountItems { get; set; }

    public bool? IncludeCases { get; set; }

    public int? Status { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserModified { get; set; }

    public DateTime? DateModified { get; set; }
}