// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CouponCust
{
    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? CompanyName { get; set; }

    public string? CustomerNo { get; set; }

    public string? Street1 { get; set; }

    public string? Street2 { get; set; }

    public string? City { get; set; }

    public string? State { get; set; }

    public string? Zip { get; set; }

    public string? PhoneNumber1 { get; set; }

    public decimal? Amount { get; set; }

    public string? CouponNo { get; set; }

    public DateTime? ExpDate { get; set; }

    public DateTime? CouponIssueDate { get; set; }

    public Guid? CouponID { get; set; }

    public Guid? CustomerID { get; set; }

    public DateTime PurchaseWeek { get; set; }

    public int? Status { get; set; }

    public string? Notes { get; set; }
}