// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CouponUsed
{
    public decimal? Amount { get; set; }

    public Guid? CouponID { get; set; }

    public Guid CouponUsedID { get; set; }

    public DateTime? DateCreated { get; set; }

    public int? Status { get; set; }

    public Guid? TransactionID { get; set; }

    public DateTime? UsedDate { get; set; }

    public DateTime? DateModified { get; set; }

    public decimal? AmountAdd { get; set; }

    public Guid? TransactionEntryID { get; set; }
}