// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CoustomFiledsCombo
{
    public string? CustomFieldName { get; set; }

    public Guid CustomFieldID { get; set; }
}