// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Credit
{
    public Guid CreditID { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public int? Days { get; set; }

    public decimal? InterestRate { get; set; }

    public bool? CreditType { get; set; }

    public int? NetDue { get; set; }

    public int? DayInMonth { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public decimal? InterestRate2 { get; set; }

    public bool? CreditType2 { get; set; }
}