// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CRMCallsView
{
    public Guid? CRMCallID { get; set; }

    public Guid? CustomerID { get; set; }

    public DateTime? CallDate { get; set; }

    public string? Note { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public string? UserName { get; set; }

    public string Name { get; set; } = null!;

    public string? Address { get; set; }

    public string? Phone { get; set; }

    public string? Email { get; set; }

    public string CityStateAndZip { get; set; } = null!;

    public string? CustomerNo { get; set; }
}