// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class CustomerDetailsForPhoneOrderResult
    {
        public bool? LockAccount { get; set; }
        [Column("BalanceDoe", TypeName = "money")]
        public decimal? BalanceDoe { get; set; }
        [Column("Credit", TypeName = "money")]
        public decimal? Credit { get; set; }
        public DateTime? LastVisit { get; set; }
        [Column("LastAmount", TypeName = "money")]
        public decimal? LastAmount { get; set; }
        public DateTime? LastPayDate { get; set; }
        [Column("LastPayment", TypeName = "money")]
        public decimal LastPayment { get; set; }
        [StringLength(50)]
        public string? FoodStampCode { get; set; }
        [StringLength(500)]
        public string? CreditCardNO { get; set; }
        [StringLength(50)]
        public string? FoodStampNo { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? LastDateCleared { get; set; }
        [Column("Over120", TypeName = "money")]
        public decimal? Over120 { get; set; }
        [Column("Over30", TypeName = "money")]
        public decimal? Over30 { get; set; }
        [Column("Over60", TypeName = "money")]
        public decimal? Over60 { get; set; }
        [Column("Over90", TypeName = "money")]
        public decimal? Over90 { get; set; }
        public int? LockOutDays { get; set; }
        public int? RegularPaymentType { get; set; }
        public DateTime? CCExpDate { get; set; }
        [StringLength(2147483647)]
        public string? GroupName { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
    }
}
