// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomerTask
{
    public Guid TaskID { get; set; }

    public Guid? CustomerID { get; set; }

    public string? Description { get; set; }

    public short? TaskStatus { get; set; }

    public short? TaskType { get; set; }

    public DateTime? TaskDate { get; set; }

    public DateTime? ScheduleDate { get; set; }

    public string? ScheduleHour { get; set; }

    public string? Note { get; set; }

    public short? Priority { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}