// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomFieldValue
{
    public Guid CustomFieldValueID { get; set; }

    public Guid CustomFieldNo { get; set; }

    public Guid RowNo { get; set; }

    public string? FieldValue { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }
}