// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomerQtyAndAmount
{
    public decimal? TotalQty { get; set; }

    public decimal? TotalDebit { get; set; }

    public Guid? CustomerID { get; set; }

    public DateTime? DateCreated { get; set; }
}