// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomerSaleInfo
{
    public Guid CustomerID { get; set; }

    public int? Visit { get; set; }

    public DateTime? LastVisit { get; set; }

    public decimal? AverageAmount { get; set; }

    public decimal? TotalSpent { get; set; }

    public int? Last12MonthsTrans { get; set; }

    public int? Last90DaysTrans { get; set; }
}