// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomerViewBasic
{
    public Guid CustomerID { get; set; }

    public string? CustomerNo { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }

    public string Name { get; set; } = null!;

    public string? Address { get; set; }

    public string? Phone { get; set; }

    public string? CityStateAndZip { get; set; }

    public string? Email { get; set; }

    public string? HouseNo { get; set; }

    public string? StreetName { get; set; }

    public string? Zones { get; set; }

    public decimal? BalanceDue { get; set; }

    public Guid? DefaultStore { get; set; }

    public string? DefaultStoreName { get; set; }
}