// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomerLastTansactionView
{
    public long? Number { get; set; }

    public Guid TransactionID { get; set; }

    public Guid? CustomerID { get; set; }

    public string TransactionNo { get; set; } = null!;

    public decimal? Qty { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public DateTime? DateModified { get; set; }

    public decimal? Paid { get; set; }

    public decimal? Total { get; set; }

    public string? ID { get; set; }

    public int Status { get; set; }

    public string? Tender { get; set; }

    public decimal Tax { get; set; }
}