// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomField
{
    public Guid CustomFieldID { get; set; }

    public string? CustomFieldName { get; set; }

    public string? CustomFieldType { get; set; }

    public string? LinkToTable { get; set; }

    public short? SortOrder { get; set; }
}