// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomerItemFilterView
{
    public Guid? CustomerID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public string? SupplierName { get; set; }

    public string? Name { get; set; }

    public string? ManufacturerName { get; set; }
}