// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomersForNoTender
{
    public Guid CustomerId { get; set; }

    public Guid CustomersForNoTenderID { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public short? Status { get; set; }

    public int? TenderId { get; set; }

    public Guid? UserCreated { get; set; }

    public Guid? UserModified { get; set; }
}