// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomerBalance
{
    public string? Name { get; set; }

    public decimal? Till30 { get; set; }

    public decimal? From30 { get; set; }

    public decimal? From60 { get; set; }

    public decimal? From90 { get; set; }

    public decimal? From120 { get; set; }
}