// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class CustomerNotesPO
{
    public DateTime? DateModified { get; set; }

    public Guid NoteID { get; set; }

    public Guid CustomerID { get; set; }

    public int TypeOfNote { get; set; }

    public string? NoteValue { get; set; }

    public short? Status { get; set; }
}