// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DailyHourSale
{
    public string? Date { get; set; }

    public Guid? StoreID { get; set; }

    public string? StoreName { get; set; }

    public decimal? Debit { get; set; }

    public decimal? Credit { get; set; }

    public decimal? Balance { get; set; }

    public int? CountTransaction { get; set; }

    public int? Registers { get; set; }

    public double? SalePrec { get; set; }

    public int? Customers { get; set; }

    public int? TransactionWithCustomer { get; set; }

    public double? CustomerPrec { get; set; }

    public decimal? CustomerDebit { get; set; }

    public decimal? Items { get; set; }

    public DateTime? OrderCol { get; set; }
}