// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DamageItem
{
    public Guid DamageItemID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Qty { get; set; }

    public int? DamageStatus { get; set; }

    public Guid? TransactionEntryID { get; set; }

    public Guid? ReturnEntryID { get; set; }

    public DateTime? Date { get; set; }

    public int? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}