// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DamageItemView
{
    public Guid DamageItemID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Qty { get; set; }

    public int? DamageStatus { get; set; }

    public Guid? TransactionEntryID { get; set; }

    public Guid? ReturnEntryID { get; set; }

    public DateTime? Date { get; set; }

    public int? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public Guid TransactionID { get; set; }

    public string TransactionNo { get; set; } = null!;

    public string? Name { get; set; }

    public string? ModalNumber { get; set; }

    public string? BarcodeNumber { get; set; }

    public string? SupplierName { get; set; }

    public Guid? SupplierID { get; set; }
}