// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DatabaseVersionHistory
{
    public int VersionNumber { get; set; }

    public DateTime VersionDate { get; set; }

    public string ChangePackage { get; set; } = null!;
}