// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DateScope
{
    public int ScopeID { get; set; }

    public string? Description { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public int? Status { get; set; }

    public int? SortOrder { get; set; }

    public Guid? UserID { get; set; }
}