// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DBUpdate
{
    public double Version { get; set; }

    public string? UpdateText { get; set; }

    public short? Sort { get; set; }

    public string? Comment { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public string? UserCreated { get; set; }
}