// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DeleteRecorde
{
    public string? TableName { get; set; }

    public int? Status { get; set; }

    public string? TableID { get; set; }

    public DateTime? DateModified { get; set; }

    public bool? IsGuid { get; set; }

    public string? FieldName { get; set; }
}