// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DeliveryDetail
{
    public int? DeliveryID { get; set; }

    public Guid DeliveryDetailID { get; set; }

    public Guid? ShippingAdress { get; set; }

    public int? Status { get; set; }

    public string? Note { get; set; }

    public int? OrderTypeID { get; set; }

    public Guid? TransactionID { get; set; }

    public Guid? CustomerID { get; set; }

    public DateTime? SentDate { get; set; }

    public Guid? RegID { get; set; }

    public Guid? CashierID { get; set; }

    public string? Shift { get; set; }

    public int? Box { get; set; }

    public int? Cases { get; set; }

    public Guid? Driver { get; set; }

    public DateTime? BeDeliverdDate { get; set; }

    public DateTime? DeliverdDate { get; set; }

    public bool? Freezer { get; set; }

    public DateTime? DateModified { get; set; }

    public int? BatchID { get; set; }

    public DateTime? ReturnedDate { get; set; }

    public DateTime? ShippedDate { get; set; }

    public string? TempAddress { get; set; }

    public string? TempCityStateZip { get; set; }

    public string? TempName { get; set; }

    public int? TotalScan { get; set; }

    public string? Number { get; set; }

    public Guid? PackedBy { get; set; }

    public DateTime? PackedDate { get; set; }

    public int? SortOrder { get; set; }

    public string? StatusType { get; set; }

    public string? PaidString { get; set; }

    public bool ShipSent { get; set; }
}