// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DepartmentStore
{
    public Guid DepartmentStoreID { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public Guid? ParentDepartmentID { get; set; }

    public Guid? StoreID { get; set; }

    public int? KeyNumber { get; set; }

    public decimal? DefaultMarkup { get; set; }

    public decimal? DefaultMarkupA { get; set; }

    public decimal? DefaultMarkupB { get; set; }

    public decimal? DefaultMarkupC { get; set; }

    public decimal? DefaultMarkupD { get; set; }

    public int RoundUp { get; set; }

    public int? RoundUpA { get; set; }

    public int? RoundUpB { get; set; }

    public int? RoundUpC { get; set; }

    public int? RoundUpD { get; set; }

    public decimal? RoundValue { get; set; }

    public decimal? RoundValueA { get; set; }

    public decimal? RoundValueB { get; set; }

    public decimal? RoundValueC { get; set; }

    public decimal? RoundValueD { get; set; }

    public int? DefaultCogsAccount { get; set; }

    public int? DefaultIncomeAccount { get; set; }

    public Guid? DefaultTaxNo { get; set; }

    public bool? IsDefaultTaxInclude { get; set; }

    public bool? IsDefaultFoodStampable { get; set; }

    public int? DefaultProfitCalculation { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public bool? IsDefaultDiscountable { get; set; }

    public string? DepartmentNo { get; set; }

    public Guid? DiscountID { get; set; }

    public bool? UseImageCard { get; set; }

    public virtual ICollection<ItemStore> ItemStores { get; set; } = new List<ItemStore>();
}