// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DiscountDepartmentPO
{
    public Guid? DepartmentID { get; set; }

    public Guid? DiscountID { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid DiscountDepartmentID { get; set; }

    public short? Status { get; set; }
}