// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DiscountsView
{
    public Guid DiscountID { get; set; }

    public string? Name { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public decimal? PercentsDiscount { get; set; }

    public decimal? AmountDiscount { get; set; }

    public decimal? MinTotalSale { get; set; }

    public string? UPCDiscount { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public bool? ClearBalance { get; set; }

    public int? ClearDays { get; set; }

    public bool? ReqPaswrd { get; set; }

    public decimal? DiscountForCC { get; set; }

    public bool? DiscountItems { get; set; }

    public decimal? PercentsDiscountWithCC { get; set; }

    public bool? SalesItem { get; set; }

    public decimal? MinTotalSale2 { get; set; }

    public decimal? PercentsDiscount2 { get; set; }

    public decimal? AmountDiscount2 { get; set; }

    public decimal? MinTotalSale3 { get; set; }

    public decimal? PercentsDiscount3 { get; set; }

    public decimal? AmountDiscount3 { get; set; }

    public int? DiscountType { get; set; }

    public bool IncludeGiftCard { get; set; }

    public int? DiscountItem { get; set; }

    public int? DiscountDepartment { get; set; }

    public int? DiscountBrand { get; set; }

    public int? DiscountStore { get; set; }

    public int? BogoQty { get; set; }

    public decimal? BogoAmount { get; set; }

    public int? BogoType { get; set; }

    public bool? SelectedItem { get; set; }

    public decimal MaxAmount { get; set; }

    public bool? AutoAssign { get; set; }
}