// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DiscountBrandPO
{
    public Guid? DiscountID { get; set; }

    public Guid DiscountBrandID { get; set; }

    public DateTime? DateModified { get; set; }

    public short? Status { get; set; }

    public string BrandID { get; set; } = null!;
}