// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class DiscountToLink
{
    public Guid ID { get; set; }

    public Guid? LinkID { get; set; }

    public int? Status { get; set; }

    public Guid? DiscountID { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserModified { get; set; }

    public DateTime? DateModified { get; set; }
}