// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class EizerLemuzin
{
    public string? CustomerGroupName { get; set; }

    public string CustName { get; set; } = null!;

    public Guid CustomerID { get; set; }

    public string? CustomerNo { get; set; }

    public string? Street1 { get; set; }

    public string? PhoneNumber1 { get; set; }

    public string? CityStateAndZip { get; set; }
}