// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class EmailTemplate
{
    public Guid EmailTemplateID { get; set; }

    public string? EmailFrom { get; set; }

    public string? Subject { get; set; }

    public string? Body { get; set; }

    public byte[]? EmailContent { get; set; }

    public int? Category { get; set; }

    public string? FileName { get; set; }

    public short? Status { get; set; }
}