// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class emailBackUp
{
    public Guid EmailID { get; set; }

    public string? Subject { get; set; }

    public string? Body { get; set; }

    public string? From { get; set; }

    public string? FromAddress { get; set; }

    public string? To { get; set; }

    public string? ToAddress { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public int? MailType { get; set; }

    public short? MailStatus { get; set; }

    public string? EmailUid { get; set; }

    public byte[]? Attachment { get; set; }

    public string? FileName { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public string? ErrorMessage { get; set; }
}