// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class emp
{
    public int EMPNO { get; set; }

    public string? ENAME { get; set; }

    public string? JOB { get; set; }

    public int? MGR { get; set; }

    public DateTime? HIREDATE { get; set; }

    public double? SAL { get; set; }

    public double? COMM { get; set; }

    public int? DEPTNO { get; set; }
}