// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class EncDatum
{
    public string? EncData { get; set; }

    public string? Type { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? StoreID { get; set; }

    public int ID { get; set; }

    public byte? Status { get; set; }
}