// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ExceptionLog
{
    public int LogID { get; set; }

    public string? ErrorSource { get; set; }

    public string? ErrorMessage { get; set; }

    public string? AppID { get; set; }

    public int? ErrorNo { get; set; }

    public DateTime? AddDate { get; set; }

    public string? AddUser { get; set; }
}