// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ExtraCharge
{
    public Guid ExtraChargeID { get; set; }

    public string? ExtraChargeName { get; set; }

    public string? ExtraChargeDescription { get; set; }

    public int ExtraChargeType { get; set; }

    public decimal? ExtraChargeQty { get; set; }

    public bool? IsExtraChargeIncluded { get; set; }

    public Guid? ExtraChargeAccount { get; set; }

    public Guid ItemStoreNo { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }
}