// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class File
{
    public Guid FileID { get; set; }

    public byte[]? File1 { get; set; }
}