// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class FixBalanceView
{
    public Guid CustomerID { get; set; }

    public decimal Debit0 { get; set; }

    public decimal Debit30 { get; set; }

    public decimal Debit60 { get; set; }

    public decimal Debit90 { get; set; }

    public decimal Debit120 { get; set; }

    public decimal Balance { get; set; }

    public decimal Credit { get; set; }
}