// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class FullItemNamesWithAlias
{
    public string? ItemStoreID { get; set; }

    public int? ItemType { get; set; }

    public string? FullName { get; set; }

    public string? BarcodeNumber { get; set; }

    public string? ModalNumber { get; set; }

    public Guid StoreNo { get; set; }

    public short? MainStatus { get; set; }

    public short? StoreStatus { get; set; }
}