// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class FullSaleQtyByStoreView
{
    public string? Name { get; set; }

    public string? StoreName { get; set; }

    public decimal Month5 { get; set; }

    public decimal Month4 { get; set; }

    public decimal Month3 { get; set; }

    public decimal Month2 { get; set; }

    public decimal Month1 { get; set; }

    public decimal last7days { get; set; }

    public decimal YTD { get; set; }

    public decimal MtdLastYr { get; set; }

    public decimal MTD { get; set; }

    public decimal YtdLastYr { get; set; }

    public decimal? OnHand { get; set; }

    public decimal OnOrder { get; set; }

    public Guid ItemID { get; set; }

    public Guid ItemStoreID { get; set; }

    public Guid StoreNo { get; set; }
}