// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class GenOrderViewHH
{
    public string? ItemName { get; set; }

    public string? StyleNo { get; set; }

    public string? SupplierName { get; set; }

    public string? BarcodeNumber { get; set; }

    public bool? ToOrder { get; set; }

    public decimal? QtyOrdered { get; set; }

    public int? UOMType { get; set; }

    public Guid? SupplierNo { get; set; }

    public Guid GenPurchaseOrderID { get; set; }

    public short? Status { get; set; }

    public Guid? ItemNo { get; set; }

    public DateTime? DateModified { get; set; }

    public int? SortOrder { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? StoreID { get; set; }
}