// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class GenPurchaseOrder
{
    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid GenPurchaseOrderID { get; set; }

    public Guid? ItemNo { get; set; }

    public decimal? ReorderQty { get; set; }

    public short? Status { get; set; }

    public Guid? Supplier { get; set; }

    public bool? ToOrder { get; set; }

    public int? UOMType { get; set; }

    public int? SortOrder { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? UserModified { get; set; }
}