// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class GetAllPoEntrybySupplierResult
    {
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? SupName { get; set; }
        [StringLength(50)]
        public string? PoNo { get; set; }
        [Column("QtyOrdered", TypeName = "decimal(19,3)")]
        public decimal? QtyOrdered { get; set; }
        [Column("PricePerUnit", TypeName = "money")]
        public decimal? PricePerUnit { get; set; }
        [StringLength(50)]
        public string? WebSite { get; set; }
    }
}
