// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class GetSupplierByNameResult
    {
        public Guid SupplierID { get; set; }
        [StringLength(50)]
        public string? SupplierNo { get; set; }
        [StringLength(50)]
        public string? Name { get; set; }
        public Guid? DefaultCredit { get; set; }
        [StringLength(50)]
        public string? WebSite { get; set; }
        [StringLength(50)]
        public string? EmailAddress { get; set; }
        public Guid? MainAddress { get; set; }
        [StringLength(50)]
        public string ContactName { get; set; } = default!;
        public Guid? BarterID { get; set; }
        public Guid? WarehouseID { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(50)]
        public string? AccountNo { get; set; }
        [StringLength(50)]
        public string? Note { get; set; }
        [StringLength(50)]
        public string Address1 { get; set; } = default!;
        [StringLength(50)]
        public string Address2 { get; set; } = default!;
        [StringLength(20)]
        public string City { get; set; } = default!;
        [StringLength(50)]
        public string State { get; set; } = default!;
        [StringLength(15)]
        public string Zip { get; set; } = default!;
        [StringLength(20)]
        public string PhoneNumber1 { get; set; } = default!;
        [StringLength(20)]
        public string? Ext1 { get; set; }
        [StringLength(20)]
        public string PhoneNumber2 { get; set; } = default!;
        [StringLength(20)]
        public string PhoneNumber3 { get; set; } = default!;
        [Column("MinMarkup", TypeName = "decimal(18,4)")]
        public decimal MinMarkup { get; set; }
        public Guid? BuyerID { get; set; }
        [Column("ListPrice", TypeName = "decimal(18,4)")]
        public decimal? ListPrice { get; set; }
        public Guid? Department { get; set; }
        public short? Import { get; set; }
        [StringLength(500)]
        public string? SupplierNote { get; set; }
    }
}
