// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class GetUsersPPCResult
    {
        public Guid PPCompID { get; set; }
        [StringLength(50)]
        public string? PPCName { get; set; }
        [StringLength(50)]
        public string? InvoiceNum { get; set; }
        [StringLength(50)]
        public string? ReturnNum { get; set; }
        [StringLength(50)]
        public string? PaymentNum { get; set; }
        [StringLength(50)]
        public string? SaleOrderNum { get; set; }
        [StringLength(50)]
        public string? ReceiveNum { get; set; }
        [StringLength(50)]
        public string? ReturnSupplierNum { get; set; }
        [StringLength(50)]
        public string? PaymentSupplierNum { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
