// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class GiftRegistryView
{
    public DateTime? EventDate { get; set; }

    public string? EventType { get; set; }

    public Guid? CustomerID { get; set; }

    public Guid GiftRegisteryID { get; set; }

    public string Name { get; set; } = null!;

    public string? RegNo { get; set; }

    public string? Event { get; set; }

    public string? Address { get; set; }
}