// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class GiftView
{
    public Guid GiftID { get; set; }

    public string? GiftNumber { get; set; }

    public Guid? CustomerID { get; set; }

    public decimal? Amount { get; set; }

    public int? GiftType { get; set; }

    public DateTime? GiftDate { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public string CustomerName { get; set; } = null!;

    public string? CustomerNo { get; set; }
}