// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class GlobalChangeEntry
{
    public Guid GlobalChangeID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public Guid ItemNo { get; set; }

    public Guid? StoreNo { get; set; }

    public Guid? DepartmentID { get; set; }

    public decimal? Cost { get; set; }

    public decimal? ListPrice { get; set; }

    public decimal? Price { get; set; }

    public decimal? PriceA { get; set; }

    public decimal? PriceB { get; set; }

    public decimal? PriceC { get; set; }

    public decimal? PriceD { get; set; }

    public Guid? ExtraCharge1 { get; set; }

    public Guid? ExtraCharge2 { get; set; }

    public Guid? ExtraCharge3 { get; set; }

    public Guid? MainSupplierID { get; set; }

    public string? BinLocation { get; set; }

    public decimal? AVGCost { get; set; }

    public int? SaleType { get; set; }

    public decimal? SalePrice { get; set; }

    public DateTime? SaleStartDate { get; set; }

    public DateTime? SaleEndDate { get; set; }

    public int? SaleMin { get; set; }

    public int? SaleMax { get; set; }

    public decimal? MinForSale { get; set; }

    public int? SpecialBuy { get; set; }

    public decimal? SpecialPrice { get; set; }

    public DateTime? SpecialBuyFromDate { get; set; }

    public DateTime? SpecialBuyToDate { get; set; }

    public Guid? MixAndMatchID { get; set; }

    public bool? AssignDate { get; set; }
}