// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class GridFieldsSQL
{
    public int ID { get; set; }

    public string? ViewName { get; set; }

    public string? SQLQuery { get; set; }
}