// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class GridColumnsNotVisible
{
    public int ID { get; set; }

    public int? GridNumber { get; set; }

    public string? FieldName { get; set; }
}