// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class HistoryView
{
    public string TransactionNo { get; set; } = null!;

    public int TransactionType { get; set; }

    public Guid? TransactionID { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public DateTime? SaleTime { get; set; }

    public decimal? Qty { get; set; }

    public decimal? UOMQty { get; set; }

    public decimal? Price { get; set; }

    public decimal? ExtPrice { get; set; }

    public Guid? ItemStoreID { get; set; }

    public Guid ItemID { get; set; }

    public Guid? StoreID { get; set; }

    public string? StoreName { get; set; }

    public Guid? CustomerID { get; set; }

    public string? Type { get; set; }

    public decimal? QtyCase { get; set; }

    public string? Customer_Name { get; set; }

    public string? CustomerNo { get; set; }

    public decimal? TotalAfterDiscount { get; set; }
}