// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ImportItemTable
{
    public decimal? AvrgCost { get; set; }

    public int? Class { get; set; }

    public int? DealQuantity { get; set; }

    public int? Department { get; set; }

    public int? Division { get; set; }

    public int ID { get; set; }

    public string? ItemName { get; set; }

    public string? ItemStatus { get; set; }

    public int? Location { get; set; }

    public int? PriceMethod { get; set; }

    public decimal? RetailPrice { get; set; }

    public string? SKU { get; set; }

    public decimal? SpecialPrice { get; set; }

    public int? SubClass { get; set; }

    public string? TaxRate { get; set; }

    public decimal? UnitCost { get; set; }

    public string? UPC1 { get; set; }

    public string? UPC2 { get; set; }

    public string? UPC3 { get; set; }

    public string? UPC4 { get; set; }

    public string? UPC5 { get; set; }

    public string? UPC6 { get; set; }

    public string? UPC7 { get; set; }

    public string? UPC8 { get; set; }
}