// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemSerialEntry
{
    public Guid ItemSerialEntryID { get; set; }

    public Guid? TransEntryID { get; set; }

    public string? SerialNumber1 { get; set; }

    public string? SerialNumber2 { get; set; }

    public string? SerialNumber3 { get; set; }

    public string? SerialNumber4 { get; set; }

    public string? SerialNumber5 { get; set; }
}