// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemSmartSerch
{
    public Guid ItemID { get; set; }

    public string? F1 { get; set; }

    public string? F2 { get; set; }

    public string? F3 { get; set; }

    public string? F4 { get; set; }

    public string? F5 { get; set; }

    public string? F6 { get; set; }

    public string? F7 { get; set; }

    public string? F8 { get; set; }

    public string? F9 { get; set; }

    public string? F10 { get; set; }
}