// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemListForSupplierView
{
    public short? Status { get; set; }

    public int? ItemType { get; set; }

    public Guid StoreNo { get; set; }

    public Guid? SupplierNo { get; set; }

    public Guid? LinkNo { get; set; }

    public string? Name { get; set; }

    public Guid ItemID { get; set; }

    public string? UPC { get; set; }

    public int? Average_Delivery_Delay { get; set; }

    public decimal Cost { get; set; }

    public int? Min_Qty { get; set; }

    public bool? Case_Only { get; set; }

    public bool Main_Supplier { get; set; }
}