// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemToGroup
{
    public Guid ItemToGroupID { get; set; }

    public Guid? ItemGroupID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }

    public virtual ItemGroup? ItemGroup { get; set; }

    public virtual ItemStore? ItemStore { get; set; }
}