// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemsForSale
{
    public Guid ItemStoreID { get; set; }

    public decimal? SalePrice { get; set; }

    public decimal Price { get; set; }

    public decimal? RealPrice { get; set; }
}