// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemNotExistsOtherStore
{
    public string? BarcodeNumber { get; set; }

    public string? FromDb { get; set; }

    public string? Todb { get; set; }

    public decimal? Qty { get; set; }

    public Guid? PhoneOrderID { get; set; }

    public Guid? ItemStoreID { get; set; }
}