// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemExistsSale
{
    public DateTime? EndSaleTime { get; set; }

    public Guid? ItemStoreID { get; set; }
}