// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemsForWeb
{
    public string? sku { get; set; }

    public string _store { get; set; } = null!;

    public string _attribute_set { get; set; } = null!;

    public string _type { get; set; } = null!;

    public string? _category { get; set; }

    public string _root_category { get; set; } = null!;

    public string _product_websites { get; set; } = null!;

    public decimal? cost { get; set; }

    public DateTime? created_at { get; set; }

    public string? description { get; set; }

    public string? manufacturer { get; set; }

    public string? name { get; set; }

    public decimal price { get; set; }

    public string? short_description { get; set; }

    public string status { get; set; } = null!;

    public string tax_class_id { get; set; } = null!;

    public string visibility { get; set; } = null!;

    public string? weight { get; set; }

    public decimal? qty { get; set; }

    public string min_qty { get; set; } = null!;

    public string use_config_min_qty { get; set; } = null!;

    public string is_qty_decimal { get; set; } = null!;

    public string backorders { get; set; } = null!;

    public string use_config_backorders { get; set; } = null!;

    public string min_sale_qty { get; set; } = null!;

    public string use_config_min_sale_qty { get; set; } = null!;

    public string max_sale_qty { get; set; } = null!;

    public string use_config_max_sale_qty { get; set; } = null!;

    public string is_in_stock { get; set; } = null!;

    public string notify_stock_qty { get; set; } = null!;

    public string use_config_notify_stock_qty { get; set; } = null!;

    public string manage_stock { get; set; } = null!;

    public string use_config_manage_stock { get; set; } = null!;

    public string stock_status_changed_auto { get; set; } = null!;

    public string use_config_qty_increments { get; set; } = null!;

    public string qty_incrementsuse_config_enable_qty_inc { get; set; } = null!;

    public string enable_qty_increments { get; set; } = null!;

    public string is_decimal_divided { get; set; } = null!;

    public string _media_attribute_id { get; set; } = null!;

    public string? _media_lable { get; set; }

    public string? _media_image { get; set; }

    public string? image { get; set; }

    public string? small_image { get; set; }

    public string? thumbnail { get; set; }
}