// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemMainView
{
    public Guid ItemID { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? ModalNumber { get; set; }

    public decimal? Quantization { get; set; }

    public Guid? Unit { get; set; }

    public Guid? ParentID { get; set; }

    public Guid? MatrixTableNo { get; set; }

    public Guid? LinkNo { get; set; }

    public string? Matrix1 { get; set; }

    public string? Matrix2 { get; set; }

    public string? Matrix3 { get; set; }

    public string? Matrix4 { get; set; }

    public string? Matrix5 { get; set; }

    public string? Matrix6 { get; set; }

    public string? BarcodeNumber { get; set; }

    public string? CaseBarcodeNumber { get; set; }

    public int? CaseQty { get; set; }

    public string? CaseDescription { get; set; }

    public int? BarcodeType { get; set; }

    public int? ItemType { get; set; }

    public byte[]? ItemPicture { get; set; }

    public string? PicturePath { get; set; }

    public byte[]? ItemPicture2 { get; set; }

    public string? PicturePath2 { get; set; }

    public byte[]? ItemPicture3 { get; set; }

    public string? PicturePath3 { get; set; }

    public bool? IsTemplate { get; set; }

    public bool? IsSerial { get; set; }

    public Guid? ManufacturerID { get; set; }

    public string? ManufacturerPartNo { get; set; }

    public bool? PriceByCase { get; set; }

    public bool? CostByCase { get; set; }

    public string? Size { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public string? ExtraInfo { get; set; }

    public string? ExtraInfo2 { get; set; }

    public decimal? Units { get; set; }

    public int? Meaasure { get; set; }

    public string? CaseBarCode { get; set; }

    public string? CustomerCode { get; set; }

    public string? NoScanMsg { get; set; }

    public string? StyleNo { get; set; }

    public int? CustomInteger1 { get; set; }

    public Guid? SeasonID { get; set; }

    public Guid? extname { get; set; }

    public Guid? CustomField1 { get; set; }

    public Guid? CustomField2 { get; set; }

    public Guid? CustomField3 { get; set; }

    public Guid? CustomField4 { get; set; }

    public Guid? CustomField5 { get; set; }

    public Guid? CustomField6 { get; set; }

    public Guid? CustomField7 { get; set; }

    public Guid? CustomField8 { get; set; }

    public Guid? CustomField9 { get; set; }

    public Guid? CustomField10 { get; set; }

    public int? OctopusItemId { get; set; }

    public bool? IsDeletedOctopus { get; set; }

    public int? AddToApp { get; set; }
}