// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class itemstoreLog
{
    public Guid ItemStoreID { get; set; }

    public Guid ItemNo { get; set; }

    public Guid? StoreNo { get; set; }

    public Guid? DepartmentID { get; set; }

    public bool? IsDiscount { get; set; }

    public bool? IsTaxable { get; set; }

    public Guid? TaxID { get; set; }

    public bool? IsFoodStampable { get; set; }

    public bool? IsWIC { get; set; }

    public decimal? Cost { get; set; }

    public decimal? ListPrice { get; set; }

    public decimal? Price { get; set; }

    public decimal? PriceA { get; set; }

    public decimal? PriceB { get; set; }

    public decimal? PriceC { get; set; }

    public decimal? PriceD { get; set; }

    public Guid? ExtraCharge1 { get; set; }

    public Guid? ExtraCharge2 { get; set; }

    public Guid? ExtraCharge3 { get; set; }

    public int? CogsAccount { get; set; }

    public int? IncomeAccount { get; set; }

    public int ProfitCalculation { get; set; }

    public decimal? CommissionQty { get; set; }

    public int CommissionType { get; set; }

    public int? PrefSaleBy { get; set; }

    public int? PrefOrderBy { get; set; }

    public Guid? MainSupplierID { get; set; }

    public decimal? OnOrder { get; set; }

    public decimal? OnTransferOrder { get; set; }

    public decimal? OnHand { get; set; }

    public decimal? ReorderPoint { get; set; }

    public decimal? RestockLevel { get; set; }

    public string? BinLocation { get; set; }

    public decimal? OnWorkOrder { get; set; }

    public int? DaysForReturn { get; set; }

    public decimal? AVGCost { get; set; }

    public int? SaleType { get; set; }

    public decimal? SalePrice { get; set; }

    public DateTime? SaleStartDate { get; set; }

    public DateTime? SaleEndDate { get; set; }

    public int? SaleMin { get; set; }

    public int? SaleMax { get; set; }

    public decimal? MinForSale { get; set; }

    public int? SpecialBuy { get; set; }

    public decimal? SpecialPrice { get; set; }

    public DateTime? SpecialBuyFromDate { get; set; }

    public DateTime? SpecialBuyToDate { get; set; }

    public Guid? MixAndMatchID { get; set; }

    public bool? AssignDate { get; set; }

    public short? Status { get; set; }

    public decimal? MTDQty { get; set; }

    public decimal? MTDDollar { get; set; }

    public decimal? PTDQty { get; set; }

    public decimal? PTDDollar { get; set; }

    public decimal? YTDQty { get; set; }

    public decimal? YTDDollar { get; set; }

    public decimal? MTDReturnQty { get; set; }

    public decimal? PTDReturnQty { get; set; }

    public decimal? YTDReturnQty { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public DateTime? TDDate { get; set; }

    public DateTime? TDReturnDate { get; set; }

    public decimal? NewPrice { get; set; }

    public DateTime? NewPriceDate { get; set; }

    public bool? SpecialsMemberOnly { get; set; }

    public decimal? CasePrice { get; set; }

    public decimal? CaseSpecial { get; set; }

    public decimal? PkgPrice { get; set; }

    public int? PkgQty { get; set; }

    public bool? IsCaseDiscount { get; set; }

    public bool? IsPkgDiscount { get; set; }

    public decimal? Tare { get; set; }

    public decimal? RegCost { get; set; }

    public Guid? LoyaltyGroupID { get; set; }

    public DateTime? LoyaltyGroupFromDate { get; set; }

    public DateTime? LoyaltyGroupToDate { get; set; }

    public string? VoidReason { get; set; }

    public int? LastCount { get; set; }

    public DateTime? CountDate { get; set; }

    public decimal? CountOnHand { get; set; }

    public decimal? RegSalePrice { get; set; }

    public DateTime? LastSoldDate { get; set; }

    public DateTime? LastReceivedDate { get; set; }

    public int? LastReceivedQty { get; set; }

    public decimal? SpecialCost { get; set; }

    public decimal? NetCost { get; set; }

    public decimal? EstimatedCost { get; set; }

    public DateTime? datecreatedlog { get; set; }

    public int? step { get; set; }

    public Guid? MainSupplierIDValue { get; set; }
}