// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Items_Log
{
    public string? ItemID { get; set; }

    public DateTime DateModified { get; set; }
}