// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemsImport
{
    public string? AISLE { get; set; }

    public string? BY_WEIGHT { get; set; }

    public string? BYCASE { get; set; }

    public string? CHESED { get; set; }

    public string? CODE { get; set; }

    public string? COMPANY { get; set; }

    public string? COST { get; set; }

    public string? COST_CASE { get; set; }

    public string? COUPON { get; set; }

    public string? CSCODE { get; set; }

    public string? D_MTD { get; set; }

    public string? D_YTD { get; set; }

    public string? DEPOSIT { get; set; }

    public string? DEPT { get; set; }

    public string? DESC { get; set; }

    public string? DESC2 { get; set; }

    public string? DISCOUNT { get; set; }

    public string? FOODSTAMP { get; set; }

    public string? HDESC { get; set; }

    public string? IMIN { get; set; }

    public string? LASTAMT { get; set; }

    public string? LASTCH { get; set; }

    public string? LIMIT { get; set; }

    public string? LIST { get; set; }

    public string? MARGIN { get; set; }

    public string? MEM_MONTH { get; set; }

    public string? MEMBER { get; set; }

    public string? MIN_PRICE { get; set; }

    public string? MIN_QTY { get; set; }

    public string? NAME { get; set; }

    public string? NAME2 { get; set; }

    public string? ONHAND { get; set; }

    public string? PR_CASE { get; set; }

    public string? PRICE { get; set; }

    public string? Q_MTD { get; set; }

    public string? Q_YTD { get; set; }

    public string? QPRICE { get; set; }

    public string? QTY { get; set; }

    public string? RUSE { get; set; }

    public string? SP_ACT { get; set; }

    public string? SP_CASE { get; set; }

    public string? SP_EDATE { get; set; }

    public string? SP_LIMIT { get; set; }

    public string? SP_MIN { get; set; }

    public string? SP_PRICE { get; set; }

    public string? SP_QTY { get; set; }

    public string? SP_SDATE { get; set; }

    public string? STARTDATE { get; set; }

    public string? TAG { get; set; }

    public string? TAXABLE { get; set; }

    public string? UN_CASE { get; set; }

    public string? UNIT { get; set; }

    public string? VENDOR { get; set; }

    public string? VNUMBER { get; set; }

    public string? WIC { get; set; }
}