// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemsRepFilter
{
    public Guid? ItemStoreID { get; set; }

    public Guid? ItemNo { get; set; }

    public int? ItemGroupID { get; set; }

    public Guid? SupplierNo { get; set; }

    public bool? IsDiscount { get; set; }

    public bool? IsTaxable { get; set; }

    public bool? IsFoodStampable { get; set; }

    public bool? IsWIC { get; set; }

    public int? ItemType { get; set; }

    public Guid? DepartmentID { get; set; }

    public Guid? ManufacturerID { get; set; }

    public Guid? LinkNo { get; set; }
}