// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemQtyAvg
{
    public Guid? itemid { get; set; }

    public int? WeekB { get; set; }

    public int? MonthB { get; set; }

    public int? YearB { get; set; }

    public decimal? TotalQty { get; set; }
}