// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemsForApi
{
    public Guid ItemID { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public string? ModelNumber { get; set; }

    public string? UPC { get; set; }

    public string ItemType { get; set; } = null!;

    public bool IsTaxable { get; set; }

    public bool? IsDiscount { get; set; }

    public bool? IsFoodStampable { get; set; }

    public bool IsWIC { get; set; }

    public decimal? Cs_Cost { get; set; }

    public decimal? Pc_Cost { get; set; }

    public decimal Price { get; set; }

    public int? CaseQty { get; set; }

    public string? StyleNo { get; set; }

    public string? CaseUPC { get; set; }

    public decimal OnHand { get; set; }

    public string? BinLocation { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime LastDateModified { get; set; }

    public string? Department { get; set; }

    public string? Matrix1 { get; set; }

    public string? Matrix2 { get; set; }

    public string? Matrix3 { get; set; }

    public string? Supplier_Item_Code { get; set; }

    public string? ManufacturerPartNo { get; set; }

    public string? SP_Price { get; set; }

    public string? SupplierName { get; set; }

    public DateTime? SP_From { get; set; }

    public DateTime? SP_To { get; set; }

    public string? Future_SP_Price { get; set; }

    public DateTime? Future_SP_From { get; set; }

    public DateTime? Future_SP_To { get; set; }

    public decimal? Markup { get; set; }

    public decimal? Margin { get; set; }

    public string? Brand { get; set; }

    public string? Size { get; set; }

    public decimal? CasePrice { get; set; }

    public string? Groups { get; set; }

    public string? MainDepartment { get; set; }

    public string? SubDepartment { get; set; }

    public string? SubSubDepartment { get; set; }

    public string? SeasonName { get; set; }

    public string? StoreName { get; set; }

    public string? StoreNumber { get; set; }

    public bool? SellOnWeb { get; set; }

    public decimal? WebCasePrice { get; set; }

    public decimal? WebPrice { get; set; }

    public int? LastSoldDate { get; set; }

    public Guid StoreID { get; set; }
}