// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemMainAndStoreGridItemSummary
{
    public Guid ItemID { get; set; }

    public Guid? LinkNo { get; set; }

    public Guid StoreNo { get; set; }

    public Guid ItemStoreID { get; set; }

    public Guid? MatrixTableNo { get; set; }

    public int? CaseQty { get; set; }

    public string? ModalNumber { get; set; }

    public string? BarcodeNumber { get; set; }

    public Guid? DepartmentID { get; set; }

    public short? Status { get; set; }

    public string? Name { get; set; }

    public string? Department { get; set; }

    public string? Matrix1 { get; set; }

    public string? Matrix2 { get; set; }

    public string? ItemTypeName { get; set; }

    public string? BarcodeType { get; set; }

    public string? SupplierName { get; set; }

    public string? Supplier_Item_Code { get; set; }

    public decimal OnHand { get; set; }

    public string? Brand { get; set; }

    public string? CustomerCode { get; set; }

    public decimal? CsOnHand { get; set; }

    public decimal MTD_Pc_Qty { get; set; }

    public decimal? MTD_Cs_Qty { get; set; }

    public decimal? YTD_Pc_Qty { get; set; }

    public decimal? YTD_Cs_Qty { get; set; }

    public decimal? PTD_Pc_Qty { get; set; }

    public decimal? PTD_Cs_Qty { get; set; }

    public decimal OnOrder { get; set; }

    public decimal? ReorderPoint { get; set; }

    public decimal? RestockLevel { get; set; }

    public decimal? OnTransferOrder { get; set; }

    public string? Groups { get; set; }
}