// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemSeason
{
    public Guid ItemStoreSeasonId { get; set; }

    public Guid? ItemStoreNo { get; set; }

    public Guid? SeasonNo { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }
}