// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemsForMobil
{
    public Guid ItemID { get; set; }

    public string? UPC { get; set; }

    public Guid ItemStoreID { get; set; }

    public string? Description { get; set; }

    public int? ItemType { get; set; }

    public decimal? OnHand { get; set; }

    public decimal? Price { get; set; }

    public decimal? Cost { get; set; }

    public bool? FS { get; set; }

    public bool? TX { get; set; }

    public bool? DIS { get; set; }

    public int? Measure { get; set; }

    public decimal? Units { get; set; }

    public int? SaleType { get; set; }

    public decimal? SalePrice { get; set; }

    public decimal? SpecialPrice { get; set; }

    public int? spQty { get; set; }

    public int? CaseQty { get; set; }

    public int? SaleMax { get; set; }

    public int? SaleMin { get; set; }

    public decimal? MinTSale { get; set; }

    public bool? AssignDate { get; set; }

    public Guid StoreID { get; set; }

    public string? ItemCode { get; set; }

    public DateTime? MainDateModified { get; set; }

    public DateTime? ItemStoreDateModified { get; set; }

    public string? AliesUPC { get; set; }

    public string? Size { get; set; }

    public string? Brand { get; set; }

    public decimal? Markup { get; set; }

    public decimal? Margin { get; set; }

    public string? SupplierName { get; set; }

    public string? Department { get; set; }

    public string? VenderCode { get; set; }

    public string? ConvertUnitPrice { get; set; }

    public decimal? CsCost { get; set; }

    public decimal? PcCost { get; set; }

    public DateTime? SaleStartDate { get; set; }

    public DateTime? SaleEndDate { get; set; }

    public int? LastDelivary { get; set; }

    public string? SPPrice { get; set; }

    public string? BinLocation { get; set; }
}