// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemPiece
{
    public Guid ItemID { get; set; }

    public string? Name { get; set; }

    public string? ModalNumber { get; set; }

    public string? BarcodeNumber { get; set; }

    public decimal OnOrder { get; set; }

    public decimal? OnHand { get; set; }

    public string? Department { get; set; }

    public string? StoreName { get; set; }

    public string? ParentCode { get; set; }

    public decimal? AVGCost { get; set; }

    public decimal? OnHandCase { get; set; }

    public decimal? Cost { get; set; }

    public decimal? Price { get; set; }

    public Guid? DepartmentID { get; set; }

    public Guid StoreNo { get; set; }

    public string? SupplierName { get; set; }

    public decimal OnTransfer { get; set; }

    public Guid? LinkNo { get; set; }

    public string? Supplier_Item_Code { get; set; }

    public int? ItemType { get; set; }

    public string? Brand { get; set; }

    public int? CaseQty { get; set; }

    public Guid ItemStoreID { get; set; }

    public string? MainDepartment { get; set; }

    public string? SubDepartment { get; set; }

    public string? SubSubDepartment { get; set; }
}