// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemlableView
{
    public Guid ItemStoreID { get; set; }

    public string? Name { get; set; }

    public string? BarcodeNumber { get; set; }

    public string? Description { get; set; }

    public string? ItemCode { get; set; }

    public string? SP_Price { get; set; }

    public decimal? Cost { get; set; }

    public string? Department { get; set; }

    public string? Meaasure { get; set; }

    public int? MeaasureType { get; set; }

    public decimal? ListPrice { get; set; }

    public string? AlwaysSpecial { get; set; }

    public string? CasePrice { get; set; }

    public string? RegPkgPrice { get; set; }

    public string? CaseSpecial { get; set; }

    public string? Brand { get; set; }

    public string? Size { get; set; }

    public DateTime? SaleBegins { get; set; }

    public DateTime? SaleEnds { get; set; }

    public string? MinTotalSale { get; set; }

    public decimal? Units { get; set; }

    public string? SaleMaxQty { get; set; }

    public int? CsQty { get; set; }

    public decimal? Price { get; set; }

    public int Test { get; set; }

    public string? DisplaySpecial { get; set; }

    public string? DisplayFutureSpecial { get; set; }

    public DateTime? FutureSaleStartDate { get; set; }

    public DateTime? FutureSaleEndDate { get; set; }

    public string? FutureSaleMaxQty { get; set; }

    public string? FutureMinTotalSale { get; set; }

    public string DisplayMember { get; set; } = null!;

    public string? DisplayPrice { get; set; }

    public string? DisplayPriceReg { get; set; }

    public decimal? DisplayMeaasure { get; set; }

    public string? ConvertUnitPrice { get; set; }

    public string? UPCA { get; set; }

    public string PlusTax { get; set; } = null!;

    public string? ParentCode { get; set; }

    public string? CompanyCode { get; set; }

    public string? StyleNo { get; set; }

    public string? RegCasePrice { get; set; }

    public string? ExtraInfo2 { get; set; }

    public string? ExtraInfo { get; set; }

    public string? PicturePath { get; set; }

    public string? PriceWithTax { get; set; }
}