// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemHeadSupplierView
{
    public Guid ItemSupplyID { get; set; }

    public Guid? ItemStoreNo { get; set; }

    public Guid? SupplierNo { get; set; }

    public decimal? TotalCost { get; set; }

    public decimal? GrossCost { get; set; }

    public int? MinimumQty { get; set; }

    public int? QtyPerCase { get; set; }

    public bool? IsOrderedOnlyInCase { get; set; }

    public int? AverageDeliveryDelay { get; set; }

    public string? ItemCode { get; set; }

    public bool? IsMainSupplier { get; set; }

    public short? SortOrder { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public decimal? CaseQty { get; set; }

    public decimal? SalePrice { get; set; }

    public bool? AssignDate { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public bool? OnSpecialReq { get; set; }

    public int? MinQty { get; set; }

    public int? MaxQty { get; set; }

    public int? UOMType { get; set; }

    public string? ColorName { get; set; }
}