// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemViewBasic
{
    public Guid ItemID { get; set; }

    public string? Name { get; set; }

    public string? ModalNumber { get; set; }

    public string? BarcodeNumber { get; set; }

    public Guid StoreNo { get; set; }

    public bool? IsTaxable { get; set; }

    public bool? IsDiscount { get; set; }

    public bool? IsFoodStampable { get; set; }

    public decimal? Cost { get; set; }

    public decimal Price { get; set; }

    public int? CaseQty { get; set; }

    public bool? PriceByCase { get; set; }

    public bool? CostByCase { get; set; }

    public string? CaseBarcodeNumber { get; set; }

    public decimal? OnHand { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? ItemStoreDateModified { get; set; }

    public decimal? Cs_Cost { get; set; }

    public decimal? Pc_Cost { get; set; }

    public Guid ItemStoreID { get; set; }

    public string? Department { get; set; }

    public string? Matrix1 { get; set; }

    public string? Matrix2 { get; set; }

    public string? SupplierName { get; set; }

    public string? SP_Price { get; set; }

    public DateTime? SP_From { get; set; }

    public DateTime? SP_To { get; set; }

    public decimal? Markup { get; set; }

    public decimal? Margin { get; set; }

    public string? Brand { get; set; }

    public string? Size { get; set; }

    public DateTime? DepartmentDateModified { get; set; }

    public Guid? DepartmentID { get; set; }

    public string? ItemTypeName { get; set; }

    public string? BarcodeType { get; set; }

    public string? Groups { get; set; }
}