// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemGroup
{
    public Guid ItemGroupID { get; set; }

    public string? ItemGroupName { get; set; }

    public Guid? ParentID { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public virtual ICollection<ItemToGroup> ItemToGroups { get; set; } = new List<ItemToGroup>();
}