// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ItemMainAndStoreGridItemsDailySale
{
    public Guid ItemID { get; set; }

    public Guid? LinkNo { get; set; }

    public Guid StoreNo { get; set; }

    public Guid ItemStoreID { get; set; }

    public Guid? MatrixTableNo { get; set; }

    public int? CaseQty { get; set; }

    public string? ModalNumber { get; set; }

    public string? BarcodeNumber { get; set; }

    public Guid? DepartmentID { get; set; }

    public short? Status { get; set; }

    public string? Name { get; set; }

    public string? Department { get; set; }
}