// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Layaway
{
    public Guid LayawayID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Price { get; set; }

    public decimal? Qty { get; set; }

    public int? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserCreate { get; set; }

    public Guid? UserModified { get; set; }

    /// <summary>
    /// 0 = Void, 1 = In Layaway, 2 = Sold
    /// </summary>
    public int? LayawayStatus { get; set; }

    public Guid? TransactionID { get; set; }
}