// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class LeftCreditsView
{
    public Guid TransactionID { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public decimal? LeftCredit { get; set; }

    public Guid? CustomerID { get; set; }

    public int TransactionType { get; set; }
}