// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class LocalTransaction
{
    public short? Status { get; set; }

    public Guid TransactionID { get; set; }

    public decimal? SaleAmount { get; set; }

    public decimal? PaidAmount { get; set; }

    public decimal? Tax { get; set; }

    public string TransactionNo { get; set; } = null!;

    public Guid? ShipTo { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public string? RegisterNo { get; set; }

    public DateTime? EndSaleTime { get; set; }

    public Guid? CustomerID { get; set; }

    public string CustomerName { get; set; } = null!;

    public string? CustomerNo { get; set; }

    public string? CashierName { get; set; }

    public int TransactionType { get; set; }

    public decimal? TotalQty { get; set; }

    public string? Tender { get; set; }

    public DateTime? DateModified { get; set; }
}