// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class LookAccountView
{
    public Guid LookAccountID { get; set; }

    public Guid? CustomerID { get; set; }

    public short? DaysOver { get; set; }

    public decimal? Ammount { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}