// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class LoyaltyPromotionView
{
    public Guid? UserModified { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public DateTime? DateCreated { get; set; }

    public int? Status { get; set; }

    public bool? InculudeDiscounts { get; set; }

    public bool? IncludeNoDiscountItems { get; set; }

    public bool? IncludeSaleItems { get; set; }

    public decimal? ForDolar { get; set; }

    public int? Points { get; set; }

    public Guid LoyaltyPromotionID { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public string? Code { get; set; }

    public string? Name { get; set; }

    public int? Item { get; set; }

    public int? Department { get; set; }

    public int? Brand { get; set; }

    public int? Store { get; set; }

    public bool? AutoAssign { get; set; }
}