// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Loyalty
{
    public Guid LoyaltyID { get; set; }

    public decimal? AvailPoints { get; set; }

    public Guid? CustomerID { get; set; }

    public DateTime? DateCreated { get; set; }

    public decimal? Points { get; set; }

    public int? Status { get; set; }

    public Guid? TransactionID { get; set; }

    public DateTime? DateModified { get; set; }

    public virtual Customer? Customer { get; set; }
}