// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class MarkOctopusSyncItemsSuccessResult
    {
        public bool? Success { get; set; }
        [StringLength(27)]
        public string Description { get; set; } = default!;
    }
}
