// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class MatrixValue
{
    public Guid MatrixValueID { get; set; }

    public Guid MatrixColumnNo { get; set; }

    public string DisplayValue { get; set; } = null!;

    public int? SortValue { get; set; }

    public short? Status { get; set; }

    public string? Code { get; set; }

    public virtual MatrixColumn MatrixColumnNoNavigation { get; set; } = null!;
}