// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class MatrixColumnView
{
    public Guid MatrixColumnID { get; set; }

    public string ColumnName { get; set; } = null!;

    public Guid MatrixNo { get; set; }

    public int? SortOrder { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }
}