// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class MatrixColumn
{
    public Guid MatrixColumnID { get; set; }

    public Guid MatrixNo { get; set; }

    public string ColumnName { get; set; } = null!;

    public int? SortOrder { get; set; }

    public short? Status { get; set; }

    public virtual MatrixTable MatrixNoNavigation { get; set; } = null!;

    public virtual ICollection<MatrixValue> MatrixValues { get; set; } = new List<MatrixValue>();
}