// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class MatrixOnhand
{
    public string? Color { get; set; }

    public string? Size { get; set; }

    public int? OnHand { get; set; }

    public Guid StoreID { get; set; }

    public Guid? LinkNo { get; set; }
}