// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class MovementsView
{
    public int ActionType { get; set; }

    public string MovementType { get; set; } = null!;

    public string? Details { get; set; }

    public string? DebitAccount { get; set; }

    public string? CreditAccount { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}