// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class MyCloudGrocerItem
{
    public Guid ID { get; set; }

    public string Category { get; set; } = null!;

    public string SubCategory { get; set; } = null!;

    public string? UPC_SKU { get; set; }

    public string? ItemDescription { get; set; }

    public int RegularPricePer { get; set; }

    public decimal? RegularPrice { get; set; }

    public int? CaseQty { get; set; }

    public decimal? CasePrice { get; set; }

    public int? SpecialPricePer { get; set; }

    public decimal? SpecialPrice { get; set; }

    public DateTime? SpecialStarts { get; set; }

    public DateTime? SpecialEnds { get; set; }

    public string? Brand { get; set; }

    public decimal? QtyOnHand { get; set; }

    public string? Size { get; set; }

    public bool? IsEBT { get; set; }

    public bool? IsTaxable { get; set; }

    public DateTime? LastSold { get; set; }

    public string? StoreName { get; set; }

    public string? SKUs { get; set; }
}