// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class NewBillsForQBView
{
    public string? BillNo { get; set; }

    public decimal? Amount { get; set; }

    public decimal? AmountPay { get; set; }

    public DateTime? BillDate { get; set; }

    public DateTime? BillDue { get; set; }

    public string? Note { get; set; }

    public string? SQbNumber { get; set; }

    public Guid BillID { get; set; }

    public Guid? StoreID { get; set; }
}