// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class OnHoldEntryLog
{
    public decimal? BreakdownPrice { get; set; }

    public decimal? BreakdownQty { get; set; }

    public bool? CaseItem { get; set; }

    public decimal? Cost { get; set; }

    public decimal? dAmount { get; set; }

    public string? dDescription { get; set; }

    public string? dDiscountID { get; set; }

    public int? dDiscountType { get; set; }

    public decimal? DefaultPrice { get; set; }

    public string? Description { get; set; }

    public bool? Discountable { get; set; }

    public decimal? dMinTotalSale { get; set; }

    public int? EntryType { get; set; }

    public bool? FoodStampable { get; set; }

    public int ID { get; set; }

    public string? ItemID { get; set; }

    public int? ItemType { get; set; }

    public bool? ManualItem { get; set; }

    public string? ModelNo { get; set; }

    public string? Note { get; set; }

    public Guid? OnHoldID { get; set; }

    public decimal? Price { get; set; }

    public decimal? PriceA { get; set; }

    public decimal? PriceB { get; set; }

    public bool? PriceBaseOnTotal { get; set; }

    public decimal? PriceC { get; set; }

    public decimal? PriceD { get; set; }

    public decimal? Qty { get; set; }

    public decimal? RegPrice { get; set; }

    public bool? Return { get; set; }

    public bool? SaleAssignDate { get; set; }

    public DateTime? SaleEndDate { get; set; }

    public decimal? SalePrice { get; set; }

    public DateTime? SaleStartDate { get; set; }

    public int? SaleType { get; set; }

    public bool? SplitItem { get; set; }

    public string? TagAlong1 { get; set; }

    public string? TagAlong2 { get; set; }

    public string? TagAlong3 { get; set; }

    public bool? Taxable { get; set; }

    public decimal? Total { get; set; }

    public decimal? UOMQty { get; set; }

    public int? UOMType { get; set; }

    public string? UPC { get; set; }

    public int? MinQtySale { get; set; }

    public int? MaxQtySale { get; set; }

    public double? CaseQty { get; set; }

    public decimal? CasePrice { get; set; }

    public Guid? DepartmentID { get; set; }

    public string? TableItemID { get; set; }

    public float? ItemDiscountPercent { get; set; }

    public bool? AltNeed { get; set; }

    public DateTime? AltExpectedDate { get; set; }

    public decimal? AvgCost { get; set; }

    public string? NewDescription { get; set; }

    public string? ReturenEntryID { get; set; }
}