// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class OpenSaleOrderView
{
    public Guid? WOID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Qty { get; set; }

    public decimal SoldQty { get; set; }

    public decimal? Price { get; set; }
}