// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class OrderForCenter
{
    public Guid PurchaseOrderId { get; set; }

    public string? PoNo { get; set; }

    public int Type { get; set; }

    public DateTime? PurchaseOrderDate { get; set; }

    public decimal? GrandTotal { get; set; }

    public short? Postatus { get; set; }

    public Guid? SupplierNo { get; set; }

    public Guid? StoreNo { get; set; }

    public short? IsVoid { get; set; }
}