// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class p_xResult
    {
        [StringLength(10)]
        public string? col1 { get; set; }
        public double? col2 { get; set; }
        public double? col3 { get; set; }
        public double? col4 { get; set; }
    }
}
