// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PaymentsView
{
    public Guid SuppTenderEntryID { get; set; }

    public string? SuppTenderNo { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? SupplierID { get; set; }

    public int TenderID { get; set; }

    public decimal? Amount { get; set; }

    public string? Common1 { get; set; }

    public string? Common2 { get; set; }

    public string? Common3 { get; set; }

    public string? Common4 { get; set; }

    public string? Common5 { get; set; }

    public string? Common6 { get; set; }

    public DateTime? TenderDate { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public bool? TransferedToBookkeeping { get; set; }

    public string? VisaType { get; set; }

    public string? Name { get; set; }

    public string? TenderName { get; set; }

    public int Type { get; set; }

    public DateTime? Check_Date { get; set; }

    public int? NumApplyBills { get; set; }
}