// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PayOutView
{
    public Guid PayOutID { get; set; }

    public decimal? Amount { get; set; }

    public string? Reason { get; set; }

    public DateTime? PayOutDate { get; set; }

    public string? PayoutTime { get; set; }

    public Guid? RegisterID { get; set; }

    public Guid? ChasierID { get; set; }

    public Guid? BatchID { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public string? RegisterNo { get; set; }

    public string? Cashier { get; set; }

    public string? BatchNo { get; set; }

    public string UserAutherized { get; set; } = null!;

    public string? StoreName { get; set; }

    public Guid? StoreID { get; set; }
}