// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PayToSupplier
{
    public Guid TransactionID { get; set; }

    public decimal? ApplyAmount { get; set; }
}