// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PhoneOrderEntryPickSheet
{
    public string? BarcodeNumber { get; set; }

    public decimal? UOMPrice { get; set; }

    public string? Name { get; set; }

    public string? ModalNumber { get; set; }

    public decimal? Qty { get; set; }

    public string? Note { get; set; }

    public bool? Picked { get; set; }

    public Guid? PhoneOrderID { get; set; }

    public int? SortOrder { get; set; }

    public short? Status { get; set; }

    public string? UomType { get; set; }

    public string? ManufacturerPartNo { get; set; }

    public string? Department { get; set; }

    public decimal? OnHand { get; set; }

    public string? ItemGroups { get; set; }

    public string? Brand { get; set; }

    public string? CustomField1 { get; set; }

    public string? CustomField2 { get; set; }

    public string? CustomField3 { get; set; }

    public string? CustomField4 { get; set; }

    public string? CustomField5 { get; set; }

    public string? CustomField6 { get; set; }

    public string? CustomField7 { get; set; }

    public string? CustomField8 { get; set; }

    public string? CustomField9 { get; set; }

    public string? CustomField10 { get; set; }

    public string? BinLocation { get; set; }

    public string? StyleNo { get; set; }
}