// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PhoneOrder
{
    public Guid PhoneOrderID { get; set; }

    public string? PhoneOrderNo { get; set; }

    public Guid? StoreID { get; set; }

    public Guid CustomerID { get; set; }

    public string? DriversNote { get; set; }

    public string? CustomerNote { get; set; }

    public string? PickNote { get; set; }

    public DateTime? PhoneOrderDate { get; set; }

    public DateTime? PhoneOrderTime { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string? ShiftID { get; set; }

    public Guid? ShippingID { get; set; }

    public int? PhoneOrderStatus { get; set; }

    public Guid? PickByID { get; set; }

    public Guid? TakeByID { get; set; }

    public Guid? TransactionID { get; set; }

    public int? Type { get; set; }

    public decimal? Total { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public bool? Freezer { get; set; }

    public string? PaymentNote { get; set; }

    public Guid? UserEditing { get; set; }

    public DateTime? StartEditing { get; set; }

    public int? TenderID { get; set; }

    public Guid? CustomerNoteID { get; set; }

    public Guid? DriversNoteID { get; set; }

    public int? Priority { get; set; }

    public DateTime? PickDate { get; set; }

    public string? PickTime { get; set; }

    public string? OnHoldMsg { get; set; }
}