// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PhoneOrderPickSheet
{
    public Guid PhoneOrderID { get; set; }

    public string? Type { get; set; }

    public DateTime? PhoneOrderDate { get; set; }

    public DateTime? PhoneOrderTime { get; set; }

    public string? PhoneOrderNo { get; set; }

    public string? Name { get; set; }

    public string? CustomerNo { get; set; }

    public string? ShiftID { get; set; }

    public string? PickNote { get; set; }

    public string? Phone { get; set; }

    public string? Cell { get; set; }

    public string Address { get; set; } = null!;

    public string? CityStateAndZip { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string? ShipName { get; set; }

    public string? ShipAddress { get; set; }

    public string? ShipCityStateZip { get; set; }

    public string? TakeBy { get; set; }

    public DateTime? LastDateCleared { get; set; }

    public string? ShipPhone { get; set; }

    public string? ShipCell { get; set; }

    public string? CustomerGroup { get; set; }

    public string? CustomerNote { get; set; }

    public bool Freezer { get; set; }

    public string? TenderName { get; set; }

    public string? GroupName { get; set; }

    public string? Zones { get; set; }
}