// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PhoneNote
{
    public int PhoneNoteIDVal { get; set; }

    public string? Value { get; set; }

    public short? Type { get; set; }

    public short? Sort { get; set; }

    public short? Status { get; set; }
}