// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PickWagon
{
    public int PickWagonID { get; set; }

    public string? WagonNo { get; set; }

    public Guid? PhoneOrderID { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserID { get; set; }
}