// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PriceChangeHistory
{
    public Guid PriceChangeHistoryID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public string? PriceLevel { get; set; }

    public decimal? OldPrice { get; set; }

    public decimal? NewPrice { get; set; }

    public Guid? UserID { get; set; }

    public string? SaleType { get; set; }

    public string? SP_Price { get; set; }

    public string? SaleDate { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public short? status { get; set; }

    public virtual ItemStore? ItemStore { get; set; }
}