// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PrintInvoiceEntryView
{
    public decimal? Qty { get; set; }

    public decimal? UOMPrice { get; set; }

    public string? ModalNumber { get; set; }

    public string Description { get; set; } = null!;

    public string? ItemCode { get; set; }

    public decimal? Total { get; set; }

    public decimal? DiscountPerc { get; set; }

    public bool? Taxable { get; set; }

    public string? Note { get; set; }

    public string? Name { get; set; }

    public string? Cs_Pc_Ds { get; set; }

    public Guid? TransactionID { get; set; }

    public int? Sort { get; set; }
}