// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Printed
{
    public string PrintedName { get; set; } = null!;

    public string PrintedContent { get; set; } = null!;

    public int? Status { get; set; }
}