// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PrintLabelLayoutView
{
    public Guid PrintLabelLayoutID { get; set; }

    public string? LayoutName { get; set; }

    public string? LayoutContent { get; set; }

    public int? PrinterType { get; set; }
}