// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PriorityLevel
{
    public int PriorityID { get; set; }

    public Guid StoreID { get; set; }

    public string StoreNumber { get; set; } = null!;

    public int Priority { get; set; }

    public int Status { get; set; }

    public DateTime? DateModified { get; set; }

    public string? StoreName { get; set; }
}