// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PurchaseOrdersMatrixView
{
    public Guid PurchaseOrderId { get; set; }

    public Guid? SupplierNo { get; set; }

    public Guid? StoreNo { get; set; }

    public string? PoNo { get; set; }

    public Guid? PersonOrderdId { get; set; }

    public decimal? GrandTotal { get; set; }

    public Guid? ShipVia { get; set; }

    public Guid? ShipTo { get; set; }

    public string? TrackNo { get; set; }

    public Guid? TermsNo { get; set; }

    public DateTime? PurchaseOrderDate { get; set; }

    public DateTime? ReqDate { get; set; }

    public DateTime? ExpirationDate { get; set; }

    public bool? Shipdrop { get; set; }

    public short? POStatus { get; set; }

    public string? Note { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public int OpenItemsCount { get; set; }

    public string? StoreName { get; set; }

    public bool? Reorder { get; set; }

    public string? Supplier { get; set; }

    public string? Supplier_No { get; set; }

    public string? User { get; set; }

    public Guid? TermsID { get; set; }

    public Guid? BuyerID { get; set; }

    public Guid? BillToStoreID { get; set; }

    public string? VendorPONo { get; set; }

    public Guid? DepartmentID { get; set; }

    public Guid? SeasonID { get; set; }
}