// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class PurOrderEntryPPC
{
    public string? ItemName { get; set; }

    public string? BarCode { get; set; }

    public int? QtyOrdered { get; set; }

    public Guid PurchaseOrderEntryId { get; set; }

    public Guid PurchaseOrderID { get; set; }

    public Guid? ItemNo { get; set; }

    public int? UOMType { get; set; }

    public decimal? UOMPrice { get; set; }

    public int? SortOrder { get; set; }
}