// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Qty_Amount
{
    public decimal? QtySum { get; set; }

    public DateTime? SaleDateQA { get; set; }

    public decimal? Debit { get; set; }

    public Guid? CustomerID { get; set; }
}