// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RCA_SyncOctopusItem
{
    public int RecordID { get; set; }

    public Guid ItemStoreNo { get; set; }

    public Guid ItemNo { get; set; }

    public Guid? StoreNo { get; set; }

    public string? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public int? Pick { get; set; }
}