// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RCA_OctopusOrderHeader
{
    public Guid RowID { get; set; }

    public int? Id { get; set; }

    public string? Source { get; set; }

    public string? Email { get; set; }

    public string? CreatedAt { get; set; }

    public string? UpdatedAt { get; set; }

    public decimal? TotalPrice { get; set; }

    public int? OrderNumber { get; set; }

    public string? CustomerFirstName { get; set; }

    public string? CustomerLastName { get; set; }

    public string? CustomerEmail { get; set; }
}