// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReceiveOrder
{
    public Guid ReceiveID { get; set; }

    public string? PackingSlipNo { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? SupplierNo { get; set; }

    public Guid? BillID { get; set; }

    public decimal? Freight { get; set; }

    public decimal? Discount { get; set; }

    public string? Note { get; set; }

    public decimal? Total { get; set; }

    public decimal? CurrBalance { get; set; }

    public bool? IsDiscAmount { get; set; }

    public DateTime? ReceiveOrderDate { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public string? FilePath { get; set; }

    public decimal? CustomsDuties { get; set; }

    public decimal? OtherCharges { get; set; }

    public Guid? TermsID { get; set; }

    public Guid? BuyerID { get; set; }

    public Guid? BillToStoreID { get; set; }

    public string? VendorPONo { get; set; }

    public Guid? DepartmentID { get; set; }

    public Guid? SeasonID { get; set; }

    public Guid? UserEditing { get; set; }

    public DateTime? StartEditing { get; set; }
}