// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReceiveForCenter
{
    public string? BillNo { get; set; }

    public int Type { get; set; }

    public DateTime? ReceiveOrderDate { get; set; }

    public Guid? SupplierNo { get; set; }

    public Guid? StoreID { get; set; }

    public Guid ReceiveID { get; set; }

    public decimal? Total { get; set; }

    public short? Status { get; set; }

    public int? Restatus { get; set; }
}