// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReceiveOrderPrintView
{
    public string? PoNo { get; set; }

    public DateTime? ReceiveOrderDate { get; set; }

    public decimal? Total { get; set; }

    public string? Note { get; set; }

    public decimal? Discount { get; set; }

    public decimal? TotalAfterDisc { get; set; }

    public decimal? Freight { get; set; }

    public string? SupplierNo { get; set; }

    public string? Name { get; set; }

    public string ContactName { get; set; } = null!;

    public string Address { get; set; } = null!;

    public string CSZSupplier { get; set; } = null!;

    public string? BillNo { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? BillDate { get; set; }

    public Guid ReceiveID { get; set; }

    public decimal? CustomsDuties { get; set; }

    public decimal? OtherCharges { get; set; }
}