// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReceiveTransfer
{
    public Guid ReceiveTransferID { get; set; }

    public DateTime? ReceiveDate { get; set; }

    public string? ReciveNo { get; set; }

    public Guid? StoreID { get; set; }

    /// <summary>
    /// This Field take from The TransferItem Table  TransaferID
    /// </summary>
    public Guid? TransferID { get; set; }

    public DateTime? DateCreate { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserCreate { get; set; }

    public Guid? UserModified { get; set; }

    public int? Status { get; set; }
}