// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReceiveTransferEntryView
{
    public Guid ReceiveTranferEntryID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public Guid? TransferEntryID { get; set; }

    public decimal? Qty { get; set; }

    public decimal? UOMQty { get; set; }

    public int? Status { get; set; }

    public decimal? TransferedQty { get; set; }

    public decimal? TransferedUOMQty { get; set; }

    public string ReceiveNo { get; set; } = null!;

    public Guid TransferID { get; set; }

    public string? TransferNo { get; set; }

    public string? Note { get; set; }

    public Guid ItemID { get; set; }

    public string? Name { get; set; }

    public string? ModalNumber { get; set; }

    public string? BarcodeNumber { get; set; }

    public string? StyleNo { get; set; }

    public decimal UOMPrice { get; set; }

    public decimal? Pc_Cost { get; set; }

    public decimal? Cs_Cost { get; set; }

    public string? Department { get; set; }

    public int? CaseQty { get; set; }

    public string? UserReceived { get; set; }

    public Guid? ReceiveTransferID { get; set; }

    public decimal? Cost { get; set; }

    public int? UOMType { get; set; }

    public string? UOMTypeName { get; set; }
}