// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReceiveTransferEntry
{
    public Guid ReceiveTranferEntryID { get; set; }

    public Guid? ReceiveTransferID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public Guid? TransferEntryID { get; set; }

    public decimal? Qty { get; set; }

    public decimal? UOMQty { get; set; }

    public int? UOMType { get; set; }

    public DateTime? DateCreate { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserCreate { get; set; }

    public Guid? UserModified { get; set; }

    public int? Status { get; set; }

    public decimal? Cost { get; set; }
}