// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RecieptDelivery
{
    public string? RecieptTxt { get; set; }

    public string TransactionNo { get; set; } = null!;
}