// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RecOrderEntryHistory
{
    public Guid ReceiveOrderEntryID { get; set; }

    public Guid? ReceiveOrderID { get; set; }

    public Guid? ItemNo { get; set; }

    public decimal? QtyOrdered { get; set; }

    public int? UOMType { get; set; }

    public string? ItemName { get; set; }

    public decimal? UOMPrice { get; set; }

    public string? BarCode { get; set; }

    public int? SortOrder { get; set; }

    public decimal? csQty { get; set; }
}