// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RecOrderHistoryPPC
{
    public Guid ReceiveID { get; set; }

    public decimal? GrandTotal { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? SupplierNo { get; set; }

    public DateTime? ReceiveOrderDate { get; set; }

    public string? Supplier { get; set; }

    public Guid? BillID { get; set; }
}