// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RegisterKey
{
    public string? ActionID { get; set; }

    public string? ActionKey { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public bool? IsAction { get; set; }

    public bool? IsButton { get; set; }

    public int RegisterKeyID { get; set; }

    public short? ShiftType { get; set; }

    public short? Status { get; set; }

    public Guid? UserCreated { get; set; }

    public Guid? UserModified { get; set; }
}