// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RegShiftEntry
{
    public DateTime? LogOnTime { get; set; }

    public DateTime? LogOutTime { get; set; }

    public Guid RegDetailID { get; set; }

    public Guid? RegShiftID { get; set; }

    public Guid? UserID { get; set; }
}