// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RepBatchView1
{
    public string? BatchNumber { get; set; }

    public DateTime? OpeningDateTime { get; set; }

    public decimal? OpeningAmount { get; set; }

    public Guid BatchID { get; set; }

    public decimal PayOut { get; set; }

    public decimal? TotalSales { get; set; }

    public decimal Tax { get; set; }

    public decimal? TotalReturn { get; set; }

    public decimal PayBalance { get; set; }

    public decimal SaleOnAccount { get; set; }

    public decimal CashBack { get; set; }
}