// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Report
{
    public int id_report { get; set; }

    public string? ReportName { get; set; }

    public byte[]? Data { get; set; }
}