// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReportsUsed
{
    public int RepUserId { get; set; }

    public string? RepNama { get; set; }

    public Guid? UserId { get; set; }

    public DateTime? DateUsed { get; set; }
}