// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReportsTable
{
    public string? ReportName { get; set; }

    public string? ReportDescription { get; set; }

    public string? ReportSection { get; set; }

    public string? ReportDll { get; set; }

    public bool? Status { get; set; }

    public int? SortOrder { get; set; }

    public string? ReportType { get; set; }

    public string? Handlers { get; set; }

    public string? Icon { get; set; }
}