// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RequestTransferEntry
{
    public Guid RequestTransferEntryID { get; set; }

    public Guid? RequestTransferID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Qty { get; set; }

    public decimal? UOMQty { get; set; }

    public int? UOMType { get; set; }

    public string? Note { get; set; }

    public int? SortOrder { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserCreated { get; set; }

    public Guid? UserModified { get; set; }

    public int? Status { get; set; }

    public decimal? Cost { get; set; }

    public Guid? CustomerId { get; set; }

    public Guid? ItemID { get; set; }

    public Guid? TransactionEntryID { get; set; }
}