// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class RequestTransferView
{
    public Guid RequestTransferID { get; set; }

    public string? RequestNo { get; set; }

    public string? FromStore { get; set; }

    public string? ToStore { get; set; }

    public string RequestTransferStatusDec { get; set; } = null!;

    public int? Status { get; set; }

    public string? Note { get; set; }

    public string? UserName { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? FromStoreID { get; set; }

    public Guid? ToStoreID { get; set; }

    public DateTime? RequestDate { get; set; }

    public int RequestStatus { get; set; }

    public decimal? openItems { get; set; }
}