// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ResellersCommission
{
    public Guid CommissionID { get; set; }

    public Guid ResellerID { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? SentDate { get; set; }

    public DateTime? CheckDate { get; set; }

    public string? CheckNo { get; set; }

    public string? CheckBank { get; set; }

    public string? CheckSubsidiary { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}