// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReturnedQtyView
{
    public Guid? TransactionID { get; set; }

    public Guid TransactionEntryID { get; set; }

    public decimal? Qty { get; set; }

    public double ReturnedQty { get; set; }
}