// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ReturnForRep
{
    public int Type { get; set; }

    public DateTime? DateT { get; set; }

    public string? Num { get; set; }

    public int? DueDate { get; set; }

    public decimal? OpenBalance { get; set; }

    public decimal AmountPay { get; set; }

    public Guid IDc { get; set; }

    public Guid PID { get; set; }

    public string? SuppName { get; set; }

    public decimal? Amount { get; set; }

    public string? SupplierNo { get; set; }

    public short? SupplierStatus { get; set; }
}