// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_TransactionAvrgResult
    {
        [StringLength(50)]
        public string? StoreName { get; set; }
        public int? NoTrans { get; set; }
        [Column("UOMQty", TypeName = "decimal(38,3)")]
        public decimal? UOMQty { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        public DateTime? SaleDay { get; set; }
        [Column("TransUnit", TypeName = "decimal(38,6)")]
        public decimal? TransUnit { get; set; }
        [Column("TransSale", TypeName = "money")]
        public decimal? TransSale { get; set; }
        public int? pplCount { get; set; }
    }
}
