// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_SumLoyaltyResult
    {
        public int? Transacions { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(101)]
        public string? CustomerName { get; set; }
        [Column("TotalAvelPoints", TypeName = "decimal(38,2)")]
        public decimal? TotalAvelPoints { get; set; }
        [Column("TotalSales", TypeName = "money")]
        public decimal? TotalSales { get; set; }
        [Column("TotalPoints", TypeName = "decimal(38,2)")]
        public decimal? TotalPoints { get; set; }
    }
}
