// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_TotalSalesWeeklyResult
    {
        [Column("Total", TypeName = "decimal(38,3)")]
        public decimal? Total { get; set; }
        public int? Trans { get; set; }
        [Column("AvgSale", TypeName = "money")]
        public decimal? AvgSale { get; set; }
        public DateOnly? Date { get; set; }
    }
}
