// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_ASSO_SalesSummaryResult
    {
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string? Assoc { get; set; }
        [StringLength(50)]
        public string? SKU { get; set; }
        [StringLength(50)]
        public string? Department { get; set; }
        [Column("Tran#")]
        [StringLength(50)]
        public string Tran { get; set; } = default!;
        [Column("Gross", TypeName = "money")]
        public decimal? Gross { get; set; }
        [Column("Price", TypeName = "decimal(38,6)")]
        public decimal? Price { get; set; }
        [Column("QTY", TypeName = "decimal(30,3)")]
        public decimal? QTY { get; set; }
        [StringLength(50)]
        public string? Store { get; set; }
        [Column("Net", TypeName = "decimal(18,3)")]
        public decimal? Net { get; set; }
        [Column("Disc", TypeName = "decimal(20,4)")]
        public decimal? Disc { get; set; }
        [StringLength(250)]
        public string DESC { get; set; } = default!;
        [StringLength(50)]
        public string? Brand { get; set; }
        [StringLength(101)]
        public string AssocName { get; set; } = default!;
        [StringLength(50)]
        public string? FirstName { get; set; }
        [StringLength(50)]
        public string? LastName { get; set; }
        [StringLength(50)]
        public string? Email { get; set; }
    }
}
