// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class RPT_ReplacedItemsResult
    {
        [StringLength(50)]
        public string? PhoneOrderNo { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(100)]
        public string? Phone { get; set; }
        [StringLength(100)]
        public string? Cell { get; set; }
        [StringLength(50)]
        public string LastName { get; set; } = default!;
        [StringLength(50)]
        public string FirstName { get; set; } = default!;
        public DateTime? PhoneOrderDate { get; set; }
        public DateTime? DeliveryDate { get; set; }
        [StringLength(13)]
        public string PhoneOrderStatus { get; set; } = default!;
        [Column("OldQty", TypeName = "decimal(19,2)")]
        public decimal OldQty { get; set; }
        [Column("NewQty", TypeName = "decimal(19,2)")]
        public decimal NewQty { get; set; }
        [StringLength(101)]
        public string UserCollected { get; set; } = default!;
        [StringLength(250)]
        public string? RemovedItem { get; set; }
        [StringLength(50)]
        public string? RemovedModelNo { get; set; }
        [StringLength(50)]
        public string? RemovedUPC { get; set; }
        [StringLength(250)]
        public string? AddedItem { get; set; }
        [StringLength(50)]
        public string? AddedModelNo { get; set; }
        [StringLength(50)]
        public string? AddedUPC { get; set; }
        [StringLength(8)]
        public string Action { get; set; } = default!;
    }
}
