// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class RPT_SalesAndTendersReportResult
    {
        public DateOnly? SaleDate { get; set; }
        [StringLength(50)]
        public string? Store { get; set; }
        public int TotalTransactionCount { get; set; }
        [Column("TotalSale", TypeName = "money")]
        public decimal TotalSale { get; set; }
        [Column("TotalDiscount", TypeName = "money")]
        public decimal TotalDiscount { get; set; }
        [Column("TotalCOGS", TypeName = "decimal(38,6)")]
        public decimal TotalCOGS { get; set; }
        [Column("TotalReturns", TypeName = "decimal(38,3)")]
        public decimal TotalReturns { get; set; }
        [Column("TotalTax", TypeName = "money")]
        public decimal TotalTax { get; set; }
        [Column("TotalGiftCardSold", TypeName = "money")]
        public decimal TotalGiftCardSold { get; set; }
    }
}
