// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_CustomerListResult
    {
        [StringLength(102)]
        public string Name { get; set; } = default!;
        public Guid CustomerID { get; set; }
        [StringLength(100)]
        public string? PhoneNumber1 { get; set; }
        [StringLength(100)]
        public string? PhoneNumber2 { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [Column("Credit", TypeName = "money")]
        public decimal? Credit { get; set; }
        [StringLength(50)]
        public string? Contact1 { get; set; }
        [StringLength(50)]
        public string? Contact2 { get; set; }
        [Column("BalanceDoe", TypeName = "money")]
        public decimal BalanceDoe { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; } = default!;
        [StringLength(50)]
        public string LastName { get; set; } = default!;
        [StringLength(472)]
        public string AllMainDetails { get; set; } = default!;
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        public Guid? ResellerID { get; set; }
        [StringLength(15)]
        public string? Zip { get; set; }
        [StringLength(100)]
        public string? State { get; set; }
        [StringLength(100)]
        public string? City { get; set; }
        [StringLength(251)]
        public string Address { get; set; } = default!;
        public DateTime? BirthDay { get; set; }
        [StringLength(50)]
        public string? Email { get; set; }
        [Column("Points", TypeName = "decimal(38,2)")]
        public decimal Points { get; set; }
        [StringLength(50)]
        public string? StoreOpen { get; set; }
        [Column("Over0", TypeName = "money")]
        public decimal? Over0 { get; set; }
        [Column("Over30", TypeName = "money")]
        public decimal? Over30 { get; set; }
        [Column("Over60", TypeName = "money")]
        public decimal? Over60 { get; set; }
        [Column("Over90", TypeName = "money")]
        public decimal? Over90 { get; set; }
        [Column("Over120", TypeName = "money")]
        public decimal? Over120 { get; set; }
    }
}
