// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_ZipSummaryResult
    {
        [StringLength(15)]
        public string? Zip { get; set; }
        [Column("Qty", TypeName = "decimal(38,3)")]
        public decimal? Qty { get; set; }
        [Column("Ext Price", TypeName = "decimal(38,6)")]
        public decimal? ExtPrice { get; set; }
        [Column("TotalMargin", TypeName = "decimal(38,6)")]
        public decimal? TotalMargin { get; set; }
    }
}
