// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_AttendanceDetailsResult
    {
        [StringLength(102)]
        public string EmployeeName { get; set; } = default!;
        [Column("Time", TypeName = "decimal(10,2)")]
        public decimal? Time { get; set; }
        [StringLength(30)]
        public string? Weekday { get; set; }
        public int? InOutID { get; set; }
        public DateTime InTime { get; set; }
        public DateTime? OutTime { get; set; }
        public Guid? StoreID { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        public Guid UserID { get; set; }
        [Column("OverTime", TypeName = "decimal(18,2)")]
        public decimal? OverTime { get; set; }
        [Column("Sick", TypeName = "decimal(18,2)")]
        public decimal? Sick { get; set; }
        [Column("Holiday", TypeName = "decimal(18,2)")]
        public decimal? Holiday { get; set; }
        [Column("Ragulare", TypeName = "decimal(18,2)")]
        public decimal? Ragulare { get; set; }
    }
}
