// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_ItemDetailsOnPhoneOrderResult
    {
        [Column("Qty", TypeName = "decimal(19,2)")]
        public decimal? Qty { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        [Column("OnHand", TypeName = "decimal(19,3)")]
        public decimal? OnHand { get; set; }
        public Guid ItemStoreID { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        [StringLength(50)]
        public string? PhoneOrderNo { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; } = default!;
        [StringLength(50)]
        public string LastName { get; set; } = default!;
        [StringLength(101)]
        public string PickedBy { get; set; } = default!;
        [Column("PickQty", TypeName = "decimal(19,2)")]
        public decimal PickQty { get; set; }
        [StringLength(500)]
        public string? Groups { get; set; }
        [StringLength(2000)]
        public string? PickNote { get; set; }
        [StringLength(50)]
        public string? PhoneOrderType { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? DateCreated { get; set; }
    }
}
