// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_ReceiveEntryResult
    {
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal Price { get; set; }
        [StringLength(120)]
        public string? Size { get; set; }
        [Column("QTY", TypeName = "decimal(18,2)")]
        public decimal? QTY { get; set; }
        [StringLength(103)]
        public string? Cost { get; set; }
        public int? CaseQty { get; set; }
        [StringLength(103)]
        public string? MarkupMARGIN { get; set; }
    }
}
