// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_AttendanceSummaryResult
    {
        [StringLength(102)]
        public string EmployeeName { get; set; } = default!;
        [Column("TotalHours", TypeName = "decimal(10,2)")]
        public decimal? TotalHours { get; set; }
    }
}
