// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_TotalSalesMonthlyResult
    {
        [Column("Total", TypeName = "decimal(38,3)")]
        public decimal? Total { get; set; }
        public int? Trans { get; set; }
        [Column("AvgSale", TypeName = "decimal(38,6)")]
        public decimal? AvgSale { get; set; }
        public DateTime? Date { get; set; }
        [Column("Cost", TypeName = "decimal(38,6)")]
        public decimal? Cost { get; set; }
        public int? Yr { get; set; }
        public int? Mt { get; set; }
        [Column("Tax", TypeName = "money")]
        public decimal? Tax { get; set; }
    }
}
