// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class RPT_CustomersPhoneOrdersResult
    {
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(50)]
        public string LastName { get; set; } = default!;
        [StringLength(50)]
        public string FirstName { get; set; } = default!;
        [StringLength(200)]
        public string? Address { get; set; }
        [StringLength(100)]
        public string? City { get; set; }
        [StringLength(100)]
        public string? State { get; set; }
        [StringLength(15)]
        public string? Zip { get; set; }
        [Column("Qty", TypeName = "decimal(38,2)")]
        public decimal? Qty { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(281)]
        public string? FullDescription { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [StringLength(50)]
        public string? ManufacturerPartNo { get; set; }
    }
}
