// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class RPT_TotalReturnsAndTendersResult
    {
        [StringLength(102)]
        public string? Name { get; set; }
        [Column("Total", TypeName = "decimal(38,3)")]
        public decimal Total { get; set; }
    }
}
