// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Rpt_CustomerLoyaltyResult
    {
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        [StringLength(101)]
        public string? CustomerName { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        public DateTime? DateCreated { get; set; }
        [Column("Points", TypeName = "decimal(18,2)")]
        public decimal? Points { get; set; }
        [Column("AvailPoints", TypeName = "decimal(18,2)")]
        public decimal? AvailPoints { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
    }
}
