// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SageItem
{
    public string? ASKPRICE { get; set; }

    public string? AVG_COST { get; set; }

    public string? BRAND { get; set; }

    public string? C_PAK_BULK { get; set; }

    public string? CHARGEIT { get; set; }

    public string? CIFSALEIS { get; set; }

    public string? CLASS { get; set; }

    public string? CLOSE0 { get; set; }

    public string? CMAX { get; set; }

    public string? CQTY { get; set; }

    public string? CTILL { get; set; }

    public string? DESC { get; set; }

    public string? DISC { get; set; }

    public string? FS { get; set; }

    public string? INVTAKEN { get; set; }

    public string? Item { get; set; }

    public string? ITEMID { get; set; }

    public string? KEEPINV { get; set; }

    public string? L_1S { get; set; }

    public string? L_C { get; set; }

    public string? L_R { get; set; }

    public string? L_S { get; set; }

    public string? LAST_COST { get; set; }

    public string? LASTDORD { get; set; }

    public string? LASTQORD { get; set; }

    public string? LASTSOLD { get; set; }

    public string? MAN { get; set; }

    public string? MINS { get; set; }

    public string? ONHAND { get; set; }

    public string? ONORD { get; set; }

    public string? PACK { get; set; }

    public string? PCASE { get; set; }

    public string? PCHG { get; set; }

    public string? PLAB { get; set; }

    public string? PR_RAMT { get; set; }

    public string? PR_RQTY { get; set; }

    public string? PR_SAMT { get; set; }

    public string? PR_SQTY { get; set; }

    public string? PRICE { get; set; }

    public string? R_PAK_BULK { get; set; }

    public string? RDESC { get; set; }

    public string? S_PAK_BULK { get; set; }

    public string? S1_PAK_BUL { get; set; }

    public string? SFROM { get; set; }

    public string? SIFSALEIS { get; set; }

    public string? SIZE { get; set; }

    public string? SMAX { get; set; }

    public string? SPRICE { get; set; }

    public string? SQTY { get; set; }

    public string? STILL { get; set; }

    public string? SUB { get; set; }

    public string? TARE { get; set; }

    public string? TAX { get; set; }

    public string? TAXINC { get; set; }

    public string? UNT { get; set; }

    public string? UPC { get; set; }
}