// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SaleReturnsTaxByStoreView
{
    public string? StoreName { get; set; }

    public DateTime? SaleDate { get; set; }

    public decimal Tax { get; set; }

    public decimal Sale { get; set; }

    public decimal Returns { get; set; }

    public decimal Discount { get; set; }

    public decimal? GiftCardPurchase { get; set; }

    public string? StoreNumber { get; set; }

    public decimal? AVGCost { get; set; }
}