// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class saleDetail
{
    public string? CustomerFName { get; set; }

    public string? CustomerLName { get; set; }

    public string? Street { get; set; }

    public string? State { get; set; }

    public string? PhonNumber { get; set; }

    public string? ShipToName { get; set; }

    public string? ShipToStreet { get; set; }

    public string? ShipToState { get; set; }

    public string? ShipToState1 { get; set; }

    public string? ShipToPhonNumber { get; set; }

    public decimal? TotalSale { get; set; }

    public decimal? TotalTax { get; set; }

    public decimal? TotalDiscount { get; set; }
}