// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SalesIncentive
{
    public Guid SalesIncentiveID { get; set; }

    public Guid ItemMainID { get; set; }

    public decimal? IncentiveValuePercent { get; set; }

    public decimal? IncentiveValueAmount { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public int? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserCreated { get; set; }

    public Guid? UserModified { get; set; }

    public Guid? SalesIncentiveHeaderID { get; set; }

    public virtual SalesIncentiveHeader? SalesIncentiveHeader { get; set; }
}