// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ScheduleReport
{
    public int ID { get; set; }

    public string? ReportName { get; set; }

    public string? Subject { get; set; }

    public string? Emails { get; set; }

    public string? ReportFilter { get; set; }

    public string? ReportLayout { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public int? Status { get; set; }

    public string? ReportFile { get; set; }

    public int TaskID { get; set; }

    public bool? IsReport { get; set; }

    public Guid? StoreID { get; set; }

    public string? DailyInterval { get; set; }

    public string? IntervalType { get; set; }

    public int? MonthlyInterval { get; set; }

    public DateTime? NextExecute { get; set; }

    public DateTime? StartTime { get; set; }

    public string? WeeklyInterval { get; set; }

    public virtual TaskSchedule Task { get; set; } = null!;
}