// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SDAC_Picture
{
    public string? Name { get; set; }

    public int UID { get; set; }

    public byte[]? Picture { get; set; }
}