// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SDAC_Long_char
{
    public int Code { get; set; }

    public string? Title { get; set; }

    public string? Value { get; set; }
}