// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Sdac_Loaded
{
    public int? Code { get; set; }

    public int? Num { get; set; }

    public double? Num1 { get; set; }

    public string? Str { get; set; }

    public DateTime? Dat { get; set; }
}