// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SetUpValuesView
{
    public int OptionID { get; set; }

    public short? CategoryID { get; set; }

    public Guid StoreID { get; set; }

    public string OptionName { get; set; } = null!;

    public string? OptionValue { get; set; }

    public string? OptionValueHe { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public bool? IsDefault { get; set; }

    public string? Description { get; set; }

    public int? FeildType { get; set; }
}