// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ShipVium
{
    public Guid ShipViaID { get; set; }

    public string? ShipViaName { get; set; }

    public decimal? ShipViaCost { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}