// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_BillTableToPayResult
    {
        public Guid BillID { get; set; }
        [StringLength(50)]
        public string? BillNo { get; set; }
        public Guid? SupplierID { get; set; }
        [Column("Discount", TypeName = "decimal(18,3)")]
        public decimal? Discount { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [Column("AmountPay", TypeName = "money")]
        public decimal? AmountPay { get; set; }
        public DateTime? BillDate { get; set; }
        public DateTime? BillDue { get; set; }
        public Guid? PersonGet { get; set; }
        public Guid? TermsID { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public bool? Taxable { get; set; }
        [Column("TaxRate", TypeName = "decimal(19,4)")]
        public decimal? TaxRate { get; set; }
        [Column("TaxAmount", TypeName = "money")]
        public decimal? TaxAmount { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
