// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_BillsForEditPaymentResult
    {
        public Guid? BillID { get; set; }
        [StringLength(50)]
        public string? BillNo { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [Column("AmountPay", TypeName = "money")]
        public decimal? AmountPay { get; set; }
        [Column("Terms Discount(%)", TypeName = "decimal(6,3)")]
        public decimal TermsDiscount { get; set; }
        [Column("Balance", TypeName = "decimal(32,11)")]
        public decimal? Balance { get; set; }
        [Column("ApplyAmount", TypeName = "money")]
        public decimal ApplyAmount { get; set; }
        public DateTime? BillDate { get; set; }
        public bool? Apply { get; set; }
    }
}
