// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_DeliveryDetailsTodayViewResult
    {
        public Guid? TransactionID { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public int? Cases { get; set; }
        public int? Box { get; set; }
        [StringLength(50)]
        public string? Shift { get; set; }
        public string? Note { get; set; }
        public DateTime? ScheduledDate { get; set; }
        [StringLength(50)]
        public string? PhoneType { get; set; }
        [StringLength(50)]
        public string? StatusType { get; set; }
        [StringLength(50)]
        public string? PaidString { get; set; }
        public int? Status { get; set; }
        public DateTime? DateModified { get; set; }
    }
}
