// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_DiscountDepartmentPOSResult
    {
        public Guid? DepartmentID { get; set; }
        public Guid? DiscountID { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid DiscountDepartmentID { get; set; }
        public short? Status { get; set; }
    }
}
