// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_Department_NPGS_Email_ReportResult
    {
        [StringLength(250)]
        public string Name { get; set; } = default!;
        public int? Qty { get; set; }
        [Column("Ext Cost")]
        [StringLength(26)]
        public string? ExtCost { get; set; }
        [Column("Total After Discount")]
        [StringLength(26)]
        public string? TotalAfterDiscount { get; set; }
        [StringLength(6)]
        public string? Margin { get; set; }
        [StringLength(26)]
        public string? Profit { get; set; }
    }
}
