// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class sp_FinishOrderOnHoldResult
    {
        [StringLength(50)]
        public string? OrderNo { get; set; }
        public DateTime? OrderDate { get; set; }
        [StringLength(101)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? FirstName { get; set; }
        [StringLength(50)]
        public string? LastName { get; set; }
        [StringLength(100)]
        public string? PhoneNo { get; set; }
        [StringLength(100)]
        public string? Cell { get; set; }
        [StringLength(200)]
        public string? Street1 { get; set; }
        [StringLength(50)]
        public string? Street2 { get; set; }
        [StringLength(100)]
        public string? City { get; set; }
        [StringLength(100)]
        public string? State { get; set; }
        [StringLength(15)]
        public string? Zip { get; set; }
        [StringLength(50)]
        public string? Country { get; set; }
        public int? PhoneOrderStatus { get; set; }
        [StringLength(50)]
        public string? OrderStatus { get; set; }
        public Guid? TakeByID { get; set; }
        [StringLength(50)]
        public string? TakenBy { get; set; }
        public Guid? UserCreated { get; set; }
        [StringLength(50)]
        public string? CreatedBy { get; set; }
        [Column("Qty", TypeName = "decimal(19,2)")]
        public decimal? Qty { get; set; }
        [StringLength(469)]
        public string Address { get; set; } = default!;
        [StringLength(1)]
        public string Note { get; set; } = default!;
        [StringLength(1)]
        public string Zone { get; set; } = default!;
        public int TotalItems { get; set; }
        public int OrderPriority { get; set; }
    }
}
