// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPrintInvoiceEntryViewResult
    {
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("UOMPrice", TypeName = "money")]
        public decimal? UOMPrice { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [StringLength(1)]
        public string Description { get; set; } = default!;
        [StringLength(50)]
        public string? ItemCode { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        [Column("DiscountPerc", TypeName = "decimal(19,3)")]
        public decimal? DiscountPerc { get; set; }
        public bool? Taxable { get; set; }
        [StringLength(50)]
        public string? Note { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [Column("Cs/Pc/Ds")]
        [StringLength(50)]
        public string? CsPcDs { get; set; }
        public Guid? TransactionID { get; set; }
        public int? Sort { get; set; }
    }
}
