// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPayOutViewResult
    {
        public Guid PayOutID { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(4000)]
        public string? Reason { get; set; }
        public DateTime? PayOutDate { get; set; }
        [StringLength(64)]
        public string? PayoutTime { get; set; }
        public Guid? RegisterID { get; set; }
        public Guid? ChasierID { get; set; }
        public Guid? BatchID { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(50)]
        public string? RegisterNo { get; set; }
        [StringLength(50)]
        public string? Cashier { get; set; }
        [StringLength(50)]
        public string? BatchNo { get; set; }
        [StringLength(1)]
        public string UserAutherized { get; set; } = default!;
        [StringLength(50)]
        public string? StoreName { get; set; }
        public Guid? StoreID { get; set; }
    }
}
