// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetItemStoreDetailsByIDResult
    {
        [StringLength(250)]
        public string? Name { get; set; }
        [Column("OnHand", TypeName = "decimal(19,3)")]
        public decimal? OnHand { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [Column("price", TypeName = "decimal(18,2)")]
        public decimal? price { get; set; }
        public Guid ItemID { get; set; }
    }
}
