// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetAlterationResult
    {
        public int AlterationID { get; set; }
        [StringLength(101)]
        public string? SlotNo { get; set; }
        [StringLength(11)]
        public string? Status { get; set; }
        public DateTime? SaleDate { get; set; }
        public DateTime? ExpectedDate { get; set; }
        [StringLength(2147483647)]
        public string? ExtraInfo { get; set; }
        [StringLength(20)]
        public string? AlterationNo { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        [StringLength(250)]
        public string? ItemName { get; set; }
        [StringLength(50)]
        public string? UPC { get; set; }
        [StringLength(50)]
        public string? ItemCode { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(102)]
        public string Name { get; set; } = default!;
        public Guid? StoreID { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        [StringLength(200)]
        public string? Address { get; set; }
        [StringLength(217)]
        public string? CityStateAndZip { get; set; }
        [StringLength(100)]
        public string? Phone { get; set; }
        public Guid? TransactionID { get; set; }
        public Guid? TransactionEntryID { get; set; }
        public DateTime? ReadyDate { get; set; }
        public DateTime? ClosedDate { get; set; }
        [Column("BalanceDoe", TypeName = "money")]
        public decimal BalanceDoe { get; set; }
        public int? ETA { get; set; }
    }
}
