// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPrintInvoiceViewResult
    {
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public Guid? ShipVia { get; set; }
        [StringLength(4000)]
        public string? PONo { get; set; }
        public Guid TransactionID { get; set; }
        [Column("Tax", TypeName = "money")]
        public decimal? Tax { get; set; }
        [StringLength(50)]
        public string? TaxType { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        [StringLength(100)]
        public string? PhoneNumber1 { get; set; }
        [StringLength(50)]
        public string? aName { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        [StringLength(30)]
        public string? StartSaleTime { get; set; }
        [StringLength(50)]
        public string? FaxNumber { get; set; }
        [StringLength(102)]
        public string? Name { get; set; }
        [StringLength(523)]
        public string AllDetails { get; set; } = default!;
        [StringLength(4000)]
        public string? Note { get; set; }
    }
}
