// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetSupplierAddressViewResult
    {
        public Guid AddressID { get; set; }
        [StringLength(50)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? Line1 { get; set; }
        [StringLength(50)]
        public string? Line2 { get; set; }
        [StringLength(20)]
        public string? Quarter { get; set; }
        [StringLength(20)]
        public string? City { get; set; }
        [StringLength(50)]
        public string? State { get; set; }
        [StringLength(15)]
        public string? Zip { get; set; }
        [StringLength(15)]
        public string? Country { get; set; }
        public int AddressType { get; set; }
        [StringLength(20)]
        public string? CCRT { get; set; }
        [StringLength(20)]
        public string? PhoneNumber1 { get; set; }
        [StringLength(20)]
        public string? Ext1 { get; set; }
        [StringLength(20)]
        public string? PhoneNumber2 { get; set; }
        [StringLength(20)]
        public string? PhoneNumber3 { get; set; }
        [StringLength(20)]
        public string? Ext2 { get; set; }
        public short? SortOrder { get; set; }
        public short? Status { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        public Guid? UserCreated { get; set; }
        [StringLength(20)]
        public string? Ext3 { get; set; }
        [StringLength(20)]
        public string? cellphone { get; set; }
    }
}
