// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPayToBillResult
    {
        [StringLength(50)]
        public string? BillNo { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
    }
}
