// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetDaySalesItemResult
    {
        public DateTime? StartSaleTime { get; set; }
        [StringLength(64)]
        public string? Time { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        [Column("Cost", TypeName = "decimal(38,6)")]
        public decimal Cost { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public Guid TransactionID { get; set; }
        [Column("Profit", TypeName = "decimal(38,6)")]
        public decimal? Profit { get; set; }
    }
}
