// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTendersCashierByStationResult
    {
        [StringLength(50)]
        public string? TenderName { get; set; }
        [StringLength(50)]
        public string? RegisterNo { get; set; }
        public Guid? RegisterID { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(4)]
        public string TenderType { get; set; } = default!;
        [StringLength(50)]
        public string? CreditName { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public Guid TransactionID { get; set; }
    }
}
