// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTendersByBatchIDResult
    {
        public int Tender { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        public Guid? BatchID { get; set; }
        public int TenderID { get; set; }
        public int? TenderGroup { get; set; }
        public short? SortOrder { get; set; }
        public int? TenderType { get; set; }
        [StringLength(50)]
        public string? TenderName { get; set; }
        [StringLength(50)]
        public string? TenderNameHe { get; set; }
        [StringLength(4000)]
        public string? TenderDescription { get; set; }
        public bool? RequiresCustomer { get; set; }
        public bool? AllowDiscount { get; set; }
        public bool? FillByPressEnter { get; set; }
        public bool? OpenDrawer { get; set; }
        public int? MinimumAmount { get; set; }
        public bool? IsSystem { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        public bool? GivePoints { get; set; }
        public bool? OverTender { get; set; }
        public bool? AllowMinus { get; set; }
        public bool? NoChange { get; set; }
        public bool? ShowOnPhoneOrder { get; set; }
        public bool? ShowOnShift { get; set; }
        public bool? ShowInCheckout { get; set; }
    }
}
