// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetZipCodesViewResult
    {
        [StringLength(8000)]
        public string? ZipCode { get; set; }
        [StringLength(4000)]
        public string? City { get; set; }
        [StringLength(50)]
        public string? StateID { get; set; }
    }
}
