// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetRptZOutTenderDetailsResult
    {
        public Guid? BatchID { get; set; }
        public int TenderID { get; set; }
        [StringLength(50)]
        public string? TenderName { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [Column("ref#")]
        [StringLength(50)]
        public string? @ref { get; set; }
        [StringLength(102)]
        public string Name { get; set; } = default!;
    }
}
