// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTransactionsResult
    {
        public Guid TransactionID { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public int TransactionType { get; set; }
        public bool? RegisterTransaction { get; set; }
        public Guid? BatchID { get; set; }
        public Guid? StoreID { get; set; }
        public Guid? CustomerID { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column("Credit", TypeName = "money")]
        public decimal? Credit { get; set; }
        public DateTime? StartSaleTime { get; set; }
        public DateTime? EndSaleTime { get; set; }
        public DateTime? DueDate { get; set; }
        [Column("Tax", TypeName = "money")]
        public decimal? Tax { get; set; }
        [StringLength(50)]
        public string? TaxType { get; set; }
        public Guid? TaxID { get; set; }
        [Column("TaxRate", TypeName = "decimal(19,4)")]
        public decimal? TaxRate { get; set; }
        public Guid? ShipTo { get; set; }
        public Guid? ShipVia { get; set; }
        [StringLength(50)]
        public string? PONo { get; set; }
        public Guid? RepID { get; set; }
        public Guid? TermsID { get; set; }
        public bool? PhoneOrder { get; set; }
        public bool? ToPrint { get; set; }
        public bool? ToEmail { get; set; }
        public Guid? CustomerMessage { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("LeftDebit", TypeName = "money")]
        public decimal? LeftDebit { get; set; }
        [Column("Balance", TypeName = "money")]
        public decimal? Balance { get; set; }
        [StringLength(64)]
        public string? EndTime { get; set; }
        [StringLength(64)]
        public string? StartTime { get; set; }
        [StringLength(102)]
        public string CustomerName { get; set; } = default!;
        [Column("AppliedAmount", TypeName = "money")]
        public decimal? AppliedAmount { get; set; }
        [Column("Freight", TypeName = "money")]
        public decimal? Freight { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        public Guid? RegisterID { get; set; }
        [StringLength(4000)]
        public string? VoidReason { get; set; }
        public Guid? ResellerID { get; set; }
        [StringLength(1)]
        public string ResellerName { get; set; } = default!;
        [Column("SubTotal", TypeName = "money")]
        public decimal? SubTotal { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        public DateTime? DeliveryDate { get; set; }
        [StringLength(50)]
        public string? TrackNo { get; set; }
        [Column("Rounding", TypeName = "money")]
        public decimal? Rounding { get; set; }
        [Column("CurrBalance", TypeName = "money")]
        public decimal? CurrBalance { get; set; }
        [StringLength(50)]
        public string? User { get; set; }
        [StringLength(50)]
        public string? SaleAssociate { get; set; }
    }
}
