// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetReturnEntriesResult
    {
        public Guid ReturnToVenderEntryID { get; set; }
        public Guid? ReturnToVenderID { get; set; }
        public Guid? ItemStoreNo { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("UOMQty", TypeName = "decimal(18,0)")]
        public decimal? UOMQty { get; set; }
        public int? UOMType { get; set; }
        [Column("ExtPrice", TypeName = "money")]
        public decimal? ExtPrice { get; set; }
        public bool? IsSpecialPrice { get; set; }
        public int? ReturnReason { get; set; }
        public bool? Taxable { get; set; }
        public Guid? LinkNo { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public Guid? ReceiveID { get; set; }
        public int? SortOrder { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("UOMPrice", TypeName = "decimal(38,6)")]
        public decimal? UOMPrice { get; set; }
    }
}
