// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetCreditViewResult
    {
        public Guid CreditID { get; set; }
        [StringLength(50)]
        public string? Name { get; set; }
        [StringLength(4000)]
        public string? Description { get; set; }
        public int? Days { get; set; }
        [Column("InterestRate", TypeName = "decimal(6,3)")]
        public decimal? InterestRate { get; set; }
        public bool? CreditType { get; set; }
        public int? NetDue { get; set; }
        public int? DayInMonth { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("InterestRate2", TypeName = "decimal(18,0)")]
        public decimal? InterestRate2 { get; set; }
        public bool? CreditType2 { get; set; }
    }
}
