// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetRptZOutResult
    {
        public Guid BatchID { get; set; }
        [StringLength(50)]
        public string? BatchNumber { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        public int? TransactionCount { get; set; }
        [Column("TotalSales", TypeName = "money")]
        public decimal TotalSales { get; set; }
        [Column("TotalReturn", TypeName = "money")]
        public decimal? TotalReturn { get; set; }
        [Column("PayBalance", TypeName = "money")]
        public decimal PayBalance { get; set; }
        [Column("Tax", TypeName = "money")]
        public decimal Tax { get; set; }
        [Column("PayOut", TypeName = "money")]
        public decimal PayOut { get; set; }
        public int? CustomerCount { get; set; }
        public int? CancelSale { get; set; }
        public int? VoiidItem { get; set; }
        public int? OpenDrawer { get; set; }
        [Column("TotalDiscount", TypeName = "money")]
        public decimal? TotalDiscount { get; set; }
    }
}
