// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetMovementsViewResult
    {
        public int ActionType { get; set; }
        [StringLength(3)]
        public string MovementType { get; set; } = default!;
        [StringLength(50)]
        public string? Details { get; set; }
        [StringLength(8)]
        public string? DebitAccount { get; set; }
        [StringLength(8)]
        public string? CreditAccount { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
