// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetReceiveEntryViewResult
    {
        public Guid ReceiveEntryID { get; set; }
        public Guid? ReceiveNo { get; set; }
        public Guid? ItemStoreNo { get; set; }
        public Guid? PurchaseOrderEntryNo { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("Qty", TypeName = "decimal(18,2)")]
        public decimal? Qty { get; set; }
        [Column("UOMQty", TypeName = "decimal(18,2)")]
        public decimal? UOMQty { get; set; }
        public int? UOMType { get; set; }
        [Column("ExtPrice", TypeName = "money")]
        public decimal? ExtPrice { get; set; }
        public bool? IsSpecialPrice { get; set; }
        public bool? ForApprove { get; set; }
        public Guid? LinkNo { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public int? SortOrder { get; set; }
        public bool? Taxable { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("ListPrice", TypeName = "money")]
        public decimal? ListPrice { get; set; }
        [Column("NetCost", TypeName = "money")]
        public decimal? NetCost { get; set; }
        [StringLength(50)]
        public string? Brand { get; set; }
        [Column("UOMPrice", TypeName = "decimal(38,6)")]
        public decimal? UOMPrice { get; set; }
        [Column("RealCost", TypeName = "decimal(38,6)")]
        public decimal? RealCost { get; set; }
        public Guid? PurchaseOrderNo { get; set; }
        [Column("CaseCost", TypeName = "money")]
        public decimal? CaseCost { get; set; }
        [Column("PcCost", TypeName = "money")]
        public decimal? PcCost { get; set; }
        [Column("CaseQty", TypeName = "decimal(18,1)")]
        public decimal? CaseQty { get; set; }
        [Column("LastNetCost", TypeName = "money")]
        public decimal? LastNetCost { get; set; }
        public byte? PriceStatus { get; set; }
        [Column("RetailUnitPrice", TypeName = "money")]
        public decimal? RetailUnitPrice { get; set; }
        [StringLength(100)]
        public string? SaleSpecialPrice { get; set; }
        [Column("RetailPrice", TypeName = "money")]
        public decimal RetailPrice { get; set; }
        [Column("Markup", TypeName = "money")]
        public decimal? Markup { get; set; }
        [Column("Margin", TypeName = "money")]
        public decimal? Margin { get; set; }
        [StringLength(250)]
        public string? ItemName { get; set; }
        [StringLength(50)]
        public string? ItemUPC { get; set; }
        [StringLength(50)]
        public string? ItemModelNo { get; set; }
        public Guid ItemID { get; set; }
        public int PriceChange { get; set; }
        [StringLength(50)]
        public string? SupplierCode { get; set; }
        [StringLength(120)]
        public string? Size { get; set; }
        [Column("Discount", TypeName = "money")]
        public decimal? Discount { get; set; }
        [StringLength(50)]
        public string? Department { get; set; }
        [StringLength(1)]
        public string ParentCode { get; set; } = default!;
        [Column("RegSPPrice", TypeName = "money")]
        public decimal? RegSPPrice { get; set; }
        [Column("CaseSPPrice", TypeName = "money")]
        public decimal? CaseSPPrice { get; set; }
        public int? RegPkgPrice { get; set; }
        [Column("Reg SP Price Markup")]
        public int? RegSPPriceMarkup { get; set; }
        [Column("Reg SP Price Margin")]
        public int? RegSPPriceMargin { get; set; }
        [Column("Pkg Price Markup")]
        public int? PkgPriceMarkup { get; set; }
        [Column("Pkg Price Margin")]
        public int? PkgPriceMargin { get; set; }
        [Column("SP Markup", TypeName = "money")]
        public decimal SPMarkup { get; set; }
        [Column("SP Margin", TypeName = "money")]
        public decimal? SPMargin { get; set; }
        [StringLength(50)]
        public string? StyleNo { get; set; }
        [StringLength(50)]
        public string? Matrix1 { get; set; }
        [StringLength(50)]
        public string? Matrix2 { get; set; }
        [StringLength(250)]
        public string? ParentName { get; set; }
        [StringLength(50)]
        public string BinLocation { get; set; } = default!;
        [StringLength(2147483647)]
        public string? ItemAlias { get; set; }
        public DateTime? SPFrom { get; set; }
        public DateTime? SPTo { get; set; }
    }
}
