// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetAccountViewResult
    {
        public Guid AccountID { get; set; }
        [StringLength(50)]
        public string? AccountName { get; set; }
        [StringLength(4000)]
        public string? AccountDescription { get; set; }
        public short? Status { get; set; }
    }
}
