// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetEntryByOrderIDResult
    {
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("Qty", TypeName = "decimal(38,3)")]
        public decimal? Qty { get; set; }
        [Column("UOMPrice", TypeName = "decimal(38,6)")]
        public decimal? UOMPrice { get; set; }
        [StringLength(50)]
        public string? StyleNo { get; set; }
        [StringLength(50)]
        public string? UOM { get; set; }
        [Column("ExtPrice", TypeName = "money")]
        public decimal ExtPrice { get; set; }
        public Guid ID { get; set; }
        public Guid? TermsNo { get; set; }
        public int CaseQty { get; set; }
        public Guid PONO { get; set; }
        public Guid? ItemStoreID { get; set; }
        [StringLength(50)]
        public string? ParentCode { get; set; }
        [StringLength(50)]
        public string ItemCode { get; set; } = default!;
        [StringLength(50)]
        public string? SupplierItemCode { get; set; }
        [StringLength(50)]
        public string? Color { get; set; }
        [StringLength(50)]
        public string? Size { get; set; }
    }
}
