// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetExtraChargeViewResult
    {
        public Guid ExtraChargeID { get; set; }
        [StringLength(50)]
        public string? ExtraChargeName { get; set; }
        [StringLength(4000)]
        public string? ExtraChargeDescription { get; set; }
        public int ExtraChargeType { get; set; }
        [Column("ExtraChargeQty", TypeName = "decimal(18,2)")]
        public decimal? ExtraChargeQty { get; set; }
        public bool? IsExtraChargeIncluded { get; set; }
        public Guid? ExtraChargeAccount { get; set; }
        public Guid ItemStoreNo { get; set; }
        public short? Status { get; set; }
        public DateTime? DateModified { get; set; }
    }
}
