// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetEntryBySupplierIDResult
    {
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? ItemCode { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("UOMPrice", TypeName = "money")]
        public decimal? UOMPrice { get; set; }
        [Column("UOMType", TypeName = "money")]
        public decimal? UOMType { get; set; }
        [StringLength(50)]
        public string? UOM { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        public Guid? ItemStoreID { get; set; }
    }
}
