// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetSupplierView_HandHeldResult
    {
        public Guid SupplierID { get; set; }
        [StringLength(50)]
        public string? SupplierNo { get; set; }
        [StringLength(50)]
        public string? Name { get; set; }
    }
}
