// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetRepUsageResult
    {
        [StringLength(50)]
        public string? ReportName { get; set; }
        [StringLength(4000)]
        public string? ReportDescription { get; set; }
        [StringLength(100)]
        public string? Icon { get; set; }
        public int? count { get; set; }
    }
}
