// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetNumberSettingsViewResult
    {
        [StringLength(50)]
        public string? StoreSymbol { get; set; }
        [StringLength(50)]
        public string? TableName { get; set; }
        public long? SeqNumber { get; set; }
        public long? StartNum { get; set; }
        [StringLength(50)]
        public string? Desc { get; set; }
        public Guid? StoreID { get; set; }
        [StringLength(50)]
        public string? TableNameHe { get; set; }
    }
}
