// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetMatrixColumnViewResult
    {
        public Guid MatrixColumnID { get; set; }
        [StringLength(50)]
        public string ColumnName { get; set; } = default!;
        public Guid MatrixNo { get; set; }
        public int? SortOrder { get; set; }
        public short? Status { get; set; }
        public DateTime? DateModified { get; set; }
    }
}
