// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetLastTransactionByItemResult
    {
        public Guid TransactionID { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public DateTime? SaleTime { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
    }
}
