// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetSalesIncentiveSummeryResult
    {
        [StringLength(50)]
        public string? UserName { get; set; }
        [Column("SumAmount", TypeName = "money")]
        public decimal? SumAmount { get; set; }
        [Column("SumSale", TypeName = "decimal(38,0)")]
        public decimal? SumSale { get; set; }
        [Column("SumPercent", TypeName = "decimal(38,21)")]
        public decimal? SumPercent { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
    }
}
