// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetSalesByStoreResult
    {
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? Matrix1 { get; set; }
        [StringLength(50)]
        public string? Matrix2 { get; set; }
        [Column("Qty Sold In Williamsburg", TypeName = "decimal(38,3)")]
        public decimal? QtySoldInWilliamsburg { get; set; }
        [Column("Qty Sold In KJ", TypeName = "decimal(38,3)")]
        public decimal? QtySoldInKJ { get; set; }
        [Column("Qty Sold In Off Casual", TypeName = "decimal(38,3)")]
        public decimal? QtySoldInOffCasual { get; set; }
    }
}
