// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetMatrixValuesViewResult
    {
        public Guid MatrixValueID { get; set; }
        [StringLength(50)]
        public string DisplayValue { get; set; } = default!;
        public int? SortOrder { get; set; }
        public Guid MatrixColumnNo { get; set; }
        public short? Status { get; set; }
        public DateTime? DateModified { get; set; }
    }
}
