// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetCardDetailByTransactionIDResult
    {
        public Guid TransactionID { get; set; }
        [StringLength(200)]
        public string? CardNumber { get; set; }
        [StringLength(200)]
        public string? HolderName { get; set; }
        public short? Status { get; set; }
    }
}
