// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetSupplierContactViewResult
    {
        public Guid SuplierContactID { get; set; }
        public Guid? SupplierNo { get; set; }
        public Guid? ContactNo { get; set; }
        [StringLength(20)]
        public string? JobTitle { get; set; }
        [StringLength(50)]
        public string? Department { get; set; }
        [StringLength(4000)]
        public string? Description { get; set; }
        public short? SortOrder { get; set; }
        public short? Status { get; set; }
        public DateTime? DateModified { get; set; }
    }
}
