// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetDailyHourSalesResult
    {
        [StringLength(50)]
        public string? StoreName { get; set; }
        [StringLength(30)]
        public string? WeekDay { get; set; }
        [StringLength(50)]
        public string? Hour { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column("Credit", TypeName = "money")]
        public decimal? Credit { get; set; }
        [Column("Balance", TypeName = "money")]
        public decimal? Balance { get; set; }
        public int? CountTransaction { get; set; }
        public int? Registers { get; set; }
        public double? SalePrec { get; set; }
        public int? Customers { get; set; }
        public int? TransactionWithCustomer { get; set; }
        public double? CustomerPrec { get; set; }
        [Column("CustomerDebit", TypeName = "money")]
        public decimal? CustomerDebit { get; set; }
        [Column("Items", TypeName = "decimal(38,3)")]
        public decimal? Items { get; set; }
    }
}
