// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetSalesIncentiveHeaderViewResult
    {
        public Guid SalesIncentiveHeaderID { get; set; }
        [StringLength(50)]
        public string? Name { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        [Column("IncentiveAmount", TypeName = "money")]
        public decimal? IncentiveAmount { get; set; }
        [Column("IncentivePercent", TypeName = "decimal(18,2)")]
        public decimal? IncentivePercent { get; set; }
        public int? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserCreated { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
    }
}
