// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetCustomerComparisonDatesResult
    {
        [Column("CurentQty", TypeName = "decimal(38,3)")]
        public decimal CurentQty { get; set; }
        [Column("CurentSales", TypeName = "decimal(38,3)")]
        public decimal CurentSales { get; set; }
        [Column("ComparisonQty", TypeName = "decimal(38,3)")]
        public decimal ComparisonQty { get; set; }
        [Column("ComparisonPeriod", TypeName = "decimal(38,3)")]
        public decimal ComparisonPeriod { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(101)]
        public string CustomerName { get; set; } = default!;
        [StringLength(50)]
        public string? Department { get; set; }
        [Column("QtyChange", TypeName = "decimal(38,3)")]
        public decimal? QtyChange { get; set; }
        [Column("DolarChange", TypeName = "decimal(38,3)")]
        public decimal? DolarChange { get; set; }
    }
}
