// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetGiftViewResult
    {
        public Guid GiftID { get; set; }
        [StringLength(50)]
        public string? GiftNumber { get; set; }
        public Guid? CustomerID { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        public int? GiftType { get; set; }
        public DateTime? GiftDate { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(102)]
        public string CustomerName { get; set; } = default!;
        [StringLength(50)]
        public string? CustomerNo { get; set; }
    }
}
