// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetMatrixChildsBasicResult
    {
        public Guid ItemID { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? Matrix1 { get; set; }
        [StringLength(50)]
        public string? Matrix2 { get; set; }
        [StringLength(50)]
        public string? Matrix3 { get; set; }
        [StringLength(50)]
        public string? Matrix4 { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        public int Field { get; set; }
        public Guid? ItemStoreID { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("OnHand", TypeName = "decimal(19,3)")]
        public decimal? OnHand { get; set; }
        [StringLength(50)]
        public string? StyleNo { get; set; }
        [Column("NetCost", TypeName = "money")]
        public decimal? NetCost { get; set; }
        [Column("SpecialCost", TypeName = "money")]
        public decimal? SpecialCost { get; set; }
        [Column("Estimatedcost", TypeName = "money")]
        public decimal? Estimatedcost { get; set; }
        public Guid? LinkNo { get; set; }
    }
}
