// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetWorkOrdersResult
    {
        [StringLength(30)]
        public string? EndTime { get; set; }
        [StringLength(30)]
        public string? StartTime { get; set; }
        [StringLength(102)]
        public string? CustomerName { get; set; }
        public Guid WorkOrderID { get; set; }
        public DateTime? ActiveDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        [StringLength(50)]
        public string? WONo { get; set; }
        public Guid? StoreID { get; set; }
        public Guid? CustomerID { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        public DateTime? StartSaleTime { get; set; }
        public DateTime? EndSaleTime { get; set; }
        [Column("Tax", TypeName = "money")]
        public decimal? Tax { get; set; }
        [StringLength(50)]
        public string? TaxType { get; set; }
        [Column("TaxRate", TypeName = "decimal(19,4)")]
        public decimal? TaxRate { get; set; }
        public Guid? TaxID { get; set; }
        public Guid? ShipTo { get; set; }
        public Guid? ShipVia { get; set; }
        public short? Pay_PaymentType { get; set; }
        [StringLength(50)]
        public string? Pay_CardNumber { get; set; }
        [Column("Freight", TypeName = "money")]
        public decimal? Freight { get; set; }
        [StringLength(50)]
        public string? Pay_NameOnCard { get; set; }
        public DateTime? Pay_ExpirationDate { get; set; }
        [StringLength(50)]
        public string? Pay_SecurityCode { get; set; }
        public bool? IsWeb { get; set; }
        public short? WOStatus { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public Guid? ResellerID { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(50)]
        public string? ResellerName { get; set; }
        public int? Pay_TenderType { get; set; }
    }
}
