// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetOneReceiveResult
    {
        public Guid ReceiveID { get; set; }
        [StringLength(50)]
        public string? PackingSlipNo { get; set; }
        public Guid? StoreID { get; set; }
        public Guid? SupplierNo { get; set; }
        public Guid? BillID { get; set; }
        [Column("Freight", TypeName = "money")]
        public decimal? Freight { get; set; }
        [Column("Discount", TypeName = "decimal(18,3)")]
        public decimal? Discount { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        [Column("CurrBalance", TypeName = "money")]
        public decimal? CurrBalance { get; set; }
        public bool? IsDiscAmount { get; set; }
        [Column("DiscountSum", TypeName = "decimal(38,7)")]
        public decimal? DiscountSum { get; set; }
        [Column("EntriesSum", TypeName = "money")]
        public decimal? EntriesSum { get; set; }
        public DateTime? ReceiveOrderDate { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(50)]
        public string? BillNo { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [Column("AmountPay", TypeName = "money")]
        public decimal? AmountPay { get; set; }
        public DateTime? BillDate { get; set; }
        public int? ReceiveStatus { get; set; }
        [Column("Balance", TypeName = "money")]
        public decimal? Balance { get; set; }
        public Guid? TermsID { get; set; }
        public DateTime? StartSaleTime { get; set; }
        [StringLength(50)]
        public string? SupplierName { get; set; }
        [StringLength(50)]
        public string? SupplierCode { get; set; }
        [StringLength(101)]
        public string? SupplierAddress { get; set; }
        [StringLength(87)]
        public string? SupplierCSZ { get; set; }
        [StringLength(20)]
        public string? PhoneNumber1 { get; set; }
        [StringLength(20)]
        public string? Ext1 { get; set; }
        [StringLength(20)]
        public string? PhoneNumber2 { get; set; }
        [StringLength(20)]
        public string? PhoneNumber3 { get; set; }
        [StringLength(50)]
        public string? ContactName { get; set; }
        public DateTime? BillDue { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        [StringLength(50)]
        public string? AccountNo { get; set; }
        [Column("CustomsDuties", TypeName = "money")]
        public decimal? CustomsDuties { get; set; }
        [Column("OtherCharges", TypeName = "money")]
        public decimal? OtherCharges { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        [StringLength(500)]
        public string? PoNo { get; set; }
    }
}
