// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetWorkOrderDetailsViewResult
    {
        public Guid WorkOrderEntryID { get; set; }
        public Guid? WorkOrderID { get; set; }
        public Guid? ItemStoreID { get; set; }
        public short? Sort { get; set; }
        public bool? Taxable { get; set; }
        [Column("UOMQty", TypeName = "decimal(19,3)")]
        public decimal? UOMQty { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        public int? UOMType { get; set; }
        [StringLength(50)]
        public string? PriceExplanation { get; set; }
        public Guid? ParentTransactionEntry { get; set; }
        [StringLength(50)]
        public string? Note { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [Column("Total", TypeName = "decimal(38,6)")]
        public decimal? Total { get; set; }
        [Column("UOMPrice", TypeName = "decimal(38,6)")]
        public decimal? UOMPrice { get; set; }
    }
}
