// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetItemsByDepartmentResult
    {
        public Guid ItemID { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("OnOrder", TypeName = "decimal(19,3)")]
        public decimal OnOrder { get; set; }
        [Column("OnHand", TypeName = "decimal(19,3)")]
        public decimal? OnHand { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("ExtCost", TypeName = "decimal(38,6)")]
        public decimal? ExtCost { get; set; }
        public Guid? DepartmentID { get; set; }
        [StringLength(50)]
        public string? Department { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        [Column("ExtPrice", TypeName = "decimal(38,6)")]
        public decimal? ExtPrice { get; set; }
        [Column("Profit", TypeName = "decimal(38,6)")]
        public decimal? Profit { get; set; }
        [Column("Margin", TypeName = "money")]
        public decimal? Margin { get; set; }
        [Column("Markup", TypeName = "money")]
        public decimal? Markup { get; set; }
    }
}
