// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetCustomerTasksFilteredResult
    {
        public Guid TaskID { get; set; }
        public Guid? CustomerID { get; set; }
        public short? TaskType { get; set; }
        public DateTime? ScheduleDate { get; set; }
        public DateTime? TaskDate { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public short? Priority { get; set; }
        public short? Status { get; set; }
        [StringLength(50)]
        public string? ScheduleHour { get; set; }
        [StringLength(9)]
        public string? TaskStatusDesc { get; set; }
        public short? TaskStatus { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(102)]
        public string CustomerName { get; set; } = default!;
        [StringLength(50)]
        public string? TaskName { get; set; }
        [StringLength(200)]
        public string Address { get; set; } = default!;
        [StringLength(217)]
        public string CityStateAndZip { get; set; } = default!;
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(4000)]
        public string? Description { get; set; }
        [StringLength(50)]
        public string? CreateBy { get; set; }
        [Column("BalanceDoe", TypeName = "money")]
        public decimal BalanceDoe { get; set; }
    }
}
