// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPurchaseOrderEntryViewResult
    {
        public Guid PurchaseOrderEntryId { get; set; }
        public Guid PurchaseOrderNo { get; set; }
        public Guid? ItemNo { get; set; }
        [Column("QtyOrdered", TypeName = "decimal(19,3)")]
        public decimal? QtyOrdered { get; set; }
        [Column("PricePerUnit", TypeName = "money")]
        public decimal? PricePerUnit { get; set; }
        public int? UOMQty { get; set; }
        public int? UOMType { get; set; }
        [Column("ExtPrice", TypeName = "money")]
        public decimal ExtPrice { get; set; }
        public bool? IsSpecialPrice { get; set; }
        public Guid? LinkNo { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public int? SortOrder { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("UOMPrice", TypeName = "decimal(38,6)")]
        public decimal? UOMPrice { get; set; }
        [Column("OrderDeficit", TypeName = "decimal(38,3)")]
        public decimal? OrderDeficit { get; set; }
        [StringLength(250)]
        public string? ItemName { get; set; }
        [StringLength(50)]
        public string? UPC { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        public int CaseQty { get; set; }
        [Column("CaseCost", TypeName = "money")]
        public decimal? CaseCost { get; set; }
        public Guid ItemID { get; set; }
        [StringLength(50)]
        public string? ItemCode { get; set; }
        [StringLength(50)]
        public string? ParentCode { get; set; }
        [StringLength(50)]
        public string? Matrix1 { get; set; }
        [StringLength(50)]
        public string? Matrix2 { get; set; }
        [StringLength(250)]
        public string? ParentName { get; set; }
        [Column("ReceivedQty", TypeName = "decimal(38,3)")]
        public decimal? ReceivedQty { get; set; }
        [StringLength(50)]
        public string? StyleNo { get; set; }
        [Column("Supplier Item Code")]
        [StringLength(50)]
        public string? SupplierItemCode { get; set; }
        [Column("CostBeforeDis", TypeName = "money")]
        public decimal? CostBeforeDis { get; set; }
        [Column("EstimateCost", TypeName = "money")]
        public decimal? EstimateCost { get; set; }
        [Column("NetCost", TypeName = "money")]
        public decimal? NetCost { get; set; }
        [Column("SpecialCost", TypeName = "money")]
        public decimal? SpecialCost { get; set; }
        [StringLength(50)]
        public string? Brand { get; set; }
        [StringLength(50)]
        public string? SubDepart2 { get; set; }
        [StringLength(50)]
        public string? Department { get; set; }
        [Column("TotalDiscount", TypeName = "decimal(38,6)")]
        public decimal? TotalDiscount { get; set; }
        public Guid ItemStoreID { get; set; }
        [StringLength(120)]
        public string? Size { get; set; }
        [Column("OnHand", TypeName = "decimal(19,3)")]
        public decimal? OnHand { get; set; }
        [Column("RetailPrice", TypeName = "money")]
        public decimal RetailPrice { get; set; }
        [Column("Markup", TypeName = "money")]
        public decimal? Markup { get; set; }
    }
}
