// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetAdjustReportResult
    {
        [StringLength(50)]
        public string? Department { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [StringLength(50)]
        public string? UPC { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(120)]
        public string? Size { get; set; }
        [StringLength(50)]
        public string? Color { get; set; }
        [StringLength(50)]
        public string? Sizze { get; set; }
        public int? CaseQty { get; set; }
        [Column("Pc Cost", TypeName = "money")]
        public decimal? PcCost { get; set; }
        public int? OldOnHand { get; set; }
        public int? AddedQty { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        public int? NewOnHand { get; set; }
        [Column("PreviousExtCost", TypeName = "money")]
        public decimal? PreviousExtCost { get; set; }
        [Column("NewExtCost", TypeName = "money")]
        public decimal? NewExtCost { get; set; }
        [Column("ValueAdded", TypeName = "money")]
        public decimal? ValueAdded { get; set; }
    }
}
