// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPOReceiveResult
    {
        public Guid ReceiveID { get; set; }
        [StringLength(50)]
        public string? BillNo { get; set; }
        public DateTime? ReceiveOrderDate { get; set; }
        public Guid PurchaseOrderId { get; set; }
        [StringLength(50)]
        public string? PoNo { get; set; }
    }
}
