// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetReceiveEntryFromReceiveResult
    {
        public Guid ReceiveEntryID { get; set; }
        public Guid? ReceiveNo { get; set; }
        public Guid? ItemStoreNo { get; set; }
        public Guid? PurchaseOrderEntryNo { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("Qty", TypeName = "decimal(18,2)")]
        public decimal? Qty { get; set; }
        [Column("UOMQty", TypeName = "decimal(18,2)")]
        public decimal? UOMQty { get; set; }
        public int? UOMType { get; set; }
        [Column("ExtPrice", TypeName = "money")]
        public decimal? ExtPrice { get; set; }
        public bool? IsSpecialPrice { get; set; }
        public bool? ForApprove { get; set; }
        public Guid? LinkNo { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public int? SortOrder { get; set; }
        public bool? Taxable { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("ListPrice", TypeName = "money")]
        public decimal? ListPrice { get; set; }
        [Column("Margin", TypeName = "money")]
        public decimal? Margin { get; set; }
        [Column("Markup", TypeName = "money")]
        public decimal? Markup { get; set; }
        [Column("NetCost", TypeName = "money")]
        public decimal? NetCost { get; set; }
        [Column("CaseCost", TypeName = "money")]
        public decimal? CaseCost { get; set; }
        [Column("PcCost", TypeName = "money")]
        public decimal? PcCost { get; set; }
        [Column("CaseQty", TypeName = "decimal(18,1)")]
        public decimal? CaseQty { get; set; }
        public byte? PriceStatus { get; set; }
        [Column("LastNetCost", TypeName = "money")]
        public decimal? LastNetCost { get; set; }
        [Column("UOMPrice", TypeName = "money")]
        public decimal? UOMPrice { get; set; }
        [Column("EstimatedPrice", TypeName = "money")]
        public decimal? EstimatedPrice { get; set; }
        [Column("Discount", TypeName = "money")]
        public decimal? Discount { get; set; }
        public int? DiscountType { get; set; }
        [Column("NetPcCost", TypeName = "money")]
        public decimal? NetPcCost { get; set; }
        [StringLength(100)]
        public string? PackingSlipLineNo { get; set; }
    }
}
