// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetRegShiftsResult
    {
        public Guid RegShiftID { get; set; }
        [StringLength(50)]
        public string ShiftNO { get; set; } = default!;
        public DateTime? ShiftOpenDate { get; set; }
        [StringLength(9)]
        public string Status { get; set; } = default!;
        public DateTime? ShiftCloseDate { get; set; }
        [StringLength(50)]
        public string? RegisterNo { get; set; }
        [StringLength(50)]
        public string? CloseBy { get; set; }
        public int TransCount { get; set; }
        [Column("TotalExp", TypeName = "money")]
        public decimal? TotalExp { get; set; }
        [Column("TotalPick", TypeName = "money")]
        public decimal TotalPick { get; set; }
        [Column("Discrepancy", TypeName = "money")]
        public decimal? Discrepancy { get; set; }
    }
}
