// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPrintLabelsMatrixResult
    {
        public Guid? PrintLabelsID { get; set; }
        public Guid ItemStoreID { get; set; }
        public int Tag { get; set; }
        public int Status { get; set; }
        [StringLength(36)]
        public string UserCreated { get; set; } = default!;
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        public int Qty { get; set; }
        [Column("OnHand", TypeName = "decimal(19,3)")]
        public decimal? OnHand { get; set; }
    }
}
