// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetResellersCommissionsViewResult
    {
        public Guid CommissionID { get; set; }
        public Guid ResellerID { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        public DateTime? SentDate { get; set; }
        public DateTime? CheckDate { get; set; }
        [StringLength(50)]
        public string? CheckNo { get; set; }
        [StringLength(50)]
        public string? CheckBank { get; set; }
        [StringLength(50)]
        public string? CheckSubsidiary { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(102)]
        public string Name { get; set; } = default!;
        [StringLength(50)]
        public string? CompanyName { get; set; }
        [StringLength(50)]
        public string? Email { get; set; }
        [StringLength(50)]
        public string? Phone { get; set; }
        [StringLength(50)]
        public string? Address1 { get; set; }
    }
}
