// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetOneRequestTransferResult
    {
        public Guid RequestTransferID { get; set; }
        [StringLength(20)]
        public string? RequestNo { get; set; }
        [StringLength(50)]
        public string? FromStore { get; set; }
        [StringLength(50)]
        public string? ToStore { get; set; }
        [StringLength(7)]
        public string RequestTransferStatusDec { get; set; } = default!;
        public int? Status { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? FromStoreID { get; set; }
        public Guid? ToStoreID { get; set; }
        public DateTime? RequestDate { get; set; }
        public int RequestStatus { get; set; }
        [Column("openItems", TypeName = "decimal(38,0)")]
        public decimal? openItems { get; set; }
    }
}
