// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetOnOrderTransferItemResult
    {
        public Guid TransferOrderID { get; set; }
        public DateTime? TransferOrderDate { get; set; }
        [StringLength(50)]
        public string? TransferOrderNo { get; set; }
        [Column("Qty", TypeName = "decimal(18,0)")]
        public decimal? Qty { get; set; }
        [StringLength(50)]
        public string? Store { get; set; }
    }
}
