// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetStatementTransactionEntryByCustomerResult
    {
        public Guid? TransactionID { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("Price", TypeName = "decimal(19,4)")]
        public decimal? Price { get; set; }
        [Column("RegPrice", TypeName = "decimal(19,4)")]
        public decimal? RegPrice { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        public int? Sort { get; set; }
    }
}
