// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetStoreChildsResult
    {
        public Guid ItemStoreID { get; set; }
        public Guid ItemNo { get; set; }
        public Guid StoreNo { get; set; }
        public Guid? DepartmentID { get; set; }
        public bool? IsDiscount { get; set; }
        public bool? IsTaxable { get; set; }
        public bool? IsFoodStampable { get; set; }
        public bool? IsWIC { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("ListPrice", TypeName = "money")]
        public decimal ListPrice { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal Price { get; set; }
        [Column("PriceA", TypeName = "money")]
        public decimal PriceA { get; set; }
        [Column("PriceB", TypeName = "money")]
        public decimal PriceB { get; set; }
        [Column("PriceC", TypeName = "money")]
        public decimal PriceC { get; set; }
        [Column("PriceD", TypeName = "money")]
        public decimal PriceD { get; set; }
        public Guid? ExtraCharge1 { get; set; }
        public Guid? ExtraCharge2 { get; set; }
        public Guid? ExtraCharge3 { get; set; }
        public int? CogsAccount { get; set; }
        public int? IncomeAccount { get; set; }
        public int ProfitCalculation { get; set; }
        [Column("CommissionQty", TypeName = "decimal(19,3)")]
        public decimal? CommissionQty { get; set; }
        public int CommissionType { get; set; }
        public int? PrefSaleBy { get; set; }
        public int? PrefOrderBy { get; set; }
        public Guid? MainSupplierID { get; set; }
        [Column("OnOrder", TypeName = "decimal(19,3)")]
        public decimal? OnOrder { get; set; }
        [Column("OnHand", TypeName = "decimal(19,3)")]
        public decimal? OnHand { get; set; }
        [Column("ReorderPoint", TypeName = "decimal(19,3)")]
        public decimal? ReorderPoint { get; set; }
        [Column("RestockLevel", TypeName = "decimal(19,3)")]
        public decimal? RestockLevel { get; set; }
        [StringLength(50)]
        public string? BinLocation { get; set; }
        [Column("OnWorkOrder", TypeName = "decimal(18,0)")]
        public decimal? OnWorkOrder { get; set; }
        public int? DaysForReturn { get; set; }
        [Column("NewPrice", TypeName = "money")]
        public decimal? NewPrice { get; set; }
        public DateTime? NewPriceDate { get; set; }
        [Column("AVGCost", TypeName = "money")]
        public decimal? AVGCost { get; set; }
        public int? SaleType { get; set; }
        [Column("SalePrice", TypeName = "money")]
        public decimal? SalePrice { get; set; }
        public DateTime? SaleStartDate { get; set; }
        public DateTime? SaleEndDate { get; set; }
        public int? SaleMin { get; set; }
        public int? SaleMax { get; set; }
        [Column("MinForSale", TypeName = "money")]
        public decimal? MinForSale { get; set; }
        public int? SpecialBuy { get; set; }
        [Column("SpecialPrice", TypeName = "money")]
        public decimal? SpecialPrice { get; set; }
        public DateTime? SpecialBuyFromDate { get; set; }
        public DateTime? SpecialBuyToDate { get; set; }
        public Guid? MixAndMatchID { get; set; }
        public bool? AssignDate { get; set; }
        public short? Status { get; set; }
        [Column("MTDQty", TypeName = "decimal(18,0)")]
        public decimal? MTDQty { get; set; }
        [Column("MTDDollar", TypeName = "money")]
        public decimal? MTDDollar { get; set; }
        [Column("PTDQty", TypeName = "decimal(18,0)")]
        public decimal? PTDQty { get; set; }
        [Column("PTDDollar", TypeName = "money")]
        public decimal? PTDDollar { get; set; }
        [Column("YTDQty", TypeName = "decimal(18,0)")]
        public decimal? YTDQty { get; set; }
        [Column("YTDDollar", TypeName = "money")]
        public decimal? YTDDollar { get; set; }
        [Column("MTDReturnQty", TypeName = "decimal(18,0)")]
        public decimal? MTDReturnQty { get; set; }
        [Column("PTDReturnQty", TypeName = "decimal(18,0)")]
        public decimal? PTDReturnQty { get; set; }
        [Column("YTDReturnQty", TypeName = "decimal(18,0)")]
        public decimal? YTDReturnQty { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("OnTransferOrder", TypeName = "decimal(19,3)")]
        public decimal? OnTransferOrder { get; set; }
        public bool? SpecialsMemberOnly { get; set; }
        [Column("CasePrice", TypeName = "money")]
        public decimal? CasePrice { get; set; }
        public int? PkgQty { get; set; }
        [Column("PkgPrice", TypeName = "money")]
        public decimal? PkgPrice { get; set; }
        [Column("Tare", TypeName = "decimal(19,2)")]
        public decimal? Tare { get; set; }
        public Guid? TaxID { get; set; }
        [Column("RegCost", TypeName = "money")]
        public decimal? RegCost { get; set; }
        public Guid? LoyaltyGroupID { get; set; }
        public DateTime? LoyaltyGroupFromDate { get; set; }
        public DateTime? LoyaltyGroupToDate { get; set; }
        [StringLength(50)]
        public string? VoidReason { get; set; }
        [Column("ListPriceMarkdown", TypeName = "money")]
        public decimal? ListPriceMarkdown { get; set; }
        public bool? IsPkgDiscount { get; set; }
        public bool? IsCaseDiscount { get; set; }
        [Column("CaseSpecial", TypeName = "money")]
        public decimal? CaseSpecial { get; set; }
        public DateTime? LastReceivedDate { get; set; }
        [Column("LastReceivedQty", TypeName = "decimal(18,2)")]
        public decimal? LastReceivedQty { get; set; }
        public DateTime? LastSoldDate { get; set; }
        [Column("RegSalePrice", TypeName = "money")]
        public decimal? RegSalePrice { get; set; }
        [Column("SpecialCost", TypeName = "money")]
        public decimal SpecialCost { get; set; }
        [Column("NetCost", TypeName = "money")]
        public decimal NetCost { get; set; }
        [Column("EstimatedCost", TypeName = "money")]
        public decimal EstimatedCost { get; set; }
        [Column("WebPrice", TypeName = "money")]
        public decimal? WebPrice { get; set; }
        [Column("WebCasePrice", TypeName = "money")]
        public decimal? WebCasePrice { get; set; }
        public bool? SellOnWeb { get; set; }
        [Column("YTDQty1", TypeName = "decimal(18,0)")]
        public decimal? YTDQty1 { get; set; }
        [Column("YTDQty2", TypeName = "decimal(18,0)")]
        public decimal? YTDQty2 { get; set; }
        [Column("YTDQty3", TypeName = "decimal(18,0)")]
        public decimal? YTDQty3 { get; set; }
        public Guid? LastSoldUser { get; set; }
        [Column("LastSoldQty", TypeName = "decimal(19,3)")]
        public decimal? LastSoldQty { get; set; }
        public Guid? LastReceivedUser { get; set; }
        [Column("TotalSold", TypeName = "decimal(19,3)")]
        public decimal? TotalSold { get; set; }
        [Column("TotalReceive", TypeName = "decimal(19,3)")]
        public decimal? TotalReceive { get; set; }
        [Column("TotalProfit", TypeName = "money")]
        public decimal? TotalProfit { get; set; }
        public DateTime? LastPriceChange { get; set; }
    }
}
