// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetLastTransactionByCustomerResult
    {
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public DateTime? SaleTime { get; set; }
        [Column("TotalSale", TypeName = "money")]
        public decimal? TotalSale { get; set; }
        public Guid TransactionID { get; set; }
        [Column("ItemsQty", TypeName = "decimal(38,3)")]
        public decimal? ItemsQty { get; set; }
    }
}
