// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTransactionEntryViewResult
    {
        public int? Sort { get; set; }
        public int TransactionEntryType { get; set; }
        public bool? Taxable { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("UOMType", TypeName = "money")]
        public decimal? UOMType { get; set; }
        [Column("UOMQty", TypeName = "decimal(19,3)")]
        public decimal? UOMQty { get; set; }
        [Column("DiscountPerc", TypeName = "decimal(19,3)")]
        public decimal? DiscountPerc { get; set; }
        [Column("DiscountAmount", TypeName = "money")]
        public decimal? DiscountAmount { get; set; }
        [StringLength(50)]
        public string? SaleCode { get; set; }
        [StringLength(50)]
        public string? PriceExplanation { get; set; }
        public Guid? ParentTransactionEntry { get; set; }
        [Column("AVGCost", TypeName = "money")]
        public decimal? AVGCost { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        public int? ReturnReason { get; set; }
        [StringLength(50)]
        public string? Note { get; set; }
        public short Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? ItemCode { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("UOMPrice", TypeName = "money")]
        public decimal? UOMPrice { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        public Guid? DepartmentID { get; set; }
        public Guid TransactionEntryID { get; set; }
        public Guid? TransactionID { get; set; }
        public Guid? ItemStoreID { get; set; }
        [Column("DiscountOnTotal", TypeName = "decimal(19,3)")]
        public decimal? DiscountOnTotal { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        [Column("OnHand", TypeName = "decimal(19,3)")]
        public decimal? OnHand { get; set; }
        public Guid? ItemID { get; set; }
        [Column("TotalAfterDiscount", TypeName = "decimal(18,3)")]
        public decimal? TotalAfterDiscount { get; set; }
        [Column("RegUnitPrice", TypeName = "money")]
        public decimal? RegUnitPrice { get; set; }
    }
}
