// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetUnReadMailsResult
    {
        public Guid EmailID { get; set; }
        [StringLength(4000)]
        public string? Subject { get; set; }
        public string? Body { get; set; }
        [StringLength(50)]
        public string? From { get; set; }
        [StringLength(50)]
        public string? FromAddress { get; set; }
        [StringLength(100)]
        public string? To { get; set; }
        [StringLength(50)]
        public string? ToAddress { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public int? MailType { get; set; }
        public short? MailStatus { get; set; }
        [StringLength(4000)]
        public string? EmailUid { get; set; }
        public byte[]? Attachment { get; set; }
        [StringLength(50)]
        public string? FileName { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(500)]
        public string? ErrorMessage { get; set; }
        public Guid? TransactionID { get; set; }
        [StringLength(4000)]
        public string? EmailText { get; set; }
    }
}
