// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetItemsForAdjustResult
    {
        public Guid ItemID { get; set; }
        [StringLength(50)]
        public string? CustomerCode { get; set; }
        public Guid ItemStoreID { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("CurrentOnHand", TypeName = "decimal(19,3)")]
        public decimal? CurrentOnHand { get; set; }
        [Column("OnHand", TypeName = "decimal(21,3)")]
        public decimal? OnHand { get; set; }
        public DateTime? CountDate { get; set; }
        public int? LastCount { get; set; }
        [StringLength(50)]
        public string? Department { get; set; }
    }
}
