// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTendersCashierResult
    {
        [StringLength(50)]
        public string? TransactionType { get; set; }
        [StringLength(50)]
        public string? Type { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(50)]
        public string? TenderType { get; set; }
        [StringLength(50)]
        public string? Cashier { get; set; }
        [StringLength(50)]
        public string? CreditType { get; set; }
        public Guid? TransactionID { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(101)]
        public string CustomerName { get; set; } = default!;
        [StringLength(50)]
        public string? TransactionNo { get; set; }
        public DateTime? TenderDate { get; set; }
        [StringLength(50)]
        public string? RegistersBackoffice { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        [StringLength(50)]
        public string? Common1 { get; set; }
    }
}
