// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetSalesBasketsViewResult
    {
        public Guid BasketID { get; set; }
        public Guid? SaleID { get; set; }
        public Guid? BaskItemID { get; set; }
        public int? BaskActionType { get; set; }
        public int? BaskItemType { get; set; }
        public Guid? SupplierID { get; set; }
        public int? QtyBasket { get; set; }
        [Column("MinQty", TypeName = "decimal(18,0)")]
        public decimal? MinQty { get; set; }
        public short? Status { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
