// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetEntryProfitResult
    {
        [StringLength(250)]
        public string? Name { get; set; }
        [Column("UOMPrice", TypeName = "money")]
        public decimal? UOMPrice { get; set; }
        [Column("UOMQty", TypeName = "decimal(19,3)")]
        public decimal? UOMQty { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        [Column("Cost", TypeName = "decimal(38,6)")]
        public decimal? Cost { get; set; }
        [Column("DiscountPerc", TypeName = "decimal(38,18)")]
        public decimal? DiscountPerc { get; set; }
        [Column("DiscountAmount", TypeName = "decimal(19,3)")]
        public decimal? DiscountAmount { get; set; }
        [Column("TotalAfterDiscount", TypeName = "decimal(21,4)")]
        public decimal? TotalAfterDiscount { get; set; }
        [Column("Markup", TypeName = "decimal(38,6)")]
        public decimal? Markup { get; set; }
        [Column("Margin", TypeName = "decimal(38,6)")]
        public decimal? Margin { get; set; }
        [Column("Profit", TypeName = "decimal(38,6)")]
        public decimal? Profit { get; set; }
        [Column("DiscountOnTotal", TypeName = "decimal(19,3)")]
        public decimal? DiscountOnTotal { get; set; }
    }
}
