// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetNewBatchResult
    {
        [StringLength(50)]
        public string? UserName { get; set; }
        public Guid BatchID { get; set; }
        [StringLength(50)]
        public string? BatchNumber { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        [StringLength(5)]
        public string Status { get; set; } = default!;
        public DateTime? OpeningDateTime { get; set; }
        public DateTime? ClosingDateTime { get; set; }
    }
}
