// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetOpenSaleOrderViewResult
    {
        public Guid? WOID { get; set; }
        public Guid? ItemStoreID { get; set; }
        [Column("QTY", TypeName = "decimal(38,0)")]
        public decimal? QTY { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
    }
}
