// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetInventorySalesResult
    {
        [StringLength(50)]
        public string? SupplierNo { get; set; }
        [StringLength(50)]
        public string? SupplierName { get; set; }
        [StringLength(20)]
        public string? StoreNumber { get; set; }
        [Column("ReceiveEntryQty", TypeName = "decimal(38,2)")]
        public decimal? ReceiveEntryQty { get; set; }
        [Column("TransactionEntryQty", TypeName = "decimal(38,3)")]
        public decimal? TransactionEntryQty { get; set; }
        [Column("OnHand", TypeName = "decimal(38,3)")]
        public decimal? OnHand { get; set; }
        [Column("NetCost", TypeName = "money")]
        public decimal? NetCost { get; set; }
        [Column("TransferEntryQty", TypeName = "decimal(38,0)")]
        public decimal? TransferEntryQty { get; set; }
        [Column("TransactionEntryTotal", TypeName = "money")]
        public decimal? TransactionEntryTotal { get; set; }
        [Column("Profit", TypeName = "decimal(38,4)")]
        public decimal? Profit { get; set; }
        [Column("OnHandAvgCost", TypeName = "decimal(38,6)")]
        public decimal? OnHandAvgCost { get; set; }
        [Column("DiscountPerc", TypeName = "decimal(38,6)")]
        public decimal? DiscountPerc { get; set; }
        [Column("MarkDown", TypeName = "money")]
        public decimal? MarkDown { get; set; }
        [Column("ProfitPerc", TypeName = "decimal(38,6)")]
        public decimal? ProfitPerc { get; set; }
        [Column("InventorySold", TypeName = "decimal(38,15)")]
        public decimal? InventorySold { get; set; }
    }
}
