// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetLeftDebitsResult
    {
        public Guid TransactionID { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column("PayedAmount", TypeName = "money")]
        public decimal PayedAmount { get; set; }
        [Column("LeftDebit", TypeName = "decimal(31,11)")]
        public decimal? LeftDebit { get; set; }
        public DateTime? StartSaleTime { get; set; }
        [Column("Terms Discount(%)", TypeName = "decimal(6,3)")]
        public decimal TermsDiscount { get; set; }
        public int ApplyAmount { get; set; }
        public int Apply { get; set; }
    }
}
