// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetUnTransferedChecksResult
    {
        public Guid TenderEntryID { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(50)]
        public string? FirstName { get; set; }
        [StringLength(50)]
        public string? LastName { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(50)]
        public string? CheckNo { get; set; }
        [StringLength(50)]
        public string? SubsidiaryNo { get; set; }
        [StringLength(50)]
        public string? BankNo { get; set; }
        public DateTime? PaymentDate { get; set; }
        public DateTime? DueDate { get; set; }
        public int Transfer { get; set; }
    }
}
