// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Sp_GetGlobalChangesResult
    {
        public Guid GlobalChangeID { get; set; }
        public Guid? UserID { get; set; }
        [StringLength(150)]
        public string? ChangeDescr { get; set; }
        public bool? AllStores { get; set; }
        public DateTime? DateCreated { get; set; }
    }
}
