// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetDiscountViewResult
    {
        public Guid DiscountID { get; set; }
        [StringLength(50)]
        public string? Name { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        [Column("PercentsDiscount", TypeName = "money")]
        public decimal? PercentsDiscount { get; set; }
        [Column("AmountDiscount", TypeName = "money")]
        public decimal? AmountDiscount { get; set; }
        [Column("MinTotalSale", TypeName = "money")]
        public decimal? MinTotalSale { get; set; }
        [StringLength(50)]
        public string? UPCDiscount { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        public bool? ClearBalance { get; set; }
        public int? ClearDays { get; set; }
        public bool? ReqPaswrd { get; set; }
        [Column("DiscountForCC", TypeName = "money")]
        public decimal? DiscountForCC { get; set; }
        public bool? DiscountItems { get; set; }
        [Column("PercentsDiscountWithCC", TypeName = "money")]
        public decimal? PercentsDiscountWithCC { get; set; }
        public bool? SalesItem { get; set; }
        [Column("MinTotalSale2", TypeName = "money")]
        public decimal? MinTotalSale2 { get; set; }
        [Column("PercentsDiscount2", TypeName = "money")]
        public decimal? PercentsDiscount2 { get; set; }
        [Column("AmountDiscount2", TypeName = "money")]
        public decimal? AmountDiscount2 { get; set; }
        [Column("MinTotalSale3", TypeName = "money")]
        public decimal? MinTotalSale3 { get; set; }
        [Column("PercentsDiscount3", TypeName = "money")]
        public decimal? PercentsDiscount3 { get; set; }
        [Column("AmountDiscount3", TypeName = "money")]
        public decimal? AmountDiscount3 { get; set; }
        public int? DiscountType { get; set; }
        public bool IncludeGiftCard { get; set; }
        public int? DiscountItem { get; set; }
        public int? DiscountDepartment { get; set; }
        public int? DiscountBrand { get; set; }
        public int? DiscountStore { get; set; }
        public int? BogoQty { get; set; }
        [Column("BogoAmount", TypeName = "decimal(18,0)")]
        public decimal? BogoAmount { get; set; }
        public int? BogoType { get; set; }
        public bool? SelectedItem { get; set; }
        [Column("MaxAmount", TypeName = "money")]
        public decimal MaxAmount { get; set; }
        public bool? AutoAssign { get; set; }
    }
}
