// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetItemListViewResult
    {
        public short? Status { get; set; }
        public int? ItemType { get; set; }
        public Guid StoreNo { get; set; }
        public Guid? SupplierNo { get; set; }
        public Guid? LinkNo { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        public Guid ItemID { get; set; }
        [StringLength(50)]
        public string? UPC { get; set; }
        [Column("Average Delivery Delay")]
        public int? AverageDeliveryDelay { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal Cost { get; set; }
        [Column("Min Qty")]
        public int? MinQty { get; set; }
        [Column("Case Only")]
        public bool? CaseOnly { get; set; }
        [Column("Main Supplier")]
        public bool MainSupplier { get; set; }
    }
}
