// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPrintedViewResult
    {
        [StringLength(50)]
        public string PrintedName { get; set; } = default!;
        public string PrintedContent { get; set; } = default!;
        public int? Status { get; set; }
    }
}
