// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetOneTransferResult
    {
        public Guid TransferID { get; set; }
        [StringLength(50)]
        public string? TransferNo { get; set; }
        public Guid? FromStoreID { get; set; }
        public Guid? ToStoreID { get; set; }
        public DateTime? TransferDate { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public Guid? PersonID { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(7)]
        public string TransferStatusDec { get; set; } = default!;
        [StringLength(50)]
        public string? To_Store { get; set; }
        [StringLength(50)]
        public string? From_Store { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        public int? TransferStatus { get; set; }
    }
}
