// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTransferListResult
    {
        public Guid TransferID { get; set; }
        [StringLength(50)]
        public string? TransferNo { get; set; }
        [StringLength(50)]
        public string? FromStore { get; set; }
        [StringLength(50)]
        public string? ToStore { get; set; }
        public DateTime? TransferDate { get; set; }
    }
}
