// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetReceiveEntryToApproveResult
    {
        public Guid ReceiveEntryID { get; set; }
        public Guid? SupplierNoEntry { get; set; }
        public Guid? ReceiveNo { get; set; }
        public Guid? ItemStoreNo { get; set; }
        [Column("Cost", TypeName = "decimal(38,6)")]
        public decimal? Cost { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [Column("CurrentCost", TypeName = "money")]
        public decimal? CurrentCost { get; set; }
        public bool? ForApprove { get; set; }
    }
}
