// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetCustomerSalesWeeklyResult
    {
        public int? weekNo { get; set; }
        public int? saleYear { get; set; }
        [Column("Sale", TypeName = "money")]
        public decimal? Sale { get; set; }
        [Column("avgSale", TypeName = "money")]
        public decimal? avgSale { get; set; }
        public int? visit { get; set; }
        [Column("avgBalance", TypeName = "money")]
        public decimal? avgBalance { get; set; }
    }
}
