// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetEmailTemplateViewResult
    {
        public Guid EmailTemplateID { get; set; }
        [StringLength(50)]
        public string? EmailFrom { get; set; }
        [StringLength(400)]
        public string? Subject { get; set; }
        public string? Body { get; set; }
        public byte[]? EmailContent { get; set; }
        public int? Category { get; set; }
        [StringLength(50)]
        public string? FileName { get; set; }
        public short? Status { get; set; }
    }
}
