// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetDivisionByTransactionResult
    {
        [Column("SumDivision", TypeName = "decimal(38,6)")]
        public decimal SumDivision { get; set; }
        public Guid? TransactionID { get; set; }
        public Guid? SupplierNo { get; set; }
        public DateTime? DateT { get; set; }
    }
}
