// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetCreditSlipViewResult
    {
        public Guid CreditSlipID { get; set; }
        [StringLength(50)]
        public string? CreditSlipNo { get; set; }
        public Guid? TransactionID { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        public DateTime? ExpDate { get; set; }
        [StringLength(400)]
        public string? Note { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
