// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Sp_GetGlobalChangesEntryResult
    {
        public Guid GlobalChangeID { get; set; }
        public Guid? ItemStoreID { get; set; }
        public Guid ItemNo { get; set; }
        public Guid? StoreNo { get; set; }
        public Guid? DepartmentID { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("ListPrice", TypeName = "money")]
        public decimal? ListPrice { get; set; }
        [Column("Price", TypeName = "money")]
        public decimal? Price { get; set; }
        [Column("PriceA", TypeName = "money")]
        public decimal? PriceA { get; set; }
        [Column("PriceB", TypeName = "money")]
        public decimal? PriceB { get; set; }
        [Column("PriceC", TypeName = "money")]
        public decimal? PriceC { get; set; }
        [Column("PriceD", TypeName = "money")]
        public decimal? PriceD { get; set; }
        public Guid? ExtraCharge1 { get; set; }
        public Guid? ExtraCharge2 { get; set; }
        public Guid? ExtraCharge3 { get; set; }
        public Guid? MainSupplierID { get; set; }
        [StringLength(50)]
        public string? BinLocation { get; set; }
        [Column("AVGCost", TypeName = "money")]
        public decimal? AVGCost { get; set; }
        public int? SaleType { get; set; }
        [Column("SalePrice", TypeName = "money")]
        public decimal? SalePrice { get; set; }
        public DateTime? SaleStartDate { get; set; }
        public DateTime? SaleEndDate { get; set; }
        public int? SaleMin { get; set; }
        public int? SaleMax { get; set; }
        [Column("MinForSale", TypeName = "money")]
        public decimal? MinForSale { get; set; }
        public int? SpecialBuy { get; set; }
        [Column("SpecialPrice", TypeName = "money")]
        public decimal? SpecialPrice { get; set; }
        public DateTime? SpecialBuyFromDate { get; set; }
        public DateTime? SpecialBuyToDate { get; set; }
        public Guid? MixAndMatchID { get; set; }
        public bool? AssignDate { get; set; }
    }
}
