// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetItemMainCustomFieldsViewResult
    {
        public Guid CustomFieldValueID { get; set; }
        public Guid CustomFieldNo { get; set; }
        public Guid RowNo { get; set; }
        [StringLength(4000)]
        public string? FieldValue { get; set; }
        public short? Status { get; set; }
        public DateTime? DateModified { get; set; }
    }
}
