// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetOnOrderItemResult
    {
        [StringLength(50)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? PoNo { get; set; }
        public Guid? ItemNo { get; set; }
        [Column("QtyOrdered", TypeName = "decimal(21,3)")]
        public decimal? QtyOrdered { get; set; }
        [Column("PricePerUnit", TypeName = "money")]
        public decimal? PricePerUnit { get; set; }
        public Guid PurchaseOrderId { get; set; }
        [Column("OrderDeficit", TypeName = "decimal(38,2)")]
        public decimal? OrderDeficit { get; set; }
    }
}
