// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetComputersViewResult
    {
        public Guid ComputerID { get; set; }
        [StringLength(255)]
        public string? ComputerName { get; set; }
        [StringLength(255)]
        public string? ComputerNo { get; set; }
        public Guid? StoreID { get; set; }
        [StringLength(255)]
        public string? LabelPrinter { get; set; }
        [StringLength(255)]
        public string? ShelfPrinter { get; set; }
        [StringLength(255)]
        public string? InvoicePrinter { get; set; }
        [StringLength(255)]
        public string? StatementPrinter { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
