// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetQuickReportResult
    {
        public Guid? ID { get; set; }
        [StringLength(16)]
        public string Type { get; set; } = default!;
        public DateTime? Date { get; set; }
        [StringLength(4)]
        public string? UOM { get; set; }
        [Column("Qty", TypeName = "decimal(24,4)")]
        public decimal? Qty { get; set; }
        [StringLength(50)]
        public string? Usr { get; set; }
    }
}
