// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPrintLabelLayoutViewResult
    {
        public Guid PrintLabelLayoutID { get; set; }
        [StringLength(4000)]
        public string? LayoutName { get; set; }
        public string? LayoutContent { get; set; }
        public int? PrinterType { get; set; }
        public int? Status { get; set; }
    }
}
