// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTaxesViewResult
    {
        public Guid TaxID { get; set; }
        [StringLength(50)]
        public string? TaxName { get; set; }
        [Column("Percents", TypeName = "decimal(9,3)")]
        public decimal? Percents { get; set; }
        [Column("FromSum", TypeName = "decimal(18,2)")]
        public decimal? FromSum { get; set; }
        [Column("ToSum", TypeName = "decimal(18,2)")]
        public decimal? ToSum { get; set; }
        public DateTime? DateModified { get; set; }
    }
}
