// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetReceiveOrderByDateAndSupplierNoResult
    {
        public Guid ReceiveID { get; set; }
        [StringLength(50)]
        public string? PackingSlipNo { get; set; }
        public Guid? StoreID { get; set; }
        public Guid? SupplierNo { get; set; }
        public Guid? BillID { get; set; }
        [Column("Freight", TypeName = "money")]
        public decimal? Freight { get; set; }
        [Column("Discount", TypeName = "decimal(18,3)")]
        public decimal? Discount { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        [Column("CurrBalance", TypeName = "money")]
        public decimal? CurrBalance { get; set; }
        public bool? IsDiscAmount { get; set; }
        public DateTime? ReceiveOrderDate { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(150)]
        public string? FilePath { get; set; }
        [Column("CustomsDuties", TypeName = "money")]
        public decimal? CustomsDuties { get; set; }
        [Column("OtherCharges", TypeName = "money")]
        public decimal? OtherCharges { get; set; }
        public Guid? TermsID { get; set; }
        public Guid? BuyerID { get; set; }
        public Guid? BillToStoreID { get; set; }
        [StringLength(100)]
        public string? VendorPONo { get; set; }
        public Guid? DepartmentID { get; set; }
        public Guid? SeasonID { get; set; }
        public Guid? UserEditing { get; set; }
        public DateTime? StartEditing { get; set; }
    }
}
