// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetRequestByRequestIDResult
    {
        public Guid RequestTransferID { get; set; }
        public Guid RequestTransferEntryID { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("RequestUOMQty", TypeName = "decimal(18,0)")]
        public decimal? RequestUOMQty { get; set; }
        [Column("PreviousTranferQty", TypeName = "decimal(38,0)")]
        public decimal? PreviousTranferQty { get; set; }
        [Column("QTY", TypeName = "decimal(38,0)")]
        public decimal? QTY { get; set; }
        [Column("ReciveUOMQty", TypeName = "decimal(38,0)")]
        public decimal? ReciveUOMQty { get; set; }
        [StringLength(50)]
        public string? UOM { get; set; }
        public Guid ID { get; set; }
        public int CaseQty { get; set; }
        [StringLength(20)]
        public string? PONO { get; set; }
        public Guid? ItemStoreID { get; set; }
        public Guid ItemCode { get; set; }
        public int? UOMType { get; set; }
        [StringLength(50)]
        public string? BinLocation { get; set; }
        public Guid FromItemStoreID { get; set; }
        public Guid ItemID { get; set; }
    }
}
