// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetOneReceiveTransferResult
    {
        public Guid ReceiveTransferID { get; set; }
        public DateTime? ReceiveDate { get; set; }
        public Guid? TransferID { get; set; }
        [StringLength(50)]
        public string? TransferNo { get; set; }
        [StringLength(20)]
        public string ReciveNo { get; set; } = default!;
        public int? TransferStatus { get; set; }
        public DateTime? TransferDate { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        [StringLength(50)]
        public string? TransferUser { get; set; }
        [StringLength(50)]
        public string? ReceiveUser { get; set; }
        [StringLength(50)]
        public string? StoreReceived { get; set; }
        [StringLength(50)]
        public string? FromStore { get; set; }
        [StringLength(50)]
        public string? ToStore { get; set; }
        public int? Status { get; set; }
        public Guid? FromStoreid { get; set; }
        public Guid? ToStoreID { get; set; }
        public Guid? StoreID { get; set; }
    }
}
