// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetAdjustInventoryViewResult
    {
        public Guid AdjustInventoryId { get; set; }
        public Guid? ItemStoreNo { get; set; }
        public int? AdjustType { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("OldQty", TypeName = "decimal(18,0)")]
        public decimal? OldQty { get; set; }
        [StringLength(4000)]
        public string? AdjustReason { get; set; }
        public int? AccountNo { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
