// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetPaymentsByGiftResult
    {
        public Guid TransactionID { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(102)]
        public string? CustomerName { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column("Credit", TypeName = "money")]
        public decimal? Credit { get; set; }
        public DateTime? EndSaleTime { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [Column("AmountAdd", TypeName = "money")]
        public decimal AmountAdd { get; set; }
    }
}
