// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetOneReturnResult
    {
        public Guid ReturnToVenderID { get; set; }
        [StringLength(50)]
        public string? ReturnToVenderNo { get; set; }
        public Guid? StoreNo { get; set; }
        public Guid? SupplierID { get; set; }
        public Guid? PersonReturnID { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public DateTime? ReturnToVenderDate { get; set; }
        public bool? Taxable { get; set; }
        [Column("TaxRate", TypeName = "decimal(19,4)")]
        public decimal? TaxRate { get; set; }
        [Column("TaxAmount", TypeName = "money")]
        public decimal? TaxAmount { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("Discount", TypeName = "money")]
        public decimal? Discount { get; set; }
        public bool? IsDiscountInAmount { get; set; }
    }
}
