// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTranOrderToTransferResult
    {
        public Guid TransferOrderID { get; set; }
        [StringLength(50)]
        public string? TransferOrderNo { get; set; }
        public Guid? FromStoreID { get; set; }
        public Guid? ToStoreID { get; set; }
        public DateTime? TransferOrderDate { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        public int? OrderStatus { get; set; }
        public Guid? PersonID { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [Column("From Store")]
        [StringLength(50)]
        public string? FromStore { get; set; }
        [Column("To Store")]
        [StringLength(50)]
        public string? ToStore { get; set; }
    }
}
