// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetUsersViewResult
    {
        public Guid UserId { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        [StringLength(50)]
        public string? Password { get; set; }
        [StringLength(50)]
        public string? UserFName { get; set; }
        [StringLength(50)]
        public string? UserLName { get; set; }
        [StringLength(4000)]
        public string? Address { get; set; }
        [StringLength(50)]
        public string? HomePhoneNumber { get; set; }
        [StringLength(50)]
        public string? WorkPhoneNumber { get; set; }
        [StringLength(50)]
        public string? Fax { get; set; }
        [StringLength(50)]
        public string? Email { get; set; }
        [StringLength(50)]
        public string? ZipCode { get; set; }
        public bool? IsSuperAdmin { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        public Guid? GroupID { get; set; }
        public bool? Manager { get; set; }
        public bool? IsDefault { get; set; }
        public Guid? StoreID { get; set; }
        public DateTime? UserStoreDateM { get; set; }
        [StringLength(20)]
        public string? ScanID { get; set; }
        [StringLength(50)]
        public string? GroupName { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        public bool? IsLogIn { get; set; }
    }
}
