// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_GetTotalProfitYearResult
    {
        [StringLength(12)]
        public string? Month { get; set; }
        [StringLength(3)]
        public string? MonthName { get; set; }
        [StringLength(12)]
        public string Type { get; set; } = default!;
        [Column("Total", TypeName = "decimal(38,3)")]
        public decimal? Total { get; set; }
    }
}
