// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class sp_helpdiagramsResult
    {
        [StringLength(128)]
        public string? Database { get; set; }
        [StringLength(128)]
        public string Name { get; set; } = default!;
        public int ID { get; set; }
        [StringLength(128)]
        public string? Owner { get; set; }
        public int OwnerID { get; set; }
    }
}
