// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_ItemSpecialViewResult
    {
        public int ItemSpecialID { get; set; }
        public Guid? ItemStoreID { get; set; }
        public int SaleType { get; set; }
        [Column("SalePrice", TypeName = "money")]
        public decimal? SalePrice { get; set; }
        public DateTime? SaleStartDate { get; set; }
        public DateTime? SaleEndDate { get; set; }
        public int? SaleMin { get; set; }
        public int? SaleMax { get; set; }
        [Column("MinForSale", TypeName = "money")]
        public decimal? MinForSale { get; set; }
        public int? SpecialBuy { get; set; }
        [Column("SpecialPrice", TypeName = "money")]
        public decimal? SpecialPrice { get; set; }
        public bool? AssignDate { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        public Guid StoreNo { get; set; }
    }
}
