// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_LastTransViewResult
    {
        public Guid TransactionID { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public int ID { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column("Credit", TypeName = "money")]
        public decimal? Credit { get; set; }
        public DateTime? EndSaleTime { get; set; }
        public short? Status { get; set; }
        public DateTime? DateModified { get; set; }
        public int TransactionType { get; set; }
        [StringLength(50)]
        public string? FirstName { get; set; }
        [StringLength(50)]
        public string? LastName { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
    }
}
