// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_LoyaltySetupViewResult
    {
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        public DateTime? DateModified { get; set; }
        public int? DayOfWeek { get; set; }
        public DateTime? FromTime { get; set; }
        public DateTime? ToTime { get; set; }
        public Guid LoyaltySetupID { get; set; }
        [Column("Point", TypeName = "decimal(18,2)")]
        public decimal? Point { get; set; }
        public int? Status { get; set; }
        public Guid? UserModified { get; set; }
        public short? MemberType { get; set; }
        [StringLength(64)]
        public string? NToTime { get; set; }
        [StringLength(64)]
        public string? NFromTime { get; set; }
    }
}
