// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_LocalTransactionEntryResult
    {
        public Guid TransactionEntryID { get; set; }
        public short Status { get; set; }
        [StringLength(500)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("Qty", TypeName = "decimal(19,3)")]
        public decimal? Qty { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        [Column("TotalAfterDiscount", TypeName = "decimal(18,3)")]
        public decimal? TotalAfterDiscount { get; set; }
        [Column("RegUnitPrice", TypeName = "money")]
        public decimal? RegUnitPrice { get; set; }
        [Column("UOMPrice", TypeName = "money")]
        public decimal? UOMPrice { get; set; }
        public Guid TransactionID { get; set; }
        [StringLength(50)]
        public string TransactionNo { get; set; } = default!;
        public int TransactionEntryType { get; set; }
        public double ReturenQty { get; set; }
        public DateTime? DateModified { get; set; }
        public int? Sort { get; set; }
        public Guid? StoreID { get; set; }
    }
}
