// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_MixAndMatchResult
    {
        public Guid MixAndMatchID { get; set; }
        [StringLength(50)]
        public string? Name { get; set; }
        public int? Qty { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        public bool? AssignDate { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        [Column("MinTotalSale", TypeName = "money")]
        public decimal? MinTotalSale { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
