// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_OnePHOForPickSheetResult
    {
        public Guid PhoneOrderID { get; set; }
        [StringLength(50)]
        public string? Type { get; set; }
        public DateTime? PhoneOrderDate { get; set; }
        public DateTime? PhoneOrderTime { get; set; }
        [StringLength(50)]
        public string? PhoneOrderNo { get; set; }
        [StringLength(102)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(50)]
        public string? ShiftID { get; set; }
        [StringLength(2000)]
        public string? PickNote { get; set; }
        [StringLength(100)]
        public string? Phone { get; set; }
        [StringLength(100)]
        public string? Cell { get; set; }
        [StringLength(251)]
        public string Address { get; set; } = default!;
        [StringLength(217)]
        public string? CityStateAndZip { get; set; }
        public DateTime? DeliveryDate { get; set; }
        [StringLength(50)]
        public string? ShipName { get; set; }
        [StringLength(200)]
        public string? ShipAddress { get; set; }
        [StringLength(217)]
        public string? ShipCityStateZip { get; set; }
        [StringLength(50)]
        public string? TakeBy { get; set; }
        public DateTime? LastDateCleared { get; set; }
        [StringLength(100)]
        public string? ShipPhone { get; set; }
        [StringLength(100)]
        public string? ShipCell { get; set; }
        [StringLength(4000)]
        public string? CustomerGroup { get; set; }
        [StringLength(4000)]
        public string? CustomerNote { get; set; }
        public bool Freezer { get; set; }
        [StringLength(50)]
        public string? TenderName { get; set; }
        [StringLength(500)]
        public string? GroupName { get; set; }
        [StringLength(500)]
        public string? Zones { get; set; }
    }
}
