// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_OrderPrintResult
    {
        [StringLength(50)]
        public string? PoNo { get; set; }
        public DateTime? PurchaseOrderDate { get; set; }
        public DateTime? ReqDate { get; set; }
        [StringLength(7)]
        public string? Status { get; set; }
        [Column("GrandTotal", TypeName = "money")]
        public decimal? GrandTotal { get; set; }
        [StringLength(50)]
        public string Terms { get; set; } = default!;
        [Column("Supplier Name")]
        [StringLength(50)]
        public string? SupplierName { get; set; }
        [StringLength(50)]
        public string ContactName { get; set; } = default!;
        [StringLength(101)]
        public string Address { get; set; } = default!;
        [StringLength(88)]
        public string CSZSupplier { get; set; } = default!;
        public Guid PurchaseOrderId { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        [StringLength(50)]
        public string? TrackNo { get; set; }
        [StringLength(101)]
        public string UserFName { get; set; } = default!;
        public DateTime? ExpirationDate { get; set; }
        [StringLength(102)]
        public string ShipToName { get; set; } = default!;
        [StringLength(251)]
        public string ShipToAddress { get; set; } = default!;
        [StringLength(218)]
        public string CSZShipTo { get; set; } = default!;
        [StringLength(50)]
        public string? SupplierNo { get; set; }
        [StringLength(50)]
        public string? ShipViaName { get; set; }
        public bool? Shipdrop { get; set; }
        [StringLength(50)]
        public string? FirstName { get; set; }
        [StringLength(50)]
        public string? AccountNo { get; set; }
        [StringLength(20)]
        public string? Fax { get; set; }
        [StringLength(20)]
        public string? Phone { get; set; }
        public Guid? ShipVia { get; set; }
        [StringLength(20)]
        public string? StoreNo { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        [StringLength(50)]
        public string? StoreAddress { get; set; }
        [StringLength(50)]
        public string? StoreCSZ { get; set; }
        [StringLength(50)]
        public string? StoreTell { get; set; }
        [StringLength(500)]
        public string? SupplierNote { get; set; }
    }
}
