// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class sp_PC_App_Settings_GetResult
    {
        public Guid SettingID { get; set; }
        [StringLength(50)]
        public string SettingName { get; set; } = default!;
        [StringLength(200)]
        public string? SettingValue { get; set; }
        [StringLength(100)]
        public string SettingDescription { get; set; } = default!;
        [StringLength(200)]
        public string? DeviceID { get; set; }
        public Guid? StoreID { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
    }
}
