// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_ProfitDailyResult
    {
        [StringLength(50)]
        public string? Name { get; set; }
        [Column("Amount", TypeName = "decimal(2,2)")]
        public decimal Amount { get; set; }
        [Column("Balance", TypeName = "money")]
        public decimal? Balance { get; set; }
    }
}
