// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Sp_PO_Receive_ReportResult
    {
        public string StoreName { get; set; } = string.Empty;
        public Guid? ItemStoreID { get; set; }
        public string BarcodeNumber { get; set; } = string.Empty;
        public string ModalNumber { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string ManufacturerName { get; set; } = string.Empty;
        public string Department { get; set; } = string.Empty;
        public decimal? OnHand { get; set; }
        public string Supplier { get; set; } = string.Empty;
        public decimal? Cost { get; set; }
        public decimal? Price { get; set; }
        public decimal? QtyReceived { get; set; }
        public decimal? ReceivedValue { get; set; }
        public decimal? ReceivedSellingPrice { get; set; }
        public string MainDepartment { get; set; } = string.Empty;
        public string SubDepartment { get; set; } = string.Empty;
        public string SubSubDepartment { get; set; } = string.Empty;
        public string CustomField1 { get; set; } = string.Empty;
        public string CustomField2 { get; set; } = string.Empty;
        public string CustomField3 { get; set; } = string.Empty;
        public string CustomField4 { get; set; } = string.Empty;
        public string CustomField5 { get; set; } = string.Empty;
        public string CustomField6 { get; set; } = string.Empty;
        public string CustomField7 { get; set; } = string.Empty;
        public string CustomField8 { get; set; } = string.Empty;
        public string CustomField9 { get; set; } = string.Empty;
        public string CustomField10 { get; set; } = string.Empty;
    }
}
