// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_ReceiveEntryItemResult
    {
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("Qty", TypeName = "decimal(18,2)")]
        public decimal? Qty { get; set; }
        public Guid ReceiveID { get; set; }
        [StringLength(50)]
        public string? SupplierNo { get; set; }
    }
}
