// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_ReceiveEntryPrintResult
    {
        public Guid? ReceiveNo { get; set; }
        [Column("UOMQty", TypeName = "decimal(18,2)")]
        public decimal? UOMQty { get; set; }
        [StringLength(50)]
        public string? UOM { get; set; }
        [Column("UOMPrice", TypeName = "decimal(38,6)")]
        public decimal? UOMPrice { get; set; }
        [StringLength(250)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string? BarcodeNumber { get; set; }
        [StringLength(50)]
        public string? ModalNumber { get; set; }
        [Column("TotalPrice", TypeName = "decimal(38,6)")]
        public decimal? TotalPrice { get; set; }
    }
}
