// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_ReceivePrintResult
    {
        [StringLength(50)]
        public string? PoNo { get; set; }
        public DateTime? ReceiveOrderDate { get; set; }
        [Column("Total", TypeName = "money")]
        public decimal? Total { get; set; }
        [StringLength(4000)]
        public string? Note { get; set; }
        [Column("Discount", TypeName = "decimal(18,3)")]
        public decimal? Discount { get; set; }
        [Column("TotalAfterDisc", TypeName = "decimal(20,4)")]
        public decimal? TotalAfterDisc { get; set; }
        [Column("Freight", TypeName = "money")]
        public decimal? Freight { get; set; }
        [StringLength(50)]
        public string? SupplierNo { get; set; }
        [StringLength(50)]
        public string? Name { get; set; }
        [StringLength(50)]
        public string ContactName { get; set; } = default!;
        [StringLength(101)]
        public string Address { get; set; } = default!;
        [StringLength(87)]
        public string CSZSupplier { get; set; } = default!;
        [StringLength(50)]
        public string? BillNo { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        public DateTime? BillDate { get; set; }
        public Guid ReceiveID { get; set; }
        [Column("CustomsDuties", TypeName = "money")]
        public decimal? CustomsDuties { get; set; }
        [Column("OtherCharges", TypeName = "money")]
        public decimal? OtherCharges { get; set; }
    }
}
