// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Sp_rptRecicveValueResult
    {
        [StringLength(1)]
        public string MainDepartment { get; set; } = default!;
        [StringLength(1)]
        public string SubDepartment { get; set; } = default!;
        [StringLength(1)]
        public string SubSubDepartment { get; set; } = default!;
        [StringLength(50)]
        public string? Department { get; set; }
        [Column("Qty", TypeName = "decimal(38,2)")]
        public decimal? Qty { get; set; }
        [Column("Cost", TypeName = "money")]
        public decimal? Cost { get; set; }
        [Column("Price", TypeName = "decimal(38,6)")]
        public decimal? Price { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
    }
}
