// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_ReceiveToAddInreturnResult
    {
        public Guid ReceiveID { get; set; }
        [StringLength(50)]
        public string? BillNo { get; set; }
        public Guid? StoreID { get; set; }
        public Guid? SupplierNo { get; set; }
        public DateTime? BillDate { get; set; }
        [StringLength(50)]
        public string? SupplierName { get; set; }
    }
}
