// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class sp_RCA_GetOctopusCollectsDeleteResult
    {
        public Guid RecordID { get; set; }
        [StringLength(50)]
        public string? OctopusCollectID { get; set; }
        [StringLength(50)]
        public string? OctopusCollectionID { get; set; }
        [StringLength(50)]
        public string? OctopusItemId { get; set; }
    }
}
