// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_SalesIncentivePOSResult
    {
        public Guid SalesIncentiveID { get; set; }
        public Guid ItemMainID { get; set; }
        public DateTime? DateModified { get; set; }
        public int Status { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        [Column("IncentiveValueAmount", TypeName = "money")]
        public decimal? IncentiveValueAmount { get; set; }
        [Column("IncentiveValuePercent", TypeName = "decimal(18,2)")]
        public decimal? IncentiveValuePercent { get; set; }
    }
}
