// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_StoreResult
    {
        public Guid StoreID { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        [StringLength(4000)]
        public string? StoreDescription { get; set; }
        public Guid? ParentStore { get; set; }
        [Column("DefaultMarkup", TypeName = "decimal(28,3)")]
        public decimal? DefaultMarkup { get; set; }
        [Column("DefaultMarkupA", TypeName = "decimal(18,0)")]
        public decimal? DefaultMarkupA { get; set; }
        [Column("DefaultMarkupB", TypeName = "decimal(18,0)")]
        public decimal? DefaultMarkupB { get; set; }
        [Column("DefaultMarkupC", TypeName = "decimal(18,0)")]
        public decimal? DefaultMarkupC { get; set; }
        [Column("DefaultMarkupD", TypeName = "decimal(18,0)")]
        public decimal? DefaultMarkupD { get; set; }
        public int? RoundUp { get; set; }
        [Column("RoundValue", TypeName = "decimal(18,3)")]
        public decimal? RoundValue { get; set; }
        public int? DefaultCogsAccount { get; set; }
        public int? DefaultIncomeAccount { get; set; }
        public Guid? DefaultTaxNo { get; set; }
        public bool? IsDefaultTaxInclude { get; set; }
        public int? DefaultProfitCalculation { get; set; }
        [StringLength(20)]
        public string? StoreEmail { get; set; }
        public byte[]? Logo { get; set; }
        public short? Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        public bool? IsMainStore { get; set; }
        [StringLength(20)]
        public string? StoreNumber { get; set; }
        [StringLength(50)]
        public string? Address { get; set; }
        [StringLength(50)]
        public string? CityStateZip { get; set; }
        public string? Country { get; set; }
        [StringLength(50)]
        public string? Phone1 { get; set; }
        [StringLength(20)]
        public string? Fax { get; set; }
        [StringLength(20)]
        public string? Phone2 { get; set; }
        public Guid? DistrictID { get; set; }
        public Guid? RegionID { get; set; }
        public DateTime? DateOpened { get; set; }
        public DateTime? DateClosed { get; set; }
        [StringLength(20)]
        public string? ShopperTrackIP { get; set; }
        public Guid? Tax2 { get; set; }
        public Guid? Tax3 { get; set; }
        public Guid? Tax4 { get; set; }
        public int StoreInt { get; set; }
        [Column("CashDiscount", TypeName = "decimal(18,4)")]
        public decimal? CashDiscount { get; set; }
        [StringLength(500)]
        public string? LogoPath { get; set; }
        public int? OctopusShopId { get; set; }
    }
}
