// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_SystemTableOrderTypeResult
    {
        public int SystemValueNo { get; set; }
        [StringLength(50)]
        public string? SystemValueName { get; set; }
        public int? SortOrder { get; set; }
        public long SystemTableNo { get; set; }
        [StringLength(50)]
        public string? SystemValueNameHe { get; set; }
        public DateTime? DateModified { get; set; }
        public int Status { get; set; }
    }
}
