// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class sp_SSA_Item_AddResult
    {
        public bool? Success { get; set; }
        public int Code { get; set; }
        [StringLength(24)]
        public string Description { get; set; } = default!;
    }
}
