// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class sp_SSA_Printers_DefaultResult
    {
        public Guid PrinterID { get; set; }
        [StringLength(50)]
        public string PrinterName { get; set; } = default!;
        [StringLength(100)]
        public string Description { get; set; } = default!;
        [StringLength(50)]
        public string PrinterIP { get; set; } = default!;
        [StringLength(50)]
        public string? PrinterPort { get; set; }
        public bool? IsDefault { get; set; }
        public Guid? StoreID { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? UserCreated { get; set; }
        public DateTime? DateModified { get; set; }
        public Guid? UserModified { get; set; }
        [StringLength(200)]
        public string? DeviceID { get; set; }
    }
}
