// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class sp_SSA_LoginVerificationResult
    {
        public bool? Success { get; set; }
        public int Code { get; set; }
        [StringLength(30)]
        public string Description { get; set; } = default!;
        public Guid UserID { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        [StringLength(50)]
        public string? UserFname { get; set; }
        [StringLength(50)]
        public string? UserLName { get; set; }
        public short? Status { get; set; }
        public bool? IsSuperAdmin { get; set; }
    }
}
