// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class sp_SSA_GetNotesResult
    {
        public Guid PhoneOrderID { get; set; }
        [StringLength(2000)]
        public string CustomerNote { get; set; } = default!;
        [StringLength(2000)]
        public string PickNote { get; set; } = default!;
    }
}
