// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_TenderTotalByBatchResult
    {
        public short? SortOrder { get; set; }
        public Guid? BatchID { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(50)]
        public string? TenderName { get; set; }
        [StringLength(50)]
        public string? BatchNumber { get; set; }
        public DateTime? OpeningDateTime { get; set; }
        public DateTime? ClosingDateTime { get; set; }
        [Column("SumTax", TypeName = "money")]
        public decimal? SumTax { get; set; }
        [Column("SumSale", TypeName = "money")]
        public decimal? SumSale { get; set; }
        [Column("SumPay", TypeName = "money")]
        public decimal? SumPay { get; set; }
        public int? TenderGroup { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        [Column("SumPayOut", TypeName = "money")]
        public decimal? SumPayOut { get; set; }
        public int CountTender { get; set; }
        public int? TransCount { get; set; }
    }
}
