// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_TenderTotalByDayResult
    {
        public short? SortOrder { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(50)]
        public string? TenderName { get; set; }
        [Column("SumTax", TypeName = "money")]
        public decimal? SumTax { get; set; }
        [Column("SumSale", TypeName = "decimal(38,3)")]
        public decimal? SumSale { get; set; }
        [Column("SumPay", TypeName = "money")]
        public decimal? SumPay { get; set; }
        public int? TenderGroup { get; set; }
        [Column("SumPayOut", TypeName = "money")]
        public decimal? SumPayOut { get; set; }
        public int CountTender { get; set; }
        public int? TransCount { get; set; }
        public int? CountCustomer { get; set; }
        [Column("SumItemQty", TypeName = "decimal(38,3)")]
        public decimal? SumItemQty { get; set; }
        public DateTime? Day { get; set; }
        [Column("OpenCredits", TypeName = "money")]
        public decimal OpenCredits { get; set; }
    }
}
