// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_TransactionByAgingResult
    {
        [StringLength(12)]
        public string Type { get; set; } = default!;
        public DateTime? DateT { get; set; }
        [StringLength(50)]
        public string Num { get; set; } = default!;
        public DateTime? DueDate { get; set; }
        [Column("OpenBalance", TypeName = "money")]
        public decimal OpenBalance { get; set; }
        [Column("AmountPay", TypeName = "money")]
        public decimal? AmountPay { get; set; }
        public Guid IDc { get; set; }
        public Guid? PID { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(102)]
        public string Name { get; set; } = default!;
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        public short? Status { get; set; }
        [Column("Debit", TypeName = "money")]
        public decimal? Debit { get; set; }
        [Column("Credit", TypeName = "money")]
        public decimal? Credit { get; set; }
        public int TransactionType { get; set; }
        public DateTime? StartSaleTime { get; set; }
        public DateTime? TimeT { get; set; }
        public Guid? StoreID { get; set; }
        [StringLength(50)]
        public string? StoreName { get; set; }
        public Guid? UserCreated { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
    }
}
