// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_TrackSalesResult
    {
        [Column("Total", TypeName = "decimal(38,3)")]
        public decimal? Total { get; set; }
        [StringLength(250)]
        public string ItemName { get; set; } = default!;
        [StringLength(50)]
        public string Department { get; set; } = default!;
        [StringLength(50)]
        public string? StoreName { get; set; }
    }
}
