// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_TenderTotalByRegShiftResult
    {
        public short? SortOrder { get; set; }
        public Guid? RegShiftID { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(59)]
        public string? TenderName { get; set; }
        [StringLength(50)]
        public string ShiftNO { get; set; } = default!;
        public DateTime? ShiftOpenDate { get; set; }
        public DateTime? ShiftCloseDate { get; set; }
        public int? TenderGroup { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        [Column("SumPayOut", TypeName = "money")]
        public decimal? SumPayOut { get; set; }
        public int CountTender { get; set; }
        [Column("OpeningAmount", TypeName = "money")]
        public decimal? OpeningAmount { get; set; }
    }
}
