// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class SP_UserQueryResult
    {
        public Guid UserId { get; set; }
        [StringLength(50)]
        public string? UserName { get; set; }
        [StringLength(50)]
        public string? Password { get; set; }
        [StringLength(50)]
        public string? UserFName { get; set; }
        [StringLength(50)]
        public string? UserLName { get; set; }
        [StringLength(4000)]
        public string? Address { get; set; }
        [StringLength(50)]
        public string? HomePhoneNumber { get; set; }
        [StringLength(50)]
        public string? WorkPhoneNumber { get; set; }
        [StringLength(50)]
        public string? Fax { get; set; }
        [StringLength(50)]
        public string? Email { get; set; }
        [StringLength(50)]
        public string? ZipCode { get; set; }
        public bool? IsSuperAdmin { get; set; }
        public Guid? StoreID { get; set; }
        public bool? OnLine { get; set; }
        public bool? IsDefault { get; set; }
        public bool? Manager { get; set; }
        [StringLength(50)]
        public string? GroupName { get; set; }
        public bool? IsSystem { get; set; }
        public bool? ChangePrices { get; set; }
        public bool? UpdateCustomer { get; set; }
        public bool? UpdateCustomerCredit { get; set; }
        public bool? UpdateCustomerDiscount { get; set; }
        public bool? UpdateItems { get; set; }
        public bool? UpdateItemsPrice { get; set; }
        public bool? Returns { get; set; }
        public bool? ExitPOS { get; set; }
        public bool? ChargeOnAccount { get; set; }
        public bool? NoSales { get; set; }
        public bool? DiscountSales { get; set; }
        public bool? RequireCashBreakDown { get; set; }
        public bool? VoidItem { get; set; }
        public bool? SaleOnHold { get; set; }
        public bool? VoidSale { get; set; }
        public bool? Payout { get; set; }
        public bool? RequirePayoutAmount { get; set; }
        public DateTime? DateModified { get; set; }
        public DateTime? AuthorizationDateModified { get; set; }
        public bool? POS_CashChecks { get; set; }
        public short? BO_CustCreditLevel { get; set; }
        public bool? POS_Minus { get; set; }
        public bool? POS_ViewTransaction { get; set; }
        public bool? POS_TaxExempt { get; set; }
        public bool? POS_ZOut { get; set; }
        public bool? POS_Gift { get; set; }
        public short? Status { get; set; }
        public bool? POS_AllowChangeForReturen { get; set; }
        public bool POS_AllowManualItem { get; set; }
        public bool? POS_AllowToReprintCoupon { get; set; }
        public bool? BO_ViewTransaction { get; set; }
        public bool? BO_SelectedDepartment { get; set; }
        public Guid? GroupID { get; set; }
    }
}
