// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SQLImportLog
{
    public long id { get; set; }

    public string filename { get; set; } = null!;

    public string? query { get; set; }

    public string? errors { get; set; }

    public DateTime time { get; set; }

    public byte? result { get; set; }
}