// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class sqlStatmentLog
{
    public int id { get; set; }

    public string? sqlString { get; set; }

    public DateTime DateInsert { get; set; }
}