// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SSA_FinishOrder
{
    public Guid PhoneOrderID { get; set; }

    public Guid? UserID { get; set; }

    public DateTime? CreatedDate { get; set; }
}