// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class StateView
{
    public string StateCode { get; set; } = null!;

    public string? StateName { get; set; }

    public int? StateSort { get; set; }
}