// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class StoreToDepartment
{
    public Guid StoreToDepartmentID { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? DepartmentID { get; set; }

    public decimal? DefaultMarkup { get; set; }

    public Guid? RoundUp { get; set; }

    public decimal? RoundValue { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}