// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class StoreInventory
{
    public string? ID { get; set; }

    public string? UPC { get; set; }

    public decimal? OnHand { get; set; }

    public string? StoreNumber { get; set; }

    public short? Status { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid StoreID { get; set; }
}