// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SumAmountPaidByTransaction
{
    public DateTime? DateT { get; set; }

    public decimal SumAmount { get; set; }

    public Guid TransactionID { get; set; }
}