// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Supplier
{
    public Guid SupplierID { get; set; }

    public string? SupplierNo { get; set; }

    public string? Name { get; set; }

    public Guid? DefaultCredit { get; set; }

    public string? WebSite { get; set; }

    public string? EmailAddress { get; set; }

    public Guid? MainAddress { get; set; }

    public string? ContactName { get; set; }

    public Guid? BarterID { get; set; }

    public Guid? WarehouseID { get; set; }

    public string? AccountNo { get; set; }

    public string? Note { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public string? QBNumber { get; set; }

    public Guid? BuyerID { get; set; }

    public decimal? MinMarkup { get; set; }

    public decimal? ListPrice { get; set; }

    public Guid? Department { get; set; }

    public short? Import { get; set; }

    public virtual ICollection<ItemSupply> ItemSupplies { get; set; } = new List<ItemSupply>();

    public virtual SupplierAddress? MainAddressNavigation { get; set; }

    public virtual ICollection<QBSupplier> QBSuppliers { get; set; } = new List<QBSupplier>();
}