// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SupplierListView
{
    public string? SupplierName { get; set; }

    public decimal? NetCost { get; set; }

    public decimal? UOMQty { get; set; }

    public Guid? ItemStoreNo { get; set; }

    public DateTime? ReceiveOrderDate { get; set; }

    public Guid SupplierNo { get; set; }
}