// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SupplierAndCost
{
    public string? Name { get; set; }

    public decimal Amount { get; set; }

    public decimal? Balance { get; set; }
}