// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SupplierGridView
{
    public Guid SupplierID { get; set; }

    public string? SupplierNo { get; set; }

    public string? Name { get; set; }

    public Guid? DefaultCredit { get; set; }

    public string? WebSite { get; set; }

    public string? EmailAddress { get; set; }

    public Guid? MainAddress { get; set; }

    public string? ContactName { get; set; }

    public Guid? BarterID { get; set; }

    public Guid? WarehouseID { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public decimal? OpenInvoice { get; set; }

    public string? LastReceive { get; set; }

    public decimal? DTM { get; set; }

    public decimal? DTP { get; set; }

    public decimal? DTY { get; set; }

    public decimal? Balance { get; set; }

    public string? AccountNo { get; set; }

    public string? Note { get; set; }

    public string? PhoneNumber { get; set; }

    public string? FaxNumber { get; set; }

    public string? PhoneNumber2 { get; set; }
}