// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class SuppyViewCombo
{
    public string? Name { get; set; }

    public Guid SupplierID { get; set; }
}