// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class Sync_ReloadCustomerResult
    {
        public Guid CustomerID { get; set; }
        [StringLength(50)]
        public string? CustomerNo { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; } = default!;
        [StringLength(50)]
        public string LastName { get; set; } = default!;
        public int? PriceLevel { get; set; }
        [Column("Balance", TypeName = "money")]
        public decimal Balance { get; set; }
        [StringLength(50)]
        public string FaxNumber { get; set; } = default!;
        [StringLength(200)]
        public string Address { get; set; } = default!;
        [StringLength(50)]
        public string Address2 { get; set; } = default!;
        [StringLength(100)]
        public string City { get; set; } = default!;
        [StringLength(100)]
        public string State { get; set; } = default!;
        [StringLength(15)]
        public string Zip { get; set; } = default!;
        [StringLength(100)]
        public string PhoneNumber { get; set; } = default!;
        public int DsRowState { get; set; }
    }
}
