// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TaskStatus
{
    public Guid? TaskID { get; set; }

    public DateTime? TaskDate { get; set; }

    public bool? IsEnd { get; set; }

    public string? Error { get; set; }
}