// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TempSale
{
    public string? SalePrice { get; set; }

    public string? SaleQty { get; set; }

    public string? UPC { get; set; }
}