// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class tempitemview
{
    public Guid ItemID { get; set; }

    public string? Name { get; set; }

    public string? ModalNumber { get; set; }

    public Guid? LinkNo { get; set; }

    public string? BarcodeNumber { get; set; }

    public Guid StoreNo { get; set; }

    public bool? IsTaxable { get; set; }

    public bool? IsDiscount { get; set; }

    public bool? IsFoodStampable { get; set; }

    public bool? IsWIC { get; set; }

    public decimal? Cost { get; set; }

    public decimal? Price { get; set; }

    public int? CaseQty { get; set; }

    public bool? PriceByCase { get; set; }

    public string? StyleNo { get; set; }

    public bool? CostByCase { get; set; }

    public string? CaseBarcodeNumber { get; set; }

    public decimal? OnHand { get; set; }

    public decimal? CsOnHand { get; set; }

    public string? BinLocation { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? ItemStoreDateModified { get; set; }

    public DateTime? MainDateModified { get; set; }

    public decimal? Cs_Cost { get; set; }

    public decimal? Pc_Cost { get; set; }

    public short? MainStatus { get; set; }

    public Guid ItemStoreID { get; set; }

    public string? Department { get; set; }

    public string? Matrix1 { get; set; }

    public string? Matrix2 { get; set; }

    public string? Matrix3 { get; set; }

    public string? Matrix4 { get; set; }

    public string? Matrix5 { get; set; }

    public string? Matrix6 { get; set; }

    public string? SupplierName { get; set; }

    public string? ManufacturerPartNo { get; set; }

    public string? SP_Price { get; set; }

    public string? Supplier_Item_Code { get; set; }

    public DateTime? GroupDateModified { get; set; }

    public DateTime? SP_From { get; set; }

    public DateTime? SP_To { get; set; }

    public string? Future_SP_Price { get; set; }

    public DateTime? Future_SP_From { get; set; }

    public DateTime? Future_SP_To { get; set; }

    public decimal? Markup { get; set; }

    public decimal? Margin { get; set; }

    public decimal MTD { get; set; }

    public decimal MTD_Pc_Qty { get; set; }

    public decimal? MTD_Cs_Qty { get; set; }

    public decimal YTD { get; set; }

    public decimal YTD_Pc_Qty { get; set; }

    public decimal? YTD_Cs_Qty { get; set; }

    public decimal PTD { get; set; }

    public decimal PTD_Pc_Qty { get; set; }

    public Guid? MatrixTableNo { get; set; }

    public decimal? PTD_Cs_Qty { get; set; }

    public Guid ItemNo { get; set; }

    public string? Brand { get; set; }

    public int ToReorder { get; set; }

    public string? Size { get; set; }

    public DateTime? DepartmentDateModified { get; set; }

    public int? ItemType { get; set; }

    public Guid? DepartmentID { get; set; }

    public int? ItemTypeName { get; set; }

    public int? BarcodeType { get; set; }

    public decimal? OnOrder { get; set; }

    public decimal? AVGCost { get; set; }

    public decimal? RegCost { get; set; }

    public decimal? ReorderPoint { get; set; }

    public Guid? MainSupplierID { get; set; }

    public decimal? RestockLevel { get; set; }

    public decimal? CasePrice { get; set; }

    public string? CustomerCode { get; set; }

    public decimal? OnTransferOrder { get; set; }

    public string? Groups { get; set; }

    public string? ItemAlias { get; set; }

    public int? ParentCode { get; set; }

    public decimal? RegSPPrice { get; set; }

    public decimal? CaseSPPrice { get; set; }

    public string? RegPkgPrice { get; set; }

    public decimal Reg_SP_Price_Markup { get; set; }

    public decimal Reg_SP_Price_Margin { get; set; }

    public decimal? Pkg_Price_Markup { get; set; }

    public decimal? Pkg_Price_Margin { get; set; }

    public decimal SP_Markup { get; set; }

    public decimal? SP_Margin { get; set; }

    public int? MainDepartment { get; set; }

    public int? SubDepartment { get; set; }

    public int? SubSubDepartment { get; set; }
}