// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class tempDept
{
    public string? size { get; set; }

    public string? uom { get; set; }

    public string? UPC { get; set; }
}