// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TempParentSupply
{
    public Guid ItemStoreID { get; set; }

    public Guid? LinkNo { get; set; }

    public string? Name { get; set; }

    public string? Supplier_Item_Code { get; set; }

    public string? SupplierName { get; set; }
}