// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Temp2
{
    public long? DupeCount { get; set; }

    public decimal CurrBalance { get; set; }

    public Guid? CustomerID { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public string? CustomerNo { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }
}