// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TempItemsDailySummary
{
    public string? StartSaleTime { get; set; }

    public string Name { get; set; } = null!;

    public string? BarcodeNumber { get; set; }

    public string? ModalNumber { get; set; }

    public int? ItemType { get; set; }

    public string? Supplier { get; set; }

    public string? SupplierCode { get; set; }

    public string? Department { get; set; }

    public Guid? DepartmentID { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? UserID { get; set; }

    public Guid? ItemID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Qty { get; set; }

    public string? ItemTypeName { get; set; }

    public decimal? TOTAL { get; set; }

    public decimal? ExtCost { get; set; }

    public decimal? Cost { get; set; }

    public decimal? ExtPrice { get; set; }

    public decimal? RegCost { get; set; }

    public decimal? AVGCost { get; set; }

    public decimal? Price { get; set; }

    public decimal? QtyCase { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Profit { get; set; }

    public decimal? TotalAfterDiscount { get; set; }

    public decimal? RegUnitPrice { get; set; }

    public decimal? UOMPrice { get; set; }

    public string? StoreName { get; set; }
}