// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TenderTotalRec
{
    public short? SortOrder { get; set; }

    public Guid? RegShiftID { get; set; }

    public decimal? Amount { get; set; }

    public string? TenderName { get; set; }

    public string ShiftNO { get; set; } = null!;

    public DateTime? ShiftOpenDate { get; set; }

    public DateTime? ShiftCloseDate { get; set; }

    public decimal? SumTax { get; set; }

    public decimal? SumSale { get; set; }

    public decimal? SumPay { get; set; }

    public int? TenderGroup { get; set; }

    public string? UserName { get; set; }

    public decimal? SumPayOut { get; set; }

    public int CountTender { get; set; }

    public int? TransCount { get; set; }
}