// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class TenMostHighPaidEmployeesResult
    {
        [StringLength(10)]
        public string? TenMostHighPaidEmployees { get; set; }
        public double? SAL { get; set; }
    }
}
