// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class testGuidChild
{
    public string? ChildText { get; set; }

    public DateTime? DateCreated { get; set; }

    public int ChildId { get; set; }

    public int? UserCreated { get; set; }

    public int? ParentId { get; set; }

    public virtual testGuidParent? Parent { get; set; }

    public virtual testGuidUser? UserCreatedNavigation { get; set; }
}