// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TestDel
{
    public Guid ItemNo { get; set; }

    public Guid ItemStoreID { get; set; }

    public int ItemStoreInt { get; set; }

    public Guid StoreNo { get; set; }

    public string? tt { get; set; }
}