// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TestFlushTable
{
    public Guid? RecID { get; set; }

    public Guid? RecEntryID { get; set; }

    public decimal? Freight { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Total { get; set; }

    public decimal? CurrBal { get; set; }

    public DateTime? DateCre { get; set; }

    public DateTime? DateMod { get; set; }

    public decimal? Cost { get; set; }

    public decimal? Qty { get; set; }

    public bool? IsSpecialPrice { get; set; }

    public bool? Taxable { get; set; }
}