// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class testGuidUser
{
    public string? userName { get; set; }

    public DateTime? CreateDate { get; set; }

    public int UserId { get; set; }

    public virtual ICollection<testGuidChild> testGuidChildren { get; set; } = new List<testGuidChild>();

    public virtual ICollection<testGuidParent> testGuidParents { get; set; } = new List<testGuidParent>();
}