// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class testTable
{
    public Guid? ItemID { get; set; }

    public Guid? DateCreated { get; set; }
}