// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class testGuidParent
{
    public string? ParentText { get; set; }

    public DateTime? DateCreated { get; set; }

    public int ParentId { get; set; }

    public int UserCreated { get; set; }

    public virtual testGuidUser UserCreatedNavigation { get; set; } = null!;

    public virtual ICollection<testGuidChild> testGuidChildren { get; set; } = new List<testGuidChild>();
}