// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TransactionEntryDaily
{
    public Guid? ItemID { get; set; }

    public Guid? StoreID { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Total { get; set; }

    public decimal? ExtCost { get; set; }

    public decimal? ExtPrice { get; set; }

    public decimal? AVGCost { get; set; }

    public decimal? Cost { get; set; }

    public decimal? QtyCase { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Profit { get; set; }

    public decimal? TotalAfterDiscount { get; set; }

    public decimal? Qty { get; set; }

    public Guid? DepartmentID { get; set; }

    public Guid? CustomerID { get; set; }
}