// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TransferItem
{
    public Guid TransferID { get; set; }

    public string? TransferNo { get; set; }

    public Guid? FromStoreID { get; set; }

    public Guid? ToStoreID { get; set; }

    public DateTime? TransferDate { get; set; }

    public string? Note { get; set; }

    public Guid? PersonID { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    /// <summary>
    /// 1=Open 2= Partial 3=Close
    /// </summary>
    public int? TransferStatus { get; set; }

    public bool? Emailed { get; set; }
}