// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TransactionEntryQty
{
    public Guid transactionentryid { get; set; }

    public decimal? Qty { get; set; }

    public Guid? ItemStoreID { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public DateTime? EndSaleTime { get; set; }
}