// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TransactionEntryProfit
{
    public Guid TransactionID { get; set; }

    public string TransactionNo { get; set; } = null!;

    public decimal? Debit { get; set; }

    public decimal? Tax { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? CustomerID { get; set; }

    public string CUstomerName { get; set; } = null!;

    public int TransactionType { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public DateTime? EndSaleTime { get; set; }

    public Guid? UserID { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Total { get; set; }

    public decimal? ExtCost { get; set; }

    public decimal? Cost { get; set; }

    public decimal? ExtPrice { get; set; }

    public decimal RegCost { get; set; }

    public decimal AVGCost { get; set; }

    public decimal? Price { get; set; }

    public decimal? QtyCase { get; set; }

    public decimal Discount { get; set; }

    public decimal? Profit { get; set; }

    public decimal? TotalAfterDiscount { get; set; }

    public decimal? RegUnitPrice { get; set; }

    public decimal? UOMPrice { get; set; }

    public decimal? QTY { get; set; }

    public decimal? UOMType { get; set; }

    public Guid? ItemID { get; set; }
}