// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TransEntryToRegEntry
{
    public Guid TransEntryToRegEntryID { get; set; }

    public Guid? TransEntryID { get; set; }

    public Guid? RegEntryID { get; set; }

    public int? Status { get; set; }

    public DateTime? DateCreated { get; set; }
}