// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TransactionEntryItemDailySale
{
    public Guid TransactionEntryID { get; set; }

    public decimal? QTY { get; set; }

    public Guid? ItemStoreID { get; set; }

    public decimal? Total { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public Guid? ItemID { get; set; }

    public string Name { get; set; } = null!;

    public Guid? DepartmentID { get; set; }

    public string? BarcodeNumber { get; set; }

    public string? Department { get; set; }

    public Guid? StoreID { get; set; }
}