// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TransactionBatchView
{
    public Guid BatchID { get; set; }

    public string? BatchNo { get; set; }

    public Guid? RegisterID { get; set; }

    public Guid? UserID { get; set; }

    public Guid? StoreID { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? CloseTime { get; set; }

    public decimal? OpenAmount { get; set; }

    public decimal? ActualCash { get; set; }

    public decimal? Gifts { get; set; }

    public decimal? AccountReceivable { get; set; }

    public decimal? TotalPayOut { get; set; }

    public decimal? LeaveAmount { get; set; }

    public int? Hundred { get; set; }

    public int? Fifty { get; set; }

    public int? Twenty { get; set; }

    public int? Ten { get; set; }

    public int? Five { get; set; }

    public int? Single { get; set; }

    public int? Half { get; set; }

    public int? Quarter { get; set; }

    public int? Dime { get; set; }

    public int? Nickel { get; set; }

    public int? Penny { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}