// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class TransferOrderEntryView
{
    public Guid TransferOrderEntryID { get; set; }

    public Guid? TransferOrderID { get; set; }

    public Guid? ItemStoreNo { get; set; }

    public decimal? Qty { get; set; }

    public decimal? UOMQty { get; set; }

    public int? UOMType { get; set; }

    public decimal? UOMPrice { get; set; }

    public Guid? LinkNo { get; set; }

    public string? Note { get; set; }

    public int? SortOrder { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}