// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class Version
{
    public int VID { get; set; }

    public string VNo { get; set; } = null!;

    public string? VPath { get; set; }

    public DateTime? AddDate { get; set; }

    public string? Status { get; set; }

    public string? Lock { get; set; }

    public string? ProductName { get; set; }
}