// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class W_Transaction
{
    public Guid TransactionID { get; set; }

    public string TransactionNo { get; set; } = null!;

    public int TransactionType { get; set; }

    public bool? RegisterTransaction { get; set; }

    public Guid? BatchID { get; set; }

    public Guid? StoreID { get; set; }

    public Guid? CustomerID { get; set; }

    public decimal? Debit { get; set; }

    public decimal? Credit { get; set; }

    public DateTime? StartSaleTime { get; set; }

    public DateTime? EndSaleTime { get; set; }

    public DateTime? DueDate { get; set; }

    public decimal? CurrBalance { get; set; }

    public decimal? LeftDebit { get; set; }

    public decimal? Freight { get; set; }

    public decimal? Tax { get; set; }

    public string? TaxType { get; set; }

    public decimal? TaxRate { get; set; }

    public Guid? TaxID { get; set; }

    public decimal? Rounding { get; set; }

    public Guid? ShipTo { get; set; }

    public Guid? ShipVia { get; set; }

    public string? PONo { get; set; }

    public Guid? RepID { get; set; }

    public Guid? TermsID { get; set; }

    public bool? PhoneOrder { get; set; }

    public bool? ToPrint { get; set; }

    public bool? ToEmail { get; set; }

    public Guid? CustomerMessage { get; set; }

    public Guid? RegisterID { get; set; }

    public string? RecieptTxt { get; set; }

    public string? Note { get; set; }

    public string? VoidReason { get; set; }

    public Guid? ResellerID { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string? TrackNo { get; set; }

    public short? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }

    public bool? TransferedToBookkeeping { get; set; }
}