// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace BackOffice.Domain.Entities.Tenant
{
    public partial class WEB_GetItemImageResult
    {
        public byte[]? ItemPicture { get; set; }
        public Guid itemid { get; set; }
        public Guid itemstoreid { get; set; }
        public byte[]? ItemPicture2 { get; set; }
        public byte[]? ItemPicture3 { get; set; }
    }
}
