// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class WebItemsView
{
    public string? UPC { get; set; }

    public decimal? Price { get; set; }

    public decimal? OnHand { get; set; }
}