// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class WebItem
{
    public string? sku { get; set; }

    public string? UPC { get; set; }

    public decimal? qty { get; set; }

    public decimal? price { get; set; }

    public decimal? special_price { get; set; }

    public string? special_from_date { get; set; }

    public string? special_to_date { get; set; }
}