// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class WorkerSchedule
{
    public Guid WorkerScheduleID { get; set; }

    public Guid? UserID { get; set; }

    public int? DayOfWeek { get; set; }

    public DateTime? DateOfWeek { get; set; }

    public byte[]? TimeIn { get; set; }

    public DateTime? TimeOut { get; set; }

    public DateTime? TimeIn2 { get; set; }

    public DateTime? TimeOut2 { get; set; }

    public int? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public Guid? UserCreated { get; set; }

    public DateTime? DateModified { get; set; }

    public Guid? UserModified { get; set; }
}