// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class WorkStation
{
    public string ClientStationID { get; set; } = null!;

    public string? ClientStationName { get; set; }

    public byte? ClientStationStatus { get; set; }

    public bool? ChangedDataFlag { get; set; }

    public Guid? UserNo { get; set; }
}