// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BackOffice.Domain.Entities.Tenant;

public partial class ZipCodesView
{
    public string? ZipCode { get; set; }

    public string? City { get; set; }

    public string? StateID { get; set; }
}