# Build and deploy Snap POS Back Office to Azure Web App
name: Build and deploy Node.js app to Azure Web App - snap-pos-backoffice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: BackOffice.Presentation
        run: npm install

      - name: Build project
        working-directory: BackOffice.Presentation
        run: npm run build

      - name: Bundle server with esbuild
        working-directory: BackOffice.Presentation
        run: |
          npm install express esbuild --no-save
          npx esbuild server.js --bundle --platform=node --format=cjs --outfile=dist/server.bundle.cjs

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: BackOffice.Presentation/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F198AF0C6BB48CA9157E4764F34E032 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_36965934B0CC45A5ABCF7064F778A217 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FFB2E9DED6954AD5B91469DE2F3B3CCE }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'snap-pos-backoffice'
          slot-name: 'Production'
          package: .
          startup-command: 'node server.bundle.cjs'
